// Generated by CSymbolGen (Mac; aarch64; 15.4.1) 2025-05-03T00:22:53

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>
#include <termios.h>
#include <signal.h>
#include <errno.h>
#include <sys/ioctl.h>
#ifdef __linux__
#include <linux/serial.h>
#endif
#ifdef __APPLE__
#include <IOKit/serial/ioss.h>
#endif

/*
 * Example code to print symbols and type sizes.
 *
 * Build:
 * gcc <filename>.c -o <filename>; chmod a+x ./<filename>
 * gcc -I<header-include-path> <filename>.c -o <filename>; chmod a+x ./<filename>
 *
 * Run:
 * ./<filename>
 */

#define CERI_STR(x) #x
#define CERI_SYM(x) ceri_print_symbol(#x,CERI_STR(x))
#define CERI_SYMI(x) ceri_print_symbol_i(#x,CERI_STR(x),x)
#define CERI_VSYMI(x,y) ceri_verify_symbol_i(#x,CERI_STR(x),x,y)
#define CERI_SIZE(x) ceri_print_symbol_i("sizeof("#x")","",sizeof(x))
#define CERI_FSIZE(t,f) ceri_print_symbol_i("sizeof("#t"."#f")","",(sizeof(((t*)0)->f)))

int ceri_errors = 0;
int ceri_undefineds = 0;

void ceri_print_symbol(const char *name, const char *sym) {
	printf("%s = ", name);
	if (strlen(sym) == 0) printf("<defined>");
	else if (strcmp(name, sym) == 0) {
		printf("<undefined?>");
		ceri_undefineds++;
	} else printf("\"%s\"", sym);
	printf("\n");
}

void ceri_print_symbol_i(const char *name, const char *sym, long int isym) {
	printf("%s = ", name);
	if (isym > -10 && isym <  10) printf("%ld", isym);
	else printf("%1$ld|0x%1$lx", isym);
	if (strlen(sym) > 0) printf(" \"%s\"", sym);
	printf("\n");
}

void ceri_verify_symbol_i(const char *name, const char *sym, long int isym, long int iexpect) {
	if (isym < -0xffffffff) isym &= 0xffffffff;
	if (isym != iexpect) {
		printf("[ERROR] 0x%lx != ", iexpect);
		ceri_errors++;
	}
	ceri_print_symbol_i(name, sym, isym);
}

int main(int argc, char *argv[]) {
	printf("\n");

	CERI_SIZE(int);
	CERI_SIZE(long);
	CERI_SIZE(size_t);
	CERI_SIZE(mode_t);
	CERI_SIZE(speed_t);
	CERI_SIZE(nfds_t);
	CERI_SIZE(sigset_t);
	CERI_SIZE(time_t);
	CERI_SIZE(struct timeval);
	CERI_FSIZE(struct timeval,tv_sec);
	CERI_FSIZE(struct timeval,tv_usec);
	CERI_SIZE(struct timespec);
	CERI_FSIZE(struct timespec,tv_sec);
	CERI_FSIZE(struct timespec,tv_nsec);
	
	printf("\n// CErrNo types\n");
#if defined(EPERM)
	CERI_VSYMI(EPERM,1);
#else
	CERI_SYM(EPERM); /* 1 */
#endif
#if defined(ENOENT)
	CERI_VSYMI(ENOENT,2);
#else
	CERI_SYM(ENOENT); /* 2 */
#endif
#if defined(ESRCH)
	CERI_VSYMI(ESRCH,3);
#else
	CERI_SYM(ESRCH); /* 3 */
#endif
#if defined(EINTR)
	CERI_VSYMI(EINTR,4);
#else
	CERI_SYM(EINTR); /* 4 */
#endif
#if defined(EIO)
	CERI_VSYMI(EIO,5);
#else
	CERI_SYM(EIO); /* 5 */
#endif
#if defined(ENXIO)
	CERI_VSYMI(ENXIO,6);
#else
	CERI_SYM(ENXIO); /* 6 */
#endif
#if defined(E2BIG)
	CERI_VSYMI(E2BIG,7);
#else
	CERI_SYM(E2BIG); /* 7 */
#endif
#if defined(ENOEXEC)
	CERI_VSYMI(ENOEXEC,8);
#else
	CERI_SYM(ENOEXEC); /* 8 */
#endif
#if defined(EBADF)
	CERI_VSYMI(EBADF,9);
#else
	CERI_SYM(EBADF); /* 9 */
#endif
#if defined(ECHILD)
	CERI_VSYMI(ECHILD,10);
#else
	CERI_SYM(ECHILD); /* 10|0xa */
#endif
#if defined(EAGAIN)
	CERI_VSYMI(EAGAIN,35);
#else
	CERI_SYM(EAGAIN); /* 35|0x23 */
#endif
#if defined(EWOULDBLOCK)
	CERI_VSYMI(EWOULDBLOCK,35);
#else
	CERI_SYM(EWOULDBLOCK); /* 35|0x23 */
#endif
#if defined(ENOMEM)
	CERI_VSYMI(ENOMEM,12);
#else
	CERI_SYM(ENOMEM); /* 12|0xc */
#endif
#if defined(EACCES)
	CERI_VSYMI(EACCES,13);
#else
	CERI_SYM(EACCES); /* 13|0xd */
#endif
#if defined(EFAULT)
	CERI_VSYMI(EFAULT,14);
#else
	CERI_SYM(EFAULT); /* 14|0xe */
#endif
#if defined(ENOTBLK)
	CERI_VSYMI(ENOTBLK,15);
#else
	CERI_SYM(ENOTBLK); /* 15|0xf */
#endif
#if defined(EBUSY)
	CERI_VSYMI(EBUSY,16);
#else
	CERI_SYM(EBUSY); /* 16|0x10 */
#endif
#if defined(EEXIST)
	CERI_VSYMI(EEXIST,17);
#else
	CERI_SYM(EEXIST); /* 17|0x11 */
#endif
#if defined(EXDEV)
	CERI_VSYMI(EXDEV,18);
#else
	CERI_SYM(EXDEV); /* 18|0x12 */
#endif
#if defined(ENODEV)
	CERI_VSYMI(ENODEV,19);
#else
	CERI_SYM(ENODEV); /* 19|0x13 */
#endif
#if defined(ENOTDIR)
	CERI_VSYMI(ENOTDIR,20);
#else
	CERI_SYM(ENOTDIR); /* 20|0x14 */
#endif
#if defined(EISDIR)
	CERI_VSYMI(EISDIR,21);
#else
	CERI_SYM(EISDIR); /* 21|0x15 */
#endif
#if defined(EINVAL)
	CERI_VSYMI(EINVAL,22);
#else
	CERI_SYM(EINVAL); /* 22|0x16 */
#endif
#if defined(ENFILE)
	CERI_VSYMI(ENFILE,23);
#else
	CERI_SYM(ENFILE); /* 23|0x17 */
#endif
#if defined(EMFILE)
	CERI_VSYMI(EMFILE,24);
#else
	CERI_SYM(EMFILE); /* 24|0x18 */
#endif
#if defined(ENOTTY)
	CERI_VSYMI(ENOTTY,25);
#else
	CERI_SYM(ENOTTY); /* 25|0x19 */
#endif
#if defined(ETXTBSY)
	CERI_VSYMI(ETXTBSY,26);
#else
	CERI_SYM(ETXTBSY); /* 26|0x1a */
#endif
#if defined(EFBIG)
	CERI_VSYMI(EFBIG,27);
#else
	CERI_SYM(EFBIG); /* 27|0x1b */
#endif
#if defined(ENOSPC)
	CERI_VSYMI(ENOSPC,28);
#else
	CERI_SYM(ENOSPC); /* 28|0x1c */
#endif
#if defined(ESPIPE)
	CERI_VSYMI(ESPIPE,29);
#else
	CERI_SYM(ESPIPE); /* 29|0x1d */
#endif
#if defined(EROFS)
	CERI_VSYMI(EROFS,30);
#else
	CERI_SYM(EROFS); /* 30|0x1e */
#endif
#if defined(EMLINK)
	CERI_VSYMI(EMLINK,31);
#else
	CERI_SYM(EMLINK); /* 31|0x1f */
#endif
#if defined(EPIPE)
	CERI_VSYMI(EPIPE,32);
#else
	CERI_SYM(EPIPE); /* 32|0x20 */
#endif
#if defined(EDOM)
	CERI_VSYMI(EDOM,33);
#else
	CERI_SYM(EDOM); /* 33|0x21 */
#endif
#if defined(ERANGE)
	CERI_VSYMI(ERANGE,34);
#else
	CERI_SYM(ERANGE); /* 34|0x22 */
#endif
#if defined(EDEADLK)
	CERI_VSYMI(EDEADLK,11);
#else
	CERI_SYM(EDEADLK); /* 11|0xb */
#endif
#if defined(ENAMETOOLONG)
	CERI_VSYMI(ENAMETOOLONG,63);
#else
	CERI_SYM(ENAMETOOLONG); /* 63|0x3f */
#endif
#if defined(ENOLCK)
	CERI_VSYMI(ENOLCK,77);
#else
	CERI_SYM(ENOLCK); /* 77|0x4d */
#endif
#if defined(ENOSYS)
	CERI_VSYMI(ENOSYS,78);
#else
	CERI_SYM(ENOSYS); /* 78|0x4e */
#endif
#if defined(ENOTEMPTY)
	CERI_VSYMI(ENOTEMPTY,66);
#else
	CERI_SYM(ENOTEMPTY); /* 66|0x42 */
#endif
#if defined(ELOOP)
	CERI_VSYMI(ELOOP,62);
#else
	CERI_SYM(ELOOP); /* 62|0x3e */
#endif
#if defined(ENOMSG)
	CERI_VSYMI(ENOMSG,91);
#else
	CERI_SYM(ENOMSG); /* 91|0x5b */
#endif
#if defined(EIDRM)
	CERI_VSYMI(EIDRM,90);
#else
	CERI_SYM(EIDRM); /* 90|0x5a */
#endif
#if defined(ENOSTR)
	CERI_VSYMI(ENOSTR,99);
#else
	CERI_SYM(ENOSTR); /* 99|0x63 */
#endif
#if defined(ENODATA)
	CERI_VSYMI(ENODATA,96);
#else
	CERI_SYM(ENODATA); /* 96|0x60 */
#endif
#if defined(ETIME)
	CERI_VSYMI(ETIME,101);
#else
	CERI_SYM(ETIME); /* 101|0x65 */
#endif
#if defined(ENOSR)
	CERI_VSYMI(ENOSR,98);
#else
	CERI_SYM(ENOSR); /* 98|0x62 */
#endif
#if defined(EREMOTE)
	CERI_VSYMI(EREMOTE,71);
#else
	CERI_SYM(EREMOTE); /* 71|0x47 */
#endif
#if defined(ENOLINK)
	CERI_VSYMI(ENOLINK,97);
#else
	CERI_SYM(ENOLINK); /* 97|0x61 */
#endif
#if defined(EPROTO)
	CERI_VSYMI(EPROTO,100);
#else
	CERI_SYM(EPROTO); /* 100|0x64 */
#endif
#if defined(EMULTIHOP)
	CERI_VSYMI(EMULTIHOP,95);
#else
	CERI_SYM(EMULTIHOP); /* 95|0x5f */
#endif
#if defined(EBADMSG)
	CERI_VSYMI(EBADMSG,94);
#else
	CERI_SYM(EBADMSG); /* 94|0x5e */
#endif
#if defined(EOVERFLOW)
	CERI_VSYMI(EOVERFLOW,84);
#else
	CERI_SYM(EOVERFLOW); /* 84|0x54 */
#endif
#if defined(EILSEQ)
	CERI_VSYMI(EILSEQ,92);
#else
	CERI_SYM(EILSEQ); /* 92|0x5c */
#endif
#if defined(EUSERS)
	CERI_VSYMI(EUSERS,68);
#else
	CERI_SYM(EUSERS); /* 68|0x44 */
#endif
#if defined(ENOTSOCK)
	CERI_VSYMI(ENOTSOCK,38);
#else
	CERI_SYM(ENOTSOCK); /* 38|0x26 */
#endif
#if defined(EDESTADDRREQ)
	CERI_VSYMI(EDESTADDRREQ,39);
#else
	CERI_SYM(EDESTADDRREQ); /* 39|0x27 */
#endif
#if defined(EMSGSIZE)
	CERI_VSYMI(EMSGSIZE,40);
#else
	CERI_SYM(EMSGSIZE); /* 40|0x28 */
#endif
#if defined(EPROTOTYPE)
	CERI_VSYMI(EPROTOTYPE,41);
#else
	CERI_SYM(EPROTOTYPE); /* 41|0x29 */
#endif
#if defined(ENOPROTOOPT)
	CERI_VSYMI(ENOPROTOOPT,42);
#else
	CERI_SYM(ENOPROTOOPT); /* 42|0x2a */
#endif
#if defined(EPROTONOSUPPORT)
	CERI_VSYMI(EPROTONOSUPPORT,43);
#else
	CERI_SYM(EPROTONOSUPPORT); /* 43|0x2b */
#endif
#if defined(ESOCKTNOSUPPORT)
	CERI_VSYMI(ESOCKTNOSUPPORT,44);
#else
	CERI_SYM(ESOCKTNOSUPPORT); /* 44|0x2c */
#endif
#if defined(EOPNOTSUPP)
	CERI_VSYMI(EOPNOTSUPP,102);
#else
	CERI_SYM(EOPNOTSUPP); /* 102|0x66 */
#endif
#if defined(ENOTSUP)
	CERI_VSYMI(ENOTSUP,45);
#else
	CERI_SYM(ENOTSUP); /* 45|0x2d */
#endif
#if defined(EPFNOSUPPORT)
	CERI_VSYMI(EPFNOSUPPORT,46);
#else
	CERI_SYM(EPFNOSUPPORT); /* 46|0x2e */
#endif
#if defined(EAFNOSUPPORT)
	CERI_VSYMI(EAFNOSUPPORT,47);
#else
	CERI_SYM(EAFNOSUPPORT); /* 47|0x2f */
#endif
#if defined(EADDRINUSE)
	CERI_VSYMI(EADDRINUSE,48);
#else
	CERI_SYM(EADDRINUSE); /* 48|0x30 */
#endif
#if defined(EADDRNOTAVAIL)
	CERI_VSYMI(EADDRNOTAVAIL,49);
#else
	CERI_SYM(EADDRNOTAVAIL); /* 49|0x31 */
#endif
#if defined(ENETDOWN)
	CERI_VSYMI(ENETDOWN,50);
#else
	CERI_SYM(ENETDOWN); /* 50|0x32 */
#endif
#if defined(ENETUNREACH)
	CERI_VSYMI(ENETUNREACH,51);
#else
	CERI_SYM(ENETUNREACH); /* 51|0x33 */
#endif
#if defined(ENETRESET)
	CERI_VSYMI(ENETRESET,52);
#else
	CERI_SYM(ENETRESET); /* 52|0x34 */
#endif
#if defined(ECONNABORTED)
	CERI_VSYMI(ECONNABORTED,53);
#else
	CERI_SYM(ECONNABORTED); /* 53|0x35 */
#endif
#if defined(ECONNRESET)
	CERI_VSYMI(ECONNRESET,54);
#else
	CERI_SYM(ECONNRESET); /* 54|0x36 */
#endif
#if defined(ENOBUFS)
	CERI_VSYMI(ENOBUFS,55);
#else
	CERI_SYM(ENOBUFS); /* 55|0x37 */
#endif
#if defined(EISCONN)
	CERI_VSYMI(EISCONN,56);
#else
	CERI_SYM(EISCONN); /* 56|0x38 */
#endif
#if defined(ENOTCONN)
	CERI_VSYMI(ENOTCONN,57);
#else
	CERI_SYM(ENOTCONN); /* 57|0x39 */
#endif
#if defined(ESHUTDOWN)
	CERI_VSYMI(ESHUTDOWN,58);
#else
	CERI_SYM(ESHUTDOWN); /* 58|0x3a */
#endif
#if defined(ETOOMANYREFS)
	CERI_VSYMI(ETOOMANYREFS,59);
#else
	CERI_SYM(ETOOMANYREFS); /* 59|0x3b */
#endif
#if defined(ETIMEDOUT)
	CERI_VSYMI(ETIMEDOUT,60);
#else
	CERI_SYM(ETIMEDOUT); /* 60|0x3c */
#endif
#if defined(ECONNREFUSED)
	CERI_VSYMI(ECONNREFUSED,61);
#else
	CERI_SYM(ECONNREFUSED); /* 61|0x3d */
#endif
#if defined(EHOSTDOWN)
	CERI_VSYMI(EHOSTDOWN,64);
#else
	CERI_SYM(EHOSTDOWN); /* 64|0x40 */
#endif
#if defined(EHOSTUNREACH)
	CERI_VSYMI(EHOSTUNREACH,65);
#else
	CERI_SYM(EHOSTUNREACH); /* 65|0x41 */
#endif
#if defined(EALREADY)
	CERI_VSYMI(EALREADY,37);
#else
	CERI_SYM(EALREADY); /* 37|0x25 */
#endif
#if defined(EINPROGRESS)
	CERI_VSYMI(EINPROGRESS,36);
#else
	CERI_SYM(EINPROGRESS); /* 36|0x24 */
#endif
#if defined(ESTALE)
	CERI_VSYMI(ESTALE,70);
#else
	CERI_SYM(ESTALE); /* 70|0x46 */
#endif
#if defined(EDQUOT)
	CERI_VSYMI(EDQUOT,69);
#else
	CERI_SYM(EDQUOT); /* 69|0x45 */
#endif
#if defined(ECANCELED)
	CERI_VSYMI(ECANCELED,89);
#else
	CERI_SYM(ECANCELED); /* 89|0x59 */
#endif
#if defined(EOWNERDEAD)
	CERI_VSYMI(EOWNERDEAD,105);
#else
	CERI_SYM(EOWNERDEAD); /* 105|0x69 */
#endif
#if defined(ENOTRECOVERABLE)
	CERI_VSYMI(ENOTRECOVERABLE,104);
#else
	CERI_SYM(ENOTRECOVERABLE); /* 104|0x68 */
#endif
#if defined(EAUTH)
	CERI_VSYMI(EAUTH,80);
#else
	CERI_SYM(EAUTH); /* 80|0x50 */
#endif
#if defined(EBADRPC)
	CERI_VSYMI(EBADRPC,72);
#else
	CERI_SYM(EBADRPC); /* 72|0x48 */
#endif
#if defined(EFTYPE)
	CERI_VSYMI(EFTYPE,79);
#else
	CERI_SYM(EFTYPE); /* 79|0x4f */
#endif
#if defined(ENEEDAUTH)
	CERI_VSYMI(ENEEDAUTH,81);
#else
	CERI_SYM(ENEEDAUTH); /* 81|0x51 */
#endif
#if defined(ENOATTR)
	CERI_VSYMI(ENOATTR,93);
#else
	CERI_SYM(ENOATTR); /* 93|0x5d */
#endif
#if defined(EPROCLIM)
	CERI_VSYMI(EPROCLIM,67);
#else
	CERI_SYM(EPROCLIM); /* 67|0x43 */
#endif
#if defined(EPROCUNAVAIL)
	CERI_VSYMI(EPROCUNAVAIL,76);
#else
	CERI_SYM(EPROCUNAVAIL); /* 76|0x4c */
#endif
#if defined(EPROGMISMATCH)
	CERI_VSYMI(EPROGMISMATCH,75);
#else
	CERI_SYM(EPROGMISMATCH); /* 75|0x4b */
#endif
#if defined(EPROGUNAVAIL)
	CERI_VSYMI(EPROGUNAVAIL,74);
#else
	CERI_SYM(EPROGUNAVAIL); /* 74|0x4a */
#endif
#if defined(ERPCMISMATCH)
	CERI_VSYMI(ERPCMISMATCH,73);
#else
	CERI_SYM(ERPCMISMATCH); /* 73|0x49 */
#endif
	
	printf("\n// CFcntl types\n");
#if defined(O_RDONLY)
	CERI_VSYMI(O_RDONLY,0);
#else
	CERI_SYM(O_RDONLY); /* 0 */
#endif
#if defined(O_WRONLY)
	CERI_VSYMI(O_WRONLY,1);
#else
	CERI_SYM(O_WRONLY); /* 1 */
#endif
#if defined(O_RDWR)
	CERI_VSYMI(O_RDWR,2);
#else
	CERI_SYM(O_RDWR); /* 2 */
#endif
#if defined(O_ACCMODE)
	CERI_VSYMI(O_ACCMODE,3);
#else
	CERI_SYM(O_ACCMODE); /* 3 */
#endif
#if defined(O_CREAT)
	CERI_VSYMI(O_CREAT,512);
#else
	CERI_SYM(O_CREAT); /* 512|0x200 */
#endif
#if defined(O_EXCL)
	CERI_VSYMI(O_EXCL,2048);
#else
	CERI_SYM(O_EXCL); /* 2048|0x800 */
#endif
#if defined(O_NOCTTY)
	CERI_VSYMI(O_NOCTTY,131072);
#else
	CERI_SYM(O_NOCTTY); /* 131072|0x20000 */
#endif
#if defined(O_TRUNC)
	CERI_VSYMI(O_TRUNC,1024);
#else
	CERI_SYM(O_TRUNC); /* 1024|0x400 */
#endif
#if defined(O_APPEND)
	CERI_VSYMI(O_APPEND,8);
#else
	CERI_SYM(O_APPEND); /* 8 */
#endif
#if defined(O_NONBLOCK)
	CERI_VSYMI(O_NONBLOCK,4);
#else
	CERI_SYM(O_NONBLOCK); /* 4 */
#endif
#if defined(O_DSYNC)
	CERI_VSYMI(O_DSYNC,4194304);
#else
	CERI_SYM(O_DSYNC); /* 4194304|0x400000 */
#endif
#if defined(O_ASYNC)
	CERI_VSYMI(O_ASYNC,64);
#else
	CERI_SYM(O_ASYNC); /* 64|0x40 */
#endif
#if defined(O_DIRECTORY)
	CERI_VSYMI(O_DIRECTORY,1048576);
#else
	CERI_SYM(O_DIRECTORY); /* 1048576|0x100000 */
#endif
#if defined(O_NOFOLLOW)
	CERI_VSYMI(O_NOFOLLOW,256);
#else
	CERI_SYM(O_NOFOLLOW); /* 256|0x100 */
#endif
#if defined(O_CLOEXEC)
	CERI_VSYMI(O_CLOEXEC,16777216);
#else
	CERI_SYM(O_CLOEXEC); /* 16777216|0x1000000 */
#endif
#if defined(O_SYNC)
	CERI_VSYMI(O_SYNC,128);
#else
	CERI_SYM(O_SYNC); /* 128|0x80 */
#endif
	
	printf("\n// CIoctl types\n");
#if defined(IOC_VOID)
	CERI_VSYMI(IOC_VOID,536870912);
#else
	CERI_SYM(IOC_VOID); /* 536870912|0x20000000 */
#endif
#if defined(IOC_OUT)
	CERI_VSYMI(IOC_OUT,1073741824);
#else
	CERI_SYM(IOC_OUT); /* 1073741824|0x40000000 */
#endif
#if defined(IOC_IN)
	CERI_VSYMI(IOC_IN,2147483648);
#else
	CERI_SYM(IOC_IN); /* 2147483648|0x80000000 */
#endif
#if defined(TIOCSBRK)
	CERI_VSYMI(TIOCSBRK,536900731);
#else
	CERI_SYM(TIOCSBRK); /* 536900731|0x2000747b */
#endif
#if defined(TIOCCBRK)
	CERI_VSYMI(TIOCCBRK,536900730);
#else
	CERI_SYM(TIOCCBRK); /* 536900730|0x2000747a */
#endif
#if defined(FIONREAD)
	CERI_VSYMI(FIONREAD,1074030207);
#else
	CERI_SYM(FIONREAD); /* 1074030207|0x4004667f */
#endif
#if defined(TIOCEXCL)
	CERI_VSYMI(TIOCEXCL,536900621);
#else
	CERI_SYM(TIOCEXCL); /* 536900621|0x2000740d */
#endif
#if defined(TIOCOUTQ)
	CERI_VSYMI(TIOCOUTQ,1074033779);
#else
	CERI_SYM(TIOCOUTQ); /* 1074033779|0x40047473 */
#endif
#if defined(TIOCMGET)
	CERI_VSYMI(TIOCMGET,1074033770);
#else
	CERI_SYM(TIOCMGET); /* 1074033770|0x4004746a */
#endif
#if defined(TIOCMBIC)
	CERI_VSYMI(TIOCMBIC,2147775595);
#else
	CERI_SYM(TIOCMBIC); /* 2147775595|0x8004746b */
#endif
#if defined(TIOCMBIS)
	CERI_VSYMI(TIOCMBIS,2147775596);
#else
	CERI_SYM(TIOCMBIS); /* 2147775596|0x8004746c */
#endif
#if defined(TIOCMSET)
	CERI_VSYMI(TIOCMSET,2147775597);
#else
	CERI_SYM(TIOCMSET); /* 2147775597|0x8004746d */
#endif
#if defined(TIOCM_LE)
	CERI_VSYMI(TIOCM_LE,1);
#else
	CERI_SYM(TIOCM_LE); /* 1 */
#endif
#if defined(TIOCM_DTR)
	CERI_VSYMI(TIOCM_DTR,2);
#else
	CERI_SYM(TIOCM_DTR); /* 2 */
#endif
#if defined(TIOCM_RTS)
	CERI_VSYMI(TIOCM_RTS,4);
#else
	CERI_SYM(TIOCM_RTS); /* 4 */
#endif
#if defined(TIOCM_CTS)
	CERI_VSYMI(TIOCM_CTS,32);
#else
	CERI_SYM(TIOCM_CTS); /* 32|0x20 */
#endif
#if defined(TIOCM_CD)
	CERI_VSYMI(TIOCM_CD,64);
#else
	CERI_SYM(TIOCM_CD); /* 64|0x40 */
#endif
#if defined(TIOCM_RI)
	CERI_VSYMI(TIOCM_RI,128);
#else
	CERI_SYM(TIOCM_RI); /* 128|0x80 */
#endif
#if defined(TIOCM_DSR)
	CERI_VSYMI(TIOCM_DSR,256);
#else
	CERI_SYM(TIOCM_DSR); /* 256|0x100 */
#endif
	
	printf("\n// CIoctl.Mac types\n");
#if defined(IOSSIOSPEED)
	CERI_VSYMI(IOSSIOSPEED,2148029442);
#else
	CERI_SYM(IOSSIOSPEED); /* 2148029442|0x80085402 */
#endif
	
	printf("\n// CPoll types\n");
#if defined(POLLIN)
	CERI_VSYMI(POLLIN,1);
#else
	CERI_SYM(POLLIN); /* 1 */
#endif
#if defined(POLLPRI)
	CERI_VSYMI(POLLPRI,2);
#else
	CERI_SYM(POLLPRI); /* 2 */
#endif
#if defined(POLLOUT)
	CERI_VSYMI(POLLOUT,4);
#else
	CERI_SYM(POLLOUT); /* 4 */
#endif
#if defined(POLLERR)
	CERI_VSYMI(POLLERR,8);
#else
	CERI_SYM(POLLERR); /* 8 */
#endif
#if defined(POLLHUP)
	CERI_VSYMI(POLLHUP,16);
#else
	CERI_SYM(POLLHUP); /* 16|0x10 */
#endif
#if defined(POLLNVAL)
	CERI_VSYMI(POLLNVAL,32);
#else
	CERI_SYM(POLLNVAL); /* 32|0x20 */
#endif
	
	printf("\n// CSignal types\n");
#if defined(SIGHUP)
	CERI_VSYMI(SIGHUP,1);
#else
	CERI_SYM(SIGHUP); /* 1 */
#endif
#if defined(SIGINT)
	CERI_VSYMI(SIGINT,2);
#else
	CERI_SYM(SIGINT); /* 2 */
#endif
#if defined(SIGQUIT)
	CERI_VSYMI(SIGQUIT,3);
#else
	CERI_SYM(SIGQUIT); /* 3 */
#endif
#if defined(SIGILL)
	CERI_VSYMI(SIGILL,4);
#else
	CERI_SYM(SIGILL); /* 4 */
#endif
#if defined(SIGTRAP)
	CERI_VSYMI(SIGTRAP,5);
#else
	CERI_SYM(SIGTRAP); /* 5 */
#endif
#if defined(SIGABRT)
	CERI_VSYMI(SIGABRT,6);
#else
	CERI_SYM(SIGABRT); /* 6 */
#endif
#if defined(SIGIOT)
	CERI_VSYMI(SIGIOT,6);
#else
	CERI_SYM(SIGIOT); /* 6 */
#endif
#if defined(SIGBUS)
	CERI_VSYMI(SIGBUS,10);
#else
	CERI_SYM(SIGBUS); /* 10|0xa */
#endif
#if defined(SIGFPE)
	CERI_VSYMI(SIGFPE,8);
#else
	CERI_SYM(SIGFPE); /* 8 */
#endif
#if defined(SIGKILL)
	CERI_VSYMI(SIGKILL,9);
#else
	CERI_SYM(SIGKILL); /* 9 */
#endif
#if defined(SIGUSR1)
	CERI_VSYMI(SIGUSR1,30);
#else
	CERI_SYM(SIGUSR1); /* 30|0x1e */
#endif
#if defined(SIGSEGV)
	CERI_VSYMI(SIGSEGV,11);
#else
	CERI_SYM(SIGSEGV); /* 11|0xb */
#endif
#if defined(SIGUSR2)
	CERI_VSYMI(SIGUSR2,31);
#else
	CERI_SYM(SIGUSR2); /* 31|0x1f */
#endif
#if defined(SIGPIPE)
	CERI_VSYMI(SIGPIPE,13);
#else
	CERI_SYM(SIGPIPE); /* 13|0xd */
#endif
#if defined(SIGALRM)
	CERI_VSYMI(SIGALRM,14);
#else
	CERI_SYM(SIGALRM); /* 14|0xe */
#endif
#if defined(SIGTERM)
	CERI_VSYMI(SIGTERM,15);
#else
	CERI_SYM(SIGTERM); /* 15|0xf */
#endif
#if defined(SIGCHLD)
	CERI_VSYMI(SIGCHLD,20);
#else
	CERI_SYM(SIGCHLD); /* 20|0x14 */
#endif
#if defined(SIGCONT)
	CERI_VSYMI(SIGCONT,19);
#else
	CERI_SYM(SIGCONT); /* 19|0x13 */
#endif
#if defined(SIGSTOP)
	CERI_VSYMI(SIGSTOP,17);
#else
	CERI_SYM(SIGSTOP); /* 17|0x11 */
#endif
#if defined(SIGTSTP)
	CERI_VSYMI(SIGTSTP,18);
#else
	CERI_SYM(SIGTSTP); /* 18|0x12 */
#endif
#if defined(SIGTTIN)
	CERI_VSYMI(SIGTTIN,21);
#else
	CERI_SYM(SIGTTIN); /* 21|0x15 */
#endif
#if defined(SIGTTOU)
	CERI_VSYMI(SIGTTOU,22);
#else
	CERI_SYM(SIGTTOU); /* 22|0x16 */
#endif
#if defined(SIGURG)
	CERI_VSYMI(SIGURG,16);
#else
	CERI_SYM(SIGURG); /* 16|0x10 */
#endif
#if defined(SIGXCPU)
	CERI_VSYMI(SIGXCPU,24);
#else
	CERI_SYM(SIGXCPU); /* 24|0x18 */
#endif
#if defined(SIGXFSZ)
	CERI_VSYMI(SIGXFSZ,25);
#else
	CERI_SYM(SIGXFSZ); /* 25|0x19 */
#endif
#if defined(SIGVTALRM)
	CERI_VSYMI(SIGVTALRM,26);
#else
	CERI_SYM(SIGVTALRM); /* 26|0x1a */
#endif
#if defined(SIGPROF)
	CERI_VSYMI(SIGPROF,27);
#else
	CERI_SYM(SIGPROF); /* 27|0x1b */
#endif
#if defined(SIGWINCH)
	CERI_VSYMI(SIGWINCH,28);
#else
	CERI_SYM(SIGWINCH); /* 28|0x1c */
#endif
#if defined(SIGIO)
	CERI_VSYMI(SIGIO,23);
#else
	CERI_SYM(SIGIO); /* 23|0x17 */
#endif
#if defined(SIGSYS)
	CERI_VSYMI(SIGSYS,12);
#else
	CERI_SYM(SIGSYS); /* 12|0xc */
#endif
	CERI_SYM(SIG_DFL); /* 0 */
	CERI_SYM(SIG_IGN); /* 1 */
	CERI_SYM(SIG_ERR); /* -1 */
	
	printf("\n// CTermios types\n");
#if defined(IGNBRK)
	CERI_VSYMI(IGNBRK,1);
#else
	CERI_SYM(IGNBRK); /* 1 */
#endif
#if defined(BRKINT)
	CERI_VSYMI(BRKINT,2);
#else
	CERI_SYM(BRKINT); /* 2 */
#endif
#if defined(IGNPAR)
	CERI_VSYMI(IGNPAR,4);
#else
	CERI_SYM(IGNPAR); /* 4 */
#endif
#if defined(PARMRK)
	CERI_VSYMI(PARMRK,8);
#else
	CERI_SYM(PARMRK); /* 8 */
#endif
#if defined(INPCK)
	CERI_VSYMI(INPCK,16);
#else
	CERI_SYM(INPCK); /* 16|0x10 */
#endif
#if defined(ISTRIP)
	CERI_VSYMI(ISTRIP,32);
#else
	CERI_SYM(ISTRIP); /* 32|0x20 */
#endif
#if defined(INLCR)
	CERI_VSYMI(INLCR,64);
#else
	CERI_SYM(INLCR); /* 64|0x40 */
#endif
#if defined(IGNCR)
	CERI_VSYMI(IGNCR,128);
#else
	CERI_SYM(IGNCR); /* 128|0x80 */
#endif
#if defined(ICRNL)
	CERI_VSYMI(ICRNL,256);
#else
	CERI_SYM(ICRNL); /* 256|0x100 */
#endif
#if defined(IXON)
	CERI_VSYMI(IXON,512);
#else
	CERI_SYM(IXON); /* 512|0x200 */
#endif
#if defined(IXANY)
	CERI_VSYMI(IXANY,2048);
#else
	CERI_SYM(IXANY); /* 2048|0x800 */
#endif
#if defined(IXOFF)
	CERI_VSYMI(IXOFF,1024);
#else
	CERI_SYM(IXOFF); /* 1024|0x400 */
#endif
#if defined(IMAXBEL)
	CERI_VSYMI(IMAXBEL,8192);
#else
	CERI_SYM(IMAXBEL); /* 8192|0x2000 */
#endif
#if defined(IUTF8)
	CERI_VSYMI(IUTF8,16384);
#else
	CERI_SYM(IUTF8); /* 16384|0x4000 */
#endif
#if defined(OPOST)
	CERI_VSYMI(OPOST,1);
#else
	CERI_SYM(OPOST); /* 1 */
#endif
#if defined(ONLCR)
	CERI_VSYMI(ONLCR,2);
#else
	CERI_SYM(ONLCR); /* 2 */
#endif
#if defined(OCRNL)
	CERI_VSYMI(OCRNL,16);
#else
	CERI_SYM(OCRNL); /* 16|0x10 */
#endif
#if defined(ONOCR)
	CERI_VSYMI(ONOCR,32);
#else
	CERI_SYM(ONOCR); /* 32|0x20 */
#endif
#if defined(ONLRET)
	CERI_VSYMI(ONLRET,64);
#else
	CERI_SYM(ONLRET); /* 64|0x40 */
#endif
#if defined(OFILL)
	CERI_VSYMI(OFILL,128);
#else
	CERI_SYM(OFILL); /* 128|0x80 */
#endif
#if defined(OFDEL)
	CERI_VSYMI(OFDEL,131072);
#else
	CERI_SYM(OFDEL); /* 131072|0x20000 */
#endif
#if defined(CSIZE)
	CERI_VSYMI(CSIZE,768);
#else
	CERI_SYM(CSIZE); /* 768|0x300 */
#endif
#if defined(CSTOPB)
	CERI_VSYMI(CSTOPB,1024);
#else
	CERI_SYM(CSTOPB); /* 1024|0x400 */
#endif
#if defined(CREAD)
	CERI_VSYMI(CREAD,2048);
#else
	CERI_SYM(CREAD); /* 2048|0x800 */
#endif
#if defined(PARENB)
	CERI_VSYMI(PARENB,4096);
#else
	CERI_SYM(PARENB); /* 4096|0x1000 */
#endif
#if defined(PARODD)
	CERI_VSYMI(PARODD,8192);
#else
	CERI_SYM(PARODD); /* 8192|0x2000 */
#endif
#if defined(HUPCL)
	CERI_VSYMI(HUPCL,16384);
#else
	CERI_SYM(HUPCL); /* 16384|0x4000 */
#endif
#if defined(CLOCAL)
	CERI_VSYMI(CLOCAL,32768);
#else
	CERI_SYM(CLOCAL); /* 32768|0x8000 */
#endif
#if defined(CRTSCTS)
	CERI_VSYMI(CRTSCTS,196608);
#else
	CERI_SYM(CRTSCTS); /* 196608|0x30000 */
#endif
#if defined(CS5)
	CERI_VSYMI(CS5,0);
#else
	CERI_SYM(CS5); /* 0 */
#endif
#if defined(CS6)
	CERI_VSYMI(CS6,256);
#else
	CERI_SYM(CS6); /* 256|0x100 */
#endif
#if defined(CS7)
	CERI_VSYMI(CS7,512);
#else
	CERI_SYM(CS7); /* 512|0x200 */
#endif
#if defined(CS8)
	CERI_VSYMI(CS8,768);
#else
	CERI_SYM(CS8); /* 768|0x300 */
#endif
#if defined(ISIG)
	CERI_VSYMI(ISIG,128);
#else
	CERI_SYM(ISIG); /* 128|0x80 */
#endif
#if defined(ICANON)
	CERI_VSYMI(ICANON,256);
#else
	CERI_SYM(ICANON); /* 256|0x100 */
#endif
#if defined(ECHO)
	CERI_VSYMI(ECHO,8);
#else
	CERI_SYM(ECHO); /* 8 */
#endif
#if defined(ECHOE)
	CERI_VSYMI(ECHOE,2);
#else
	CERI_SYM(ECHOE); /* 2 */
#endif
#if defined(ECHOK)
	CERI_VSYMI(ECHOK,4);
#else
	CERI_SYM(ECHOK); /* 4 */
#endif
#if defined(ECHONL)
	CERI_VSYMI(ECHONL,16);
#else
	CERI_SYM(ECHONL); /* 16|0x10 */
#endif
#if defined(ECHOCTL)
	CERI_VSYMI(ECHOCTL,64);
#else
	CERI_SYM(ECHOCTL); /* 64|0x40 */
#endif
#if defined(ECHOPRT)
	CERI_VSYMI(ECHOPRT,32);
#else
	CERI_SYM(ECHOPRT); /* 32|0x20 */
#endif
#if defined(ECHOKE)
	CERI_VSYMI(ECHOKE,1);
#else
	CERI_SYM(ECHOKE); /* 1 */
#endif
#if defined(NOFLSH)
	CERI_VSYMI(NOFLSH,2147483648);
#else
	CERI_SYM(NOFLSH); /* 2147483648|0x80000000 */
#endif
#if defined(TOSTOP)
	CERI_VSYMI(TOSTOP,4194304);
#else
	CERI_SYM(TOSTOP); /* 4194304|0x400000 */
#endif
#if defined(IEXTEN)
	CERI_VSYMI(IEXTEN,1024);
#else
	CERI_SYM(IEXTEN); /* 1024|0x400 */
#endif
#if defined(VEOF)
	CERI_VSYMI(VEOF,0);
#else
	CERI_SYM(VEOF); /* 0 */
#endif
#if defined(VEOL)
	CERI_VSYMI(VEOL,1);
#else
	CERI_SYM(VEOL); /* 1 */
#endif
#if defined(VEOL2)
	CERI_VSYMI(VEOL2,2);
#else
	CERI_SYM(VEOL2); /* 2 */
#endif
#if defined(VERASE)
	CERI_VSYMI(VERASE,3);
#else
	CERI_SYM(VERASE); /* 3 */
#endif
#if defined(VINTR)
	CERI_VSYMI(VINTR,8);
#else
	CERI_SYM(VINTR); /* 8 */
#endif
#if defined(VKILL)
	CERI_VSYMI(VKILL,5);
#else
	CERI_SYM(VKILL); /* 5 */
#endif
#if defined(VLNEXT)
	CERI_VSYMI(VLNEXT,14);
#else
	CERI_SYM(VLNEXT); /* 14|0xe */
#endif
#if defined(VMIN)
	CERI_VSYMI(VMIN,16);
#else
	CERI_SYM(VMIN); /* 16|0x10 */
#endif
#if defined(VQUIT)
	CERI_VSYMI(VQUIT,9);
#else
	CERI_SYM(VQUIT); /* 9 */
#endif
#if defined(VREPRINT)
	CERI_VSYMI(VREPRINT,6);
#else
	CERI_SYM(VREPRINT); /* 6 */
#endif
#if defined(VSTART)
	CERI_VSYMI(VSTART,12);
#else
	CERI_SYM(VSTART); /* 12|0xc */
#endif
#if defined(VSTOP)
	CERI_VSYMI(VSTOP,13);
#else
	CERI_SYM(VSTOP); /* 13|0xd */
#endif
#if defined(VSUSP)
	CERI_VSYMI(VSUSP,10);
#else
	CERI_SYM(VSUSP); /* 10|0xa */
#endif
#if defined(VTIME)
	CERI_VSYMI(VTIME,17);
#else
	CERI_SYM(VTIME); /* 17|0x11 */
#endif
#if defined(VWERASE)
	CERI_VSYMI(VWERASE,4);
#else
	CERI_SYM(VWERASE); /* 4 */
#endif
#if defined(TCSANOW)
	CERI_VSYMI(TCSANOW,0);
#else
	CERI_SYM(TCSANOW); /* 0 */
#endif
#if defined(TCSADRAIN)
	CERI_VSYMI(TCSADRAIN,1);
#else
	CERI_SYM(TCSADRAIN); /* 1 */
#endif
#if defined(TCSAFLUSH)
	CERI_VSYMI(TCSAFLUSH,2);
#else
	CERI_SYM(TCSAFLUSH); /* 2 */
#endif
#if defined(TCIFLUSH)
	CERI_VSYMI(TCIFLUSH,1);
#else
	CERI_SYM(TCIFLUSH); /* 1 */
#endif
#if defined(TCOFLUSH)
	CERI_VSYMI(TCOFLUSH,2);
#else
	CERI_SYM(TCOFLUSH); /* 2 */
#endif
#if defined(TCIOFLUSH)
	CERI_VSYMI(TCIOFLUSH,3);
#else
	CERI_SYM(TCIOFLUSH); /* 3 */
#endif
#if defined(TCOOFF)
	CERI_VSYMI(TCOOFF,1);
#else
	CERI_SYM(TCOOFF); /* 1 */
#endif
#if defined(TCOON)
	CERI_VSYMI(TCOON,2);
#else
	CERI_SYM(TCOON); /* 2 */
#endif
#if defined(TCIOFF)
	CERI_VSYMI(TCIOFF,3);
#else
	CERI_SYM(TCIOFF); /* 3 */
#endif
#if defined(TCION)
	CERI_VSYMI(TCION,4);
#else
	CERI_SYM(TCION); /* 4 */
#endif
#if defined(B0)
	CERI_VSYMI(B0,0);
#else
	CERI_SYM(B0); /* 0 */
#endif
#if defined(B50)
	CERI_VSYMI(B50,50);
#else
	CERI_SYM(B50); /* 50|0x32 */
#endif
#if defined(B75)
	CERI_VSYMI(B75,75);
#else
	CERI_SYM(B75); /* 75|0x4b */
#endif
#if defined(B110)
	CERI_VSYMI(B110,110);
#else
	CERI_SYM(B110); /* 110|0x6e */
#endif
#if defined(B134)
	CERI_VSYMI(B134,134);
#else
	CERI_SYM(B134); /* 134|0x86 */
#endif
#if defined(B150)
	CERI_VSYMI(B150,150);
#else
	CERI_SYM(B150); /* 150|0x96 */
#endif
#if defined(B200)
	CERI_VSYMI(B200,200);
#else
	CERI_SYM(B200); /* 200|0xc8 */
#endif
#if defined(B300)
	CERI_VSYMI(B300,300);
#else
	CERI_SYM(B300); /* 300|0x12c */
#endif
#if defined(B600)
	CERI_VSYMI(B600,600);
#else
	CERI_SYM(B600); /* 600|0x258 */
#endif
#if defined(B1200)
	CERI_VSYMI(B1200,1200);
#else
	CERI_SYM(B1200); /* 1200|0x4b0 */
#endif
#if defined(B1800)
	CERI_VSYMI(B1800,1800);
#else
	CERI_SYM(B1800); /* 1800|0x708 */
#endif
#if defined(B2400)
	CERI_VSYMI(B2400,2400);
#else
	CERI_SYM(B2400); /* 2400|0x960 */
#endif
#if defined(B4800)
	CERI_VSYMI(B4800,4800);
#else
	CERI_SYM(B4800); /* 4800|0x12c0 */
#endif
#if defined(B9600)
	CERI_VSYMI(B9600,9600);
#else
	CERI_SYM(B9600); /* 9600|0x2580 */
#endif
#if defined(B19200)
	CERI_VSYMI(B19200,19200);
#else
	CERI_SYM(B19200); /* 19200|0x4b00 */
#endif
#if defined(B38400)
	CERI_VSYMI(B38400,38400);
#else
	CERI_SYM(B38400); /* 38400|0x9600 */
#endif
#if defined(B57600)
	CERI_VSYMI(B57600,57600);
#else
	CERI_SYM(B57600); /* 57600|0xe100 */
#endif
#if defined(B115200)
	CERI_VSYMI(B115200,115200);
#else
	CERI_SYM(B115200); /* 115200|0x1c200 */
#endif
#if defined(B230400)
	CERI_VSYMI(B230400,230400);
#else
	CERI_SYM(B230400); /* 230400|0x38400 */
#endif
	
	printf("\n// CUnistd types\n");
#if defined(STDIN_FILENO)
	CERI_VSYMI(STDIN_FILENO,0);
#else
	CERI_SYM(STDIN_FILENO); /* 0 */
#endif
#if defined(STDOUT_FILENO)
	CERI_VSYMI(STDOUT_FILENO,1);
#else
	CERI_SYM(STDOUT_FILENO); /* 1 */
#endif
#if defined(STDERR_FILENO)
	CERI_VSYMI(STDERR_FILENO,2);
#else
	CERI_SYM(STDERR_FILENO); /* 2 */
#endif
#if defined(SEEK_SET)
	CERI_VSYMI(SEEK_SET,0);
#else
	CERI_SYM(SEEK_SET); /* 0 */
#endif
#if defined(SEEK_CUR)
	CERI_VSYMI(SEEK_CUR,1);
#else
	CERI_SYM(SEEK_CUR); /* 1 */
#endif
#if defined(SEEK_END)
	CERI_VSYMI(SEEK_END,2);
#else
	CERI_SYM(SEEK_END); /* 2 */
#endif

	printf("\n");
	if (ceri_errors > 0) printf("[ERRORS: %d]\n", ceri_errors);
	if (ceri_undefineds > 0) printf("[undefined: %d]\n", ceri_undefineds);
	return 0;
}
