// Generated by CSymbolGen (Linux; aarch64; 15.4.1) 2025-05-03T00:22:53

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>
#include <termios.h>
#include <signal.h>
#include <errno.h>
#include <sys/ioctl.h>
#ifdef __linux__
#include <linux/serial.h>
#endif
#ifdef __APPLE__
#include <IOKit/serial/ioss.h>
#endif

/*
 * Example code to print symbols and type sizes.
 *
 * Build:
 * gcc <filename>.c -o <filename>; chmod a+x ./<filename>
 * gcc -I<header-include-path> <filename>.c -o <filename>; chmod a+x ./<filename>
 *
 * Run:
 * ./<filename>
 */

#define CERI_STR(x) #x
#define CERI_SYM(x) ceri_print_symbol(#x,CERI_STR(x))
#define CERI_SYMI(x) ceri_print_symbol_i(#x,CERI_STR(x),x)
#define CERI_VSYMI(x,y) ceri_verify_symbol_i(#x,CERI_STR(x),x,y)
#define CERI_SIZE(x) ceri_print_symbol_i("sizeof("#x")","",sizeof(x))
#define CERI_FSIZE(t,f) ceri_print_symbol_i("sizeof("#t"."#f")","",(sizeof(((t*)0)->f)))

int ceri_errors = 0;
int ceri_undefineds = 0;

void ceri_print_symbol(const char *name, const char *sym) {
	printf("%s = ", name);
	if (strlen(sym) == 0) printf("<defined>");
	else if (strcmp(name, sym) == 0) {
		printf("<undefined?>");
		ceri_undefineds++;
	} else printf("\"%s\"", sym);
	printf("\n");
}

void ceri_print_symbol_i(const char *name, const char *sym, long int isym) {
	printf("%s = ", name);
	if (isym > -10 && isym <  10) printf("%ld", isym);
	else printf("%1$ld|0x%1$lx", isym);
	if (strlen(sym) > 0) printf(" \"%s\"", sym);
	printf("\n");
}

void ceri_verify_symbol_i(const char *name, const char *sym, long int isym, long int iexpect) {
	if (isym < -0xffffffff) isym &= 0xffffffff;
	if (isym != iexpect) {
		printf("[ERROR] 0x%lx != ", iexpect);
		ceri_errors++;
	}
	ceri_print_symbol_i(name, sym, isym);
}

int main(int argc, char *argv[]) {
	printf("\n");

	CERI_SIZE(int);
	CERI_SIZE(long);
	CERI_SIZE(size_t);
	CERI_SIZE(mode_t);
	CERI_SIZE(speed_t);
	CERI_SIZE(nfds_t);
	CERI_SIZE(sigset_t);
	CERI_SIZE(time_t);
	CERI_SIZE(struct timeval);
	CERI_FSIZE(struct timeval,tv_sec);
	CERI_FSIZE(struct timeval,tv_usec);
	CERI_SIZE(struct timespec);
	CERI_FSIZE(struct timespec,tv_sec);
	CERI_FSIZE(struct timespec,tv_nsec);
	
	printf("\n// CErrNo types\n");
#if defined(EPERM)
	CERI_VSYMI(EPERM,1);
#else
	CERI_SYM(EPERM); /* 1 */
#endif
#if defined(ENOENT)
	CERI_VSYMI(ENOENT,2);
#else
	CERI_SYM(ENOENT); /* 2 */
#endif
#if defined(ESRCH)
	CERI_VSYMI(ESRCH,3);
#else
	CERI_SYM(ESRCH); /* 3 */
#endif
#if defined(EINTR)
	CERI_VSYMI(EINTR,4);
#else
	CERI_SYM(EINTR); /* 4 */
#endif
#if defined(EIO)
	CERI_VSYMI(EIO,5);
#else
	CERI_SYM(EIO); /* 5 */
#endif
#if defined(ENXIO)
	CERI_VSYMI(ENXIO,6);
#else
	CERI_SYM(ENXIO); /* 6 */
#endif
#if defined(E2BIG)
	CERI_VSYMI(E2BIG,7);
#else
	CERI_SYM(E2BIG); /* 7 */
#endif
#if defined(ENOEXEC)
	CERI_VSYMI(ENOEXEC,8);
#else
	CERI_SYM(ENOEXEC); /* 8 */
#endif
#if defined(EBADF)
	CERI_VSYMI(EBADF,9);
#else
	CERI_SYM(EBADF); /* 9 */
#endif
#if defined(ECHILD)
	CERI_VSYMI(ECHILD,10);
#else
	CERI_SYM(ECHILD); /* 10|0xa */
#endif
#if defined(EAGAIN)
	CERI_VSYMI(EAGAIN,11);
#else
	CERI_SYM(EAGAIN); /* 11|0xb */
#endif
#if defined(EWOULDBLOCK)
	CERI_VSYMI(EWOULDBLOCK,11);
#else
	CERI_SYM(EWOULDBLOCK); /* 11|0xb */
#endif
#if defined(ENOMEM)
	CERI_VSYMI(ENOMEM,12);
#else
	CERI_SYM(ENOMEM); /* 12|0xc */
#endif
#if defined(EACCES)
	CERI_VSYMI(EACCES,13);
#else
	CERI_SYM(EACCES); /* 13|0xd */
#endif
#if defined(EFAULT)
	CERI_VSYMI(EFAULT,14);
#else
	CERI_SYM(EFAULT); /* 14|0xe */
#endif
#if defined(ENOTBLK)
	CERI_VSYMI(ENOTBLK,15);
#else
	CERI_SYM(ENOTBLK); /* 15|0xf */
#endif
#if defined(EBUSY)
	CERI_VSYMI(EBUSY,16);
#else
	CERI_SYM(EBUSY); /* 16|0x10 */
#endif
#if defined(EEXIST)
	CERI_VSYMI(EEXIST,17);
#else
	CERI_SYM(EEXIST); /* 17|0x11 */
#endif
#if defined(EXDEV)
	CERI_VSYMI(EXDEV,18);
#else
	CERI_SYM(EXDEV); /* 18|0x12 */
#endif
#if defined(ENODEV)
	CERI_VSYMI(ENODEV,19);
#else
	CERI_SYM(ENODEV); /* 19|0x13 */
#endif
#if defined(ENOTDIR)
	CERI_VSYMI(ENOTDIR,20);
#else
	CERI_SYM(ENOTDIR); /* 20|0x14 */
#endif
#if defined(EISDIR)
	CERI_VSYMI(EISDIR,21);
#else
	CERI_SYM(EISDIR); /* 21|0x15 */
#endif
#if defined(EINVAL)
	CERI_VSYMI(EINVAL,22);
#else
	CERI_SYM(EINVAL); /* 22|0x16 */
#endif
#if defined(ENFILE)
	CERI_VSYMI(ENFILE,23);
#else
	CERI_SYM(ENFILE); /* 23|0x17 */
#endif
#if defined(EMFILE)
	CERI_VSYMI(EMFILE,24);
#else
	CERI_SYM(EMFILE); /* 24|0x18 */
#endif
#if defined(ENOTTY)
	CERI_VSYMI(ENOTTY,25);
#else
	CERI_SYM(ENOTTY); /* 25|0x19 */
#endif
#if defined(ETXTBSY)
	CERI_VSYMI(ETXTBSY,26);
#else
	CERI_SYM(ETXTBSY); /* 26|0x1a */
#endif
#if defined(EFBIG)
	CERI_VSYMI(EFBIG,27);
#else
	CERI_SYM(EFBIG); /* 27|0x1b */
#endif
#if defined(ENOSPC)
	CERI_VSYMI(ENOSPC,28);
#else
	CERI_SYM(ENOSPC); /* 28|0x1c */
#endif
#if defined(ESPIPE)
	CERI_VSYMI(ESPIPE,29);
#else
	CERI_SYM(ESPIPE); /* 29|0x1d */
#endif
#if defined(EROFS)
	CERI_VSYMI(EROFS,30);
#else
	CERI_SYM(EROFS); /* 30|0x1e */
#endif
#if defined(EMLINK)
	CERI_VSYMI(EMLINK,31);
#else
	CERI_SYM(EMLINK); /* 31|0x1f */
#endif
#if defined(EPIPE)
	CERI_VSYMI(EPIPE,32);
#else
	CERI_SYM(EPIPE); /* 32|0x20 */
#endif
#if defined(EDOM)
	CERI_VSYMI(EDOM,33);
#else
	CERI_SYM(EDOM); /* 33|0x21 */
#endif
#if defined(ERANGE)
	CERI_VSYMI(ERANGE,34);
#else
	CERI_SYM(ERANGE); /* 34|0x22 */
#endif
#if defined(EDEADLK)
	CERI_VSYMI(EDEADLK,35);
#else
	CERI_SYM(EDEADLK); /* 35|0x23 */
#endif
#if defined(ENAMETOOLONG)
	CERI_VSYMI(ENAMETOOLONG,36);
#else
	CERI_SYM(ENAMETOOLONG); /* 36|0x24 */
#endif
#if defined(ENOLCK)
	CERI_VSYMI(ENOLCK,37);
#else
	CERI_SYM(ENOLCK); /* 37|0x25 */
#endif
#if defined(ENOSYS)
	CERI_VSYMI(ENOSYS,38);
#else
	CERI_SYM(ENOSYS); /* 38|0x26 */
#endif
#if defined(ENOTEMPTY)
	CERI_VSYMI(ENOTEMPTY,39);
#else
	CERI_SYM(ENOTEMPTY); /* 39|0x27 */
#endif
#if defined(ELOOP)
	CERI_VSYMI(ELOOP,40);
#else
	CERI_SYM(ELOOP); /* 40|0x28 */
#endif
#if defined(ENOMSG)
	CERI_VSYMI(ENOMSG,42);
#else
	CERI_SYM(ENOMSG); /* 42|0x2a */
#endif
#if defined(EIDRM)
	CERI_VSYMI(EIDRM,43);
#else
	CERI_SYM(EIDRM); /* 43|0x2b */
#endif
#if defined(ECHRNG)
	CERI_VSYMI(ECHRNG,44);
#else
	CERI_SYM(ECHRNG); /* 44|0x2c */
#endif
#if defined(EL2NSYNC)
	CERI_VSYMI(EL2NSYNC,45);
#else
	CERI_SYM(EL2NSYNC); /* 45|0x2d */
#endif
#if defined(EL3HLT)
	CERI_VSYMI(EL3HLT,46);
#else
	CERI_SYM(EL3HLT); /* 46|0x2e */
#endif
#if defined(EL3RST)
	CERI_VSYMI(EL3RST,47);
#else
	CERI_SYM(EL3RST); /* 47|0x2f */
#endif
#if defined(ELNRNG)
	CERI_VSYMI(ELNRNG,48);
#else
	CERI_SYM(ELNRNG); /* 48|0x30 */
#endif
#if defined(EUNATCH)
	CERI_VSYMI(EUNATCH,49);
#else
	CERI_SYM(EUNATCH); /* 49|0x31 */
#endif
#if defined(ENOCSI)
	CERI_VSYMI(ENOCSI,50);
#else
	CERI_SYM(ENOCSI); /* 50|0x32 */
#endif
#if defined(EL2HLT)
	CERI_VSYMI(EL2HLT,51);
#else
	CERI_SYM(EL2HLT); /* 51|0x33 */
#endif
#if defined(EBADE)
	CERI_VSYMI(EBADE,52);
#else
	CERI_SYM(EBADE); /* 52|0x34 */
#endif
#if defined(EBADR)
	CERI_VSYMI(EBADR,53);
#else
	CERI_SYM(EBADR); /* 53|0x35 */
#endif
#if defined(EXFULL)
	CERI_VSYMI(EXFULL,54);
#else
	CERI_SYM(EXFULL); /* 54|0x36 */
#endif
#if defined(ENOANO)
	CERI_VSYMI(ENOANO,55);
#else
	CERI_SYM(ENOANO); /* 55|0x37 */
#endif
#if defined(EBADRQC)
	CERI_VSYMI(EBADRQC,56);
#else
	CERI_SYM(EBADRQC); /* 56|0x38 */
#endif
#if defined(EBADSLT)
	CERI_VSYMI(EBADSLT,57);
#else
	CERI_SYM(EBADSLT); /* 57|0x39 */
#endif
#if defined(EBFONT)
	CERI_VSYMI(EBFONT,59);
#else
	CERI_SYM(EBFONT); /* 59|0x3b */
#endif
#if defined(ENOSTR)
	CERI_VSYMI(ENOSTR,60);
#else
	CERI_SYM(ENOSTR); /* 60|0x3c */
#endif
#if defined(ENODATA)
	CERI_VSYMI(ENODATA,61);
#else
	CERI_SYM(ENODATA); /* 61|0x3d */
#endif
#if defined(ETIME)
	CERI_VSYMI(ETIME,62);
#else
	CERI_SYM(ETIME); /* 62|0x3e */
#endif
#if defined(ENOSR)
	CERI_VSYMI(ENOSR,63);
#else
	CERI_SYM(ENOSR); /* 63|0x3f */
#endif
#if defined(ENONET)
	CERI_VSYMI(ENONET,64);
#else
	CERI_SYM(ENONET); /* 64|0x40 */
#endif
#if defined(ENOPKG)
	CERI_VSYMI(ENOPKG,65);
#else
	CERI_SYM(ENOPKG); /* 65|0x41 */
#endif
#if defined(EREMOTE)
	CERI_VSYMI(EREMOTE,66);
#else
	CERI_SYM(EREMOTE); /* 66|0x42 */
#endif
#if defined(ENOLINK)
	CERI_VSYMI(ENOLINK,67);
#else
	CERI_SYM(ENOLINK); /* 67|0x43 */
#endif
#if defined(EADV)
	CERI_VSYMI(EADV,68);
#else
	CERI_SYM(EADV); /* 68|0x44 */
#endif
#if defined(ESRMNT)
	CERI_VSYMI(ESRMNT,69);
#else
	CERI_SYM(ESRMNT); /* 69|0x45 */
#endif
#if defined(ECOMM)
	CERI_VSYMI(ECOMM,70);
#else
	CERI_SYM(ECOMM); /* 70|0x46 */
#endif
#if defined(EPROTO)
	CERI_VSYMI(EPROTO,71);
#else
	CERI_SYM(EPROTO); /* 71|0x47 */
#endif
#if defined(EMULTIHOP)
	CERI_VSYMI(EMULTIHOP,72);
#else
	CERI_SYM(EMULTIHOP); /* 72|0x48 */
#endif
#if defined(EDOTDOT)
	CERI_VSYMI(EDOTDOT,73);
#else
	CERI_SYM(EDOTDOT); /* 73|0x49 */
#endif
#if defined(EBADMSG)
	CERI_VSYMI(EBADMSG,74);
#else
	CERI_SYM(EBADMSG); /* 74|0x4a */
#endif
#if defined(EOVERFLOW)
	CERI_VSYMI(EOVERFLOW,75);
#else
	CERI_SYM(EOVERFLOW); /* 75|0x4b */
#endif
#if defined(ENOTUNIQ)
	CERI_VSYMI(ENOTUNIQ,76);
#else
	CERI_SYM(ENOTUNIQ); /* 76|0x4c */
#endif
#if defined(EBADFD)
	CERI_VSYMI(EBADFD,77);
#else
	CERI_SYM(EBADFD); /* 77|0x4d */
#endif
#if defined(EREMCHG)
	CERI_VSYMI(EREMCHG,78);
#else
	CERI_SYM(EREMCHG); /* 78|0x4e */
#endif
#if defined(ELIBACC)
	CERI_VSYMI(ELIBACC,79);
#else
	CERI_SYM(ELIBACC); /* 79|0x4f */
#endif
#if defined(ELIBBAD)
	CERI_VSYMI(ELIBBAD,80);
#else
	CERI_SYM(ELIBBAD); /* 80|0x50 */
#endif
#if defined(ELIBSCN)
	CERI_VSYMI(ELIBSCN,81);
#else
	CERI_SYM(ELIBSCN); /* 81|0x51 */
#endif
#if defined(ELIBMAX)
	CERI_VSYMI(ELIBMAX,82);
#else
	CERI_SYM(ELIBMAX); /* 82|0x52 */
#endif
#if defined(ELIBEXEC)
	CERI_VSYMI(ELIBEXEC,83);
#else
	CERI_SYM(ELIBEXEC); /* 83|0x53 */
#endif
#if defined(EILSEQ)
	CERI_VSYMI(EILSEQ,84);
#else
	CERI_SYM(EILSEQ); /* 84|0x54 */
#endif
#if defined(ERESTART)
	CERI_VSYMI(ERESTART,85);
#else
	CERI_SYM(ERESTART); /* 85|0x55 */
#endif
#if defined(ESTRPIPE)
	CERI_VSYMI(ESTRPIPE,86);
#else
	CERI_SYM(ESTRPIPE); /* 86|0x56 */
#endif
#if defined(EUSERS)
	CERI_VSYMI(EUSERS,87);
#else
	CERI_SYM(EUSERS); /* 87|0x57 */
#endif
#if defined(ENOTSOCK)
	CERI_VSYMI(ENOTSOCK,88);
#else
	CERI_SYM(ENOTSOCK); /* 88|0x58 */
#endif
#if defined(EDESTADDRREQ)
	CERI_VSYMI(EDESTADDRREQ,89);
#else
	CERI_SYM(EDESTADDRREQ); /* 89|0x59 */
#endif
#if defined(EMSGSIZE)
	CERI_VSYMI(EMSGSIZE,90);
#else
	CERI_SYM(EMSGSIZE); /* 90|0x5a */
#endif
#if defined(EPROTOTYPE)
	CERI_VSYMI(EPROTOTYPE,91);
#else
	CERI_SYM(EPROTOTYPE); /* 91|0x5b */
#endif
#if defined(ENOPROTOOPT)
	CERI_VSYMI(ENOPROTOOPT,92);
#else
	CERI_SYM(ENOPROTOOPT); /* 92|0x5c */
#endif
#if defined(EPROTONOSUPPORT)
	CERI_VSYMI(EPROTONOSUPPORT,93);
#else
	CERI_SYM(EPROTONOSUPPORT); /* 93|0x5d */
#endif
#if defined(ESOCKTNOSUPPORT)
	CERI_VSYMI(ESOCKTNOSUPPORT,94);
#else
	CERI_SYM(ESOCKTNOSUPPORT); /* 94|0x5e */
#endif
#if defined(EOPNOTSUPP)
	CERI_VSYMI(EOPNOTSUPP,95);
#else
	CERI_SYM(EOPNOTSUPP); /* 95|0x5f */
#endif
#if defined(ENOTSUP)
	CERI_VSYMI(ENOTSUP,95);
#else
	CERI_SYM(ENOTSUP); /* 95|0x5f */
#endif
#if defined(EPFNOSUPPORT)
	CERI_VSYMI(EPFNOSUPPORT,96);
#else
	CERI_SYM(EPFNOSUPPORT); /* 96|0x60 */
#endif
#if defined(EAFNOSUPPORT)
	CERI_VSYMI(EAFNOSUPPORT,97);
#else
	CERI_SYM(EAFNOSUPPORT); /* 97|0x61 */
#endif
#if defined(EADDRINUSE)
	CERI_VSYMI(EADDRINUSE,98);
#else
	CERI_SYM(EADDRINUSE); /* 98|0x62 */
#endif
#if defined(EADDRNOTAVAIL)
	CERI_VSYMI(EADDRNOTAVAIL,99);
#else
	CERI_SYM(EADDRNOTAVAIL); /* 99|0x63 */
#endif
#if defined(ENETDOWN)
	CERI_VSYMI(ENETDOWN,100);
#else
	CERI_SYM(ENETDOWN); /* 100|0x64 */
#endif
#if defined(ENETUNREACH)
	CERI_VSYMI(ENETUNREACH,101);
#else
	CERI_SYM(ENETUNREACH); /* 101|0x65 */
#endif
#if defined(ENETRESET)
	CERI_VSYMI(ENETRESET,102);
#else
	CERI_SYM(ENETRESET); /* 102|0x66 */
#endif
#if defined(ECONNABORTED)
	CERI_VSYMI(ECONNABORTED,103);
#else
	CERI_SYM(ECONNABORTED); /* 103|0x67 */
#endif
#if defined(ECONNRESET)
	CERI_VSYMI(ECONNRESET,104);
#else
	CERI_SYM(ECONNRESET); /* 104|0x68 */
#endif
#if defined(ENOBUFS)
	CERI_VSYMI(ENOBUFS,105);
#else
	CERI_SYM(ENOBUFS); /* 105|0x69 */
#endif
#if defined(EISCONN)
	CERI_VSYMI(EISCONN,106);
#else
	CERI_SYM(EISCONN); /* 106|0x6a */
#endif
#if defined(ENOTCONN)
	CERI_VSYMI(ENOTCONN,107);
#else
	CERI_SYM(ENOTCONN); /* 107|0x6b */
#endif
#if defined(ESHUTDOWN)
	CERI_VSYMI(ESHUTDOWN,108);
#else
	CERI_SYM(ESHUTDOWN); /* 108|0x6c */
#endif
#if defined(ETOOMANYREFS)
	CERI_VSYMI(ETOOMANYREFS,109);
#else
	CERI_SYM(ETOOMANYREFS); /* 109|0x6d */
#endif
#if defined(ETIMEDOUT)
	CERI_VSYMI(ETIMEDOUT,110);
#else
	CERI_SYM(ETIMEDOUT); /* 110|0x6e */
#endif
#if defined(ECONNREFUSED)
	CERI_VSYMI(ECONNREFUSED,111);
#else
	CERI_SYM(ECONNREFUSED); /* 111|0x6f */
#endif
#if defined(EHOSTDOWN)
	CERI_VSYMI(EHOSTDOWN,112);
#else
	CERI_SYM(EHOSTDOWN); /* 112|0x70 */
#endif
#if defined(EHOSTUNREACH)
	CERI_VSYMI(EHOSTUNREACH,113);
#else
	CERI_SYM(EHOSTUNREACH); /* 113|0x71 */
#endif
#if defined(EALREADY)
	CERI_VSYMI(EALREADY,114);
#else
	CERI_SYM(EALREADY); /* 114|0x72 */
#endif
#if defined(EINPROGRESS)
	CERI_VSYMI(EINPROGRESS,115);
#else
	CERI_SYM(EINPROGRESS); /* 115|0x73 */
#endif
#if defined(ESTALE)
	CERI_VSYMI(ESTALE,116);
#else
	CERI_SYM(ESTALE); /* 116|0x74 */
#endif
#if defined(EUCLEAN)
	CERI_VSYMI(EUCLEAN,117);
#else
	CERI_SYM(EUCLEAN); /* 117|0x75 */
#endif
#if defined(ENOTNAM)
	CERI_VSYMI(ENOTNAM,118);
#else
	CERI_SYM(ENOTNAM); /* 118|0x76 */
#endif
#if defined(ENAVAIL)
	CERI_VSYMI(ENAVAIL,119);
#else
	CERI_SYM(ENAVAIL); /* 119|0x77 */
#endif
#if defined(EISNAM)
	CERI_VSYMI(EISNAM,120);
#else
	CERI_SYM(EISNAM); /* 120|0x78 */
#endif
#if defined(EREMOTEIO)
	CERI_VSYMI(EREMOTEIO,121);
#else
	CERI_SYM(EREMOTEIO); /* 121|0x79 */
#endif
#if defined(EDQUOT)
	CERI_VSYMI(EDQUOT,122);
#else
	CERI_SYM(EDQUOT); /* 122|0x7a */
#endif
#if defined(ENOMEDIUM)
	CERI_VSYMI(ENOMEDIUM,123);
#else
	CERI_SYM(ENOMEDIUM); /* 123|0x7b */
#endif
#if defined(EMEDIUMTYPE)
	CERI_VSYMI(EMEDIUMTYPE,124);
#else
	CERI_SYM(EMEDIUMTYPE); /* 124|0x7c */
#endif
#if defined(ECANCELED)
	CERI_VSYMI(ECANCELED,125);
#else
	CERI_SYM(ECANCELED); /* 125|0x7d */
#endif
#if defined(ENOKEY)
	CERI_VSYMI(ENOKEY,126);
#else
	CERI_SYM(ENOKEY); /* 126|0x7e */
#endif
#if defined(EKEYEXPIRED)
	CERI_VSYMI(EKEYEXPIRED,127);
#else
	CERI_SYM(EKEYEXPIRED); /* 127|0x7f */
#endif
#if defined(EKEYREVOKED)
	CERI_VSYMI(EKEYREVOKED,128);
#else
	CERI_SYM(EKEYREVOKED); /* 128|0x80 */
#endif
#if defined(EKEYREJECTED)
	CERI_VSYMI(EKEYREJECTED,129);
#else
	CERI_SYM(EKEYREJECTED); /* 129|0x81 */
#endif
#if defined(EOWNERDEAD)
	CERI_VSYMI(EOWNERDEAD,130);
#else
	CERI_SYM(EOWNERDEAD); /* 130|0x82 */
#endif
#if defined(ENOTRECOVERABLE)
	CERI_VSYMI(ENOTRECOVERABLE,131);
#else
	CERI_SYM(ENOTRECOVERABLE); /* 131|0x83 */
#endif
#if defined(ERFKILL)
	CERI_VSYMI(ERFKILL,132);
#else
	CERI_SYM(ERFKILL); /* 132|0x84 */
#endif
#if defined(EHWPOISON)
	CERI_VSYMI(EHWPOISON,133);
#else
	CERI_SYM(EHWPOISON); /* 133|0x85 */
#endif
	
	printf("\n// CFcntl types\n");
#if defined(O_RDONLY)
	CERI_VSYMI(O_RDONLY,0);
#else
	CERI_SYM(O_RDONLY); /* 0 */
#endif
#if defined(O_WRONLY)
	CERI_VSYMI(O_WRONLY,1);
#else
	CERI_SYM(O_WRONLY); /* 1 */
#endif
#if defined(O_RDWR)
	CERI_VSYMI(O_RDWR,2);
#else
	CERI_SYM(O_RDWR); /* 2 */
#endif
#if defined(O_ACCMODE)
	CERI_VSYMI(O_ACCMODE,3);
#else
	CERI_SYM(O_ACCMODE); /* 3 */
#endif
#if defined(O_CREAT)
	CERI_VSYMI(O_CREAT,64);
#else
	CERI_SYM(O_CREAT); /* 64|0x40 */
#endif
#if defined(O_EXCL)
	CERI_VSYMI(O_EXCL,128);
#else
	CERI_SYM(O_EXCL); /* 128|0x80 */
#endif
#if defined(O_NOCTTY)
	CERI_VSYMI(O_NOCTTY,256);
#else
	CERI_SYM(O_NOCTTY); /* 256|0x100 */
#endif
#if defined(O_TRUNC)
	CERI_VSYMI(O_TRUNC,512);
#else
	CERI_SYM(O_TRUNC); /* 512|0x200 */
#endif
#if defined(O_APPEND)
	CERI_VSYMI(O_APPEND,1024);
#else
	CERI_SYM(O_APPEND); /* 1024|0x400 */
#endif
#if defined(O_NONBLOCK)
	CERI_VSYMI(O_NONBLOCK,2048);
#else
	CERI_SYM(O_NONBLOCK); /* 2048|0x800 */
#endif
#if defined(O_DSYNC)
	CERI_VSYMI(O_DSYNC,4096);
#else
	CERI_SYM(O_DSYNC); /* 4096|0x1000 */
#endif
#if defined(O_ASYNC)
	CERI_VSYMI(O_ASYNC,8192);
#else
	CERI_SYM(O_ASYNC); /* 8192|0x2000 */
#endif
#if defined(O_DIRECTORY)
	CERI_VSYMI(O_DIRECTORY,16384);
#else
	CERI_SYM(O_DIRECTORY); /* 16384|0x4000 */
#endif
#if defined(O_NOFOLLOW)
	CERI_VSYMI(O_NOFOLLOW,32768);
#else
	CERI_SYM(O_NOFOLLOW); /* 32768|0x8000 */
#endif
#if defined(O_CLOEXEC)
	CERI_VSYMI(O_CLOEXEC,524288);
#else
	CERI_SYM(O_CLOEXEC); /* 524288|0x80000 */
#endif
#if defined(O_SYNC)
	CERI_VSYMI(O_SYNC,1052672);
#else
	CERI_SYM(O_SYNC); /* 1052672|0x101000 */
#endif
	
	printf("\n// CIoctl types\n");
#if defined(_IOC_SIZEBITS)
	CERI_VSYMI(_IOC_SIZEBITS,14);
#else
	CERI_SYM(_IOC_SIZEBITS); /* 14|0xe */
#endif
#if defined(_IOC_SIZEMASK)
	CERI_VSYMI(_IOC_SIZEMASK,16383);
#else
	CERI_SYM(_IOC_SIZEMASK); /* 16383|0x3fff */
#endif
#if defined(IOC_OUT)
	CERI_VSYMI(IOC_OUT,2147483648);
#else
	CERI_SYM(IOC_OUT); /* 2147483648|0x80000000 */
#endif
#if defined(IOC_IN)
	CERI_VSYMI(IOC_IN,1073741824);
#else
	CERI_SYM(IOC_IN); /* 1073741824|0x40000000 */
#endif
#if defined(TIOCSBRK)
	CERI_VSYMI(TIOCSBRK,21543);
#else
	CERI_SYM(TIOCSBRK); /* 21543|0x5427 */
#endif
#if defined(TIOCCBRK)
	CERI_VSYMI(TIOCCBRK,21544);
#else
	CERI_SYM(TIOCCBRK); /* 21544|0x5428 */
#endif
#if defined(FIONREAD)
	CERI_VSYMI(FIONREAD,21531);
#else
	CERI_SYM(FIONREAD); /* 21531|0x541b */
#endif
#if defined(TIOCEXCL)
	CERI_VSYMI(TIOCEXCL,21516);
#else
	CERI_SYM(TIOCEXCL); /* 21516|0x540c */
#endif
#if defined(TIOCOUTQ)
	CERI_VSYMI(TIOCOUTQ,21521);
#else
	CERI_SYM(TIOCOUTQ); /* 21521|0x5411 */
#endif
#if defined(TIOCMGET)
	CERI_VSYMI(TIOCMGET,21525);
#else
	CERI_SYM(TIOCMGET); /* 21525|0x5415 */
#endif
#if defined(TIOCMBIC)
	CERI_VSYMI(TIOCMBIC,21527);
#else
	CERI_SYM(TIOCMBIC); /* 21527|0x5417 */
#endif
#if defined(TIOCMBIS)
	CERI_VSYMI(TIOCMBIS,21526);
#else
	CERI_SYM(TIOCMBIS); /* 21526|0x5416 */
#endif
#if defined(TIOCMSET)
	CERI_VSYMI(TIOCMSET,21528);
#else
	CERI_SYM(TIOCMSET); /* 21528|0x5418 */
#endif
#if defined(TIOCM_LE)
	CERI_VSYMI(TIOCM_LE,1);
#else
	CERI_SYM(TIOCM_LE); /* 1 */
#endif
#if defined(TIOCM_DTR)
	CERI_VSYMI(TIOCM_DTR,2);
#else
	CERI_SYM(TIOCM_DTR); /* 2 */
#endif
#if defined(TIOCM_RTS)
	CERI_VSYMI(TIOCM_RTS,4);
#else
	CERI_SYM(TIOCM_RTS); /* 4 */
#endif
#if defined(TIOCM_CTS)
	CERI_VSYMI(TIOCM_CTS,32);
#else
	CERI_SYM(TIOCM_CTS); /* 32|0x20 */
#endif
#if defined(TIOCM_CD)
	CERI_VSYMI(TIOCM_CD,64);
#else
	CERI_SYM(TIOCM_CD); /* 64|0x40 */
#endif
#if defined(TIOCM_RI)
	CERI_VSYMI(TIOCM_RI,128);
#else
	CERI_SYM(TIOCM_RI); /* 128|0x80 */
#endif
#if defined(TIOCM_DSR)
	CERI_VSYMI(TIOCM_DSR,256);
#else
	CERI_SYM(TIOCM_DSR); /* 256|0x100 */
#endif
	
	printf("\n// CIoctl.Linux types\n");
#if defined(ASYNC_SPD_HI)
	CERI_VSYMI(ASYNC_SPD_HI,16);
#else
	CERI_SYM(ASYNC_SPD_HI); /* 16|0x10 */
#endif
#if defined(ASYNC_SPD_VHI)
	CERI_VSYMI(ASYNC_SPD_VHI,32);
#else
	CERI_SYM(ASYNC_SPD_VHI); /* 32|0x20 */
#endif
#if defined(ASYNC_SPD_SHI)
	CERI_VSYMI(ASYNC_SPD_SHI,4096);
#else
	CERI_SYM(ASYNC_SPD_SHI); /* 4096|0x1000 */
#endif
#if defined(ASYNC_SPD_CUST)
	CERI_VSYMI(ASYNC_SPD_CUST,48);
#else
	CERI_SYM(ASYNC_SPD_CUST); /* 48|0x30 */
#endif
#if defined(ASYNC_SPD_MASK)
	CERI_VSYMI(ASYNC_SPD_MASK,4144);
#else
	CERI_SYM(ASYNC_SPD_MASK); /* 4144|0x1030 */
#endif
#if defined(TIOCGSERIAL)
	CERI_VSYMI(TIOCGSERIAL,21534);
#else
	CERI_SYM(TIOCGSERIAL); /* 21534|0x541e */
#endif
#if defined(TIOCSSERIAL)
	CERI_VSYMI(TIOCSSERIAL,21535);
#else
	CERI_SYM(TIOCSSERIAL); /* 21535|0x541f */
#endif
	
	printf("\n// CPoll types\n");
#if defined(POLLIN)
	CERI_VSYMI(POLLIN,1);
#else
	CERI_SYM(POLLIN); /* 1 */
#endif
#if defined(POLLPRI)
	CERI_VSYMI(POLLPRI,2);
#else
	CERI_SYM(POLLPRI); /* 2 */
#endif
#if defined(POLLOUT)
	CERI_VSYMI(POLLOUT,4);
#else
	CERI_SYM(POLLOUT); /* 4 */
#endif
#if defined(POLLERR)
	CERI_VSYMI(POLLERR,8);
#else
	CERI_SYM(POLLERR); /* 8 */
#endif
#if defined(POLLHUP)
	CERI_VSYMI(POLLHUP,16);
#else
	CERI_SYM(POLLHUP); /* 16|0x10 */
#endif
#if defined(POLLNVAL)
	CERI_VSYMI(POLLNVAL,32);
#else
	CERI_SYM(POLLNVAL); /* 32|0x20 */
#endif
	
	printf("\n// CSignal types\n");
#if defined(SIGHUP)
	CERI_VSYMI(SIGHUP,1);
#else
	CERI_SYM(SIGHUP); /* 1 */
#endif
#if defined(SIGINT)
	CERI_VSYMI(SIGINT,2);
#else
	CERI_SYM(SIGINT); /* 2 */
#endif
#if defined(SIGQUIT)
	CERI_VSYMI(SIGQUIT,3);
#else
	CERI_SYM(SIGQUIT); /* 3 */
#endif
#if defined(SIGILL)
	CERI_VSYMI(SIGILL,4);
#else
	CERI_SYM(SIGILL); /* 4 */
#endif
#if defined(SIGTRAP)
	CERI_VSYMI(SIGTRAP,5);
#else
	CERI_SYM(SIGTRAP); /* 5 */
#endif
#if defined(SIGABRT)
	CERI_VSYMI(SIGABRT,6);
#else
	CERI_SYM(SIGABRT); /* 6 */
#endif
#if defined(SIGIOT)
	CERI_VSYMI(SIGIOT,6);
#else
	CERI_SYM(SIGIOT); /* 6 */
#endif
#if defined(SIGBUS)
	CERI_VSYMI(SIGBUS,7);
#else
	CERI_SYM(SIGBUS); /* 7 */
#endif
#if defined(SIGFPE)
	CERI_VSYMI(SIGFPE,8);
#else
	CERI_SYM(SIGFPE); /* 8 */
#endif
#if defined(SIGKILL)
	CERI_VSYMI(SIGKILL,9);
#else
	CERI_SYM(SIGKILL); /* 9 */
#endif
#if defined(SIGUSR1)
	CERI_VSYMI(SIGUSR1,10);
#else
	CERI_SYM(SIGUSR1); /* 10|0xa */
#endif
#if defined(SIGSEGV)
	CERI_VSYMI(SIGSEGV,11);
#else
	CERI_SYM(SIGSEGV); /* 11|0xb */
#endif
#if defined(SIGUSR2)
	CERI_VSYMI(SIGUSR2,12);
#else
	CERI_SYM(SIGUSR2); /* 12|0xc */
#endif
#if defined(SIGPIPE)
	CERI_VSYMI(SIGPIPE,13);
#else
	CERI_SYM(SIGPIPE); /* 13|0xd */
#endif
#if defined(SIGALRM)
	CERI_VSYMI(SIGALRM,14);
#else
	CERI_SYM(SIGALRM); /* 14|0xe */
#endif
#if defined(SIGTERM)
	CERI_VSYMI(SIGTERM,15);
#else
	CERI_SYM(SIGTERM); /* 15|0xf */
#endif
#if defined(SIGCHLD)
	CERI_VSYMI(SIGCHLD,17);
#else
	CERI_SYM(SIGCHLD); /* 17|0x11 */
#endif
#if defined(SIGCONT)
	CERI_VSYMI(SIGCONT,18);
#else
	CERI_SYM(SIGCONT); /* 18|0x12 */
#endif
#if defined(SIGSTOP)
	CERI_VSYMI(SIGSTOP,19);
#else
	CERI_SYM(SIGSTOP); /* 19|0x13 */
#endif
#if defined(SIGTSTP)
	CERI_VSYMI(SIGTSTP,20);
#else
	CERI_SYM(SIGTSTP); /* 20|0x14 */
#endif
#if defined(SIGTTIN)
	CERI_VSYMI(SIGTTIN,21);
#else
	CERI_SYM(SIGTTIN); /* 21|0x15 */
#endif
#if defined(SIGTTOU)
	CERI_VSYMI(SIGTTOU,22);
#else
	CERI_SYM(SIGTTOU); /* 22|0x16 */
#endif
#if defined(SIGURG)
	CERI_VSYMI(SIGURG,23);
#else
	CERI_SYM(SIGURG); /* 23|0x17 */
#endif
#if defined(SIGXCPU)
	CERI_VSYMI(SIGXCPU,24);
#else
	CERI_SYM(SIGXCPU); /* 24|0x18 */
#endif
#if defined(SIGXFSZ)
	CERI_VSYMI(SIGXFSZ,25);
#else
	CERI_SYM(SIGXFSZ); /* 25|0x19 */
#endif
#if defined(SIGVTALRM)
	CERI_VSYMI(SIGVTALRM,26);
#else
	CERI_SYM(SIGVTALRM); /* 26|0x1a */
#endif
#if defined(SIGPROF)
	CERI_VSYMI(SIGPROF,27);
#else
	CERI_SYM(SIGPROF); /* 27|0x1b */
#endif
#if defined(SIGWINCH)
	CERI_VSYMI(SIGWINCH,28);
#else
	CERI_SYM(SIGWINCH); /* 28|0x1c */
#endif
#if defined(SIGIO)
	CERI_VSYMI(SIGIO,29);
#else
	CERI_SYM(SIGIO); /* 29|0x1d */
#endif
#if defined(SIGPOLL)
	CERI_VSYMI(SIGPOLL,29);
#else
	CERI_SYM(SIGPOLL); /* 29|0x1d */
#endif
#if defined(SIGSYS)
	CERI_VSYMI(SIGSYS,31);
#else
	CERI_SYM(SIGSYS); /* 31|0x1f */
#endif
	CERI_SYM(SIG_DFL); /* 0 */
	CERI_SYM(SIG_IGN); /* 1 */
	CERI_SYM(SIG_ERR); /* -1 */
	
	printf("\n// CTermios types\n");
#if defined(IGNBRK)
	CERI_VSYMI(IGNBRK,1);
#else
	CERI_SYM(IGNBRK); /* 1 */
#endif
#if defined(BRKINT)
	CERI_VSYMI(BRKINT,2);
#else
	CERI_SYM(BRKINT); /* 2 */
#endif
#if defined(IGNPAR)
	CERI_VSYMI(IGNPAR,4);
#else
	CERI_SYM(IGNPAR); /* 4 */
#endif
#if defined(PARMRK)
	CERI_VSYMI(PARMRK,8);
#else
	CERI_SYM(PARMRK); /* 8 */
#endif
#if defined(INPCK)
	CERI_VSYMI(INPCK,16);
#else
	CERI_SYM(INPCK); /* 16|0x10 */
#endif
#if defined(ISTRIP)
	CERI_VSYMI(ISTRIP,32);
#else
	CERI_SYM(ISTRIP); /* 32|0x20 */
#endif
#if defined(INLCR)
	CERI_VSYMI(INLCR,64);
#else
	CERI_SYM(INLCR); /* 64|0x40 */
#endif
#if defined(IGNCR)
	CERI_VSYMI(IGNCR,128);
#else
	CERI_SYM(IGNCR); /* 128|0x80 */
#endif
#if defined(ICRNL)
	CERI_VSYMI(ICRNL,256);
#else
	CERI_SYM(ICRNL); /* 256|0x100 */
#endif
#if defined(IXON)
	CERI_VSYMI(IXON,1024);
#else
	CERI_SYM(IXON); /* 1024|0x400 */
#endif
#if defined(IXANY)
	CERI_VSYMI(IXANY,2048);
#else
	CERI_SYM(IXANY); /* 2048|0x800 */
#endif
#if defined(IXOFF)
	CERI_VSYMI(IXOFF,4096);
#else
	CERI_SYM(IXOFF); /* 4096|0x1000 */
#endif
#if defined(IMAXBEL)
	CERI_VSYMI(IMAXBEL,8192);
#else
	CERI_SYM(IMAXBEL); /* 8192|0x2000 */
#endif
#if defined(IUTF8)
	CERI_VSYMI(IUTF8,16384);
#else
	CERI_SYM(IUTF8); /* 16384|0x4000 */
#endif
#if defined(OPOST)
	CERI_VSYMI(OPOST,1);
#else
	CERI_SYM(OPOST); /* 1 */
#endif
#if defined(ONLCR)
	CERI_VSYMI(ONLCR,4);
#else
	CERI_SYM(ONLCR); /* 4 */
#endif
#if defined(OCRNL)
	CERI_VSYMI(OCRNL,8);
#else
	CERI_SYM(OCRNL); /* 8 */
#endif
#if defined(ONOCR)
	CERI_VSYMI(ONOCR,16);
#else
	CERI_SYM(ONOCR); /* 16|0x10 */
#endif
#if defined(ONLRET)
	CERI_VSYMI(ONLRET,32);
#else
	CERI_SYM(ONLRET); /* 32|0x20 */
#endif
#if defined(OFILL)
	CERI_VSYMI(OFILL,64);
#else
	CERI_SYM(OFILL); /* 64|0x40 */
#endif
#if defined(OFDEL)
	CERI_VSYMI(OFDEL,128);
#else
	CERI_SYM(OFDEL); /* 128|0x80 */
#endif
#if defined(CSIZE)
	CERI_VSYMI(CSIZE,48);
#else
	CERI_SYM(CSIZE); /* 48|0x30 */
#endif
#if defined(CSTOPB)
	CERI_VSYMI(CSTOPB,64);
#else
	CERI_SYM(CSTOPB); /* 64|0x40 */
#endif
#if defined(CREAD)
	CERI_VSYMI(CREAD,128);
#else
	CERI_SYM(CREAD); /* 128|0x80 */
#endif
#if defined(PARENB)
	CERI_VSYMI(PARENB,256);
#else
	CERI_SYM(PARENB); /* 256|0x100 */
#endif
#if defined(PARODD)
	CERI_VSYMI(PARODD,512);
#else
	CERI_SYM(PARODD); /* 512|0x200 */
#endif
#if defined(HUPCL)
	CERI_VSYMI(HUPCL,1024);
#else
	CERI_SYM(HUPCL); /* 1024|0x400 */
#endif
#if defined(CLOCAL)
	CERI_VSYMI(CLOCAL,2048);
#else
	CERI_SYM(CLOCAL); /* 2048|0x800 */
#endif
#if defined(CMSPAR)
	CERI_VSYMI(CMSPAR,1073741824);
#else
	CERI_SYM(CMSPAR); /* 1073741824|0x40000000 */
#endif
#if defined(CRTSCTS)
	CERI_VSYMI(CRTSCTS,2147483648);
#else
	CERI_SYM(CRTSCTS); /* 2147483648|0x80000000 */
#endif
#if defined(CS5)
	CERI_VSYMI(CS5,0);
#else
	CERI_SYM(CS5); /* 0 */
#endif
#if defined(CS6)
	CERI_VSYMI(CS6,16);
#else
	CERI_SYM(CS6); /* 16|0x10 */
#endif
#if defined(CS7)
	CERI_VSYMI(CS7,32);
#else
	CERI_SYM(CS7); /* 32|0x20 */
#endif
#if defined(CS8)
	CERI_VSYMI(CS8,48);
#else
	CERI_SYM(CS8); /* 48|0x30 */
#endif
#if defined(ISIG)
	CERI_VSYMI(ISIG,1);
#else
	CERI_SYM(ISIG); /* 1 */
#endif
#if defined(ICANON)
	CERI_VSYMI(ICANON,2);
#else
	CERI_SYM(ICANON); /* 2 */
#endif
#if defined(ECHO)
	CERI_VSYMI(ECHO,8);
#else
	CERI_SYM(ECHO); /* 8 */
#endif
#if defined(ECHOE)
	CERI_VSYMI(ECHOE,16);
#else
	CERI_SYM(ECHOE); /* 16|0x10 */
#endif
#if defined(ECHOK)
	CERI_VSYMI(ECHOK,32);
#else
	CERI_SYM(ECHOK); /* 32|0x20 */
#endif
#if defined(ECHONL)
	CERI_VSYMI(ECHONL,64);
#else
	CERI_SYM(ECHONL); /* 64|0x40 */
#endif
#if defined(ECHOCTL)
	CERI_VSYMI(ECHOCTL,512);
#else
	CERI_SYM(ECHOCTL); /* 512|0x200 */
#endif
#if defined(ECHOPRT)
	CERI_VSYMI(ECHOPRT,1024);
#else
	CERI_SYM(ECHOPRT); /* 1024|0x400 */
#endif
#if defined(ECHOKE)
	CERI_VSYMI(ECHOKE,2048);
#else
	CERI_SYM(ECHOKE); /* 2048|0x800 */
#endif
#if defined(NOFLSH)
	CERI_VSYMI(NOFLSH,128);
#else
	CERI_SYM(NOFLSH); /* 128|0x80 */
#endif
#if defined(TOSTOP)
	CERI_VSYMI(TOSTOP,256);
#else
	CERI_SYM(TOSTOP); /* 256|0x100 */
#endif
#if defined(IEXTEN)
	CERI_VSYMI(IEXTEN,32768);
#else
	CERI_SYM(IEXTEN); /* 32768|0x8000 */
#endif
#if defined(VEOF)
	CERI_VSYMI(VEOF,4);
#else
	CERI_SYM(VEOF); /* 4 */
#endif
#if defined(VEOL)
	CERI_VSYMI(VEOL,11);
#else
	CERI_SYM(VEOL); /* 11|0xb */
#endif
#if defined(VEOL2)
	CERI_VSYMI(VEOL2,16);
#else
	CERI_SYM(VEOL2); /* 16|0x10 */
#endif
#if defined(VERASE)
	CERI_VSYMI(VERASE,2);
#else
	CERI_SYM(VERASE); /* 2 */
#endif
#if defined(VINTR)
	CERI_VSYMI(VINTR,0);
#else
	CERI_SYM(VINTR); /* 0 */
#endif
#if defined(VKILL)
	CERI_VSYMI(VKILL,3);
#else
	CERI_SYM(VKILL); /* 3 */
#endif
#if defined(VLNEXT)
	CERI_VSYMI(VLNEXT,15);
#else
	CERI_SYM(VLNEXT); /* 15|0xf */
#endif
#if defined(VMIN)
	CERI_VSYMI(VMIN,6);
#else
	CERI_SYM(VMIN); /* 6 */
#endif
#if defined(VQUIT)
	CERI_VSYMI(VQUIT,1);
#else
	CERI_SYM(VQUIT); /* 1 */
#endif
#if defined(VREPRINT)
	CERI_VSYMI(VREPRINT,12);
#else
	CERI_SYM(VREPRINT); /* 12|0xc */
#endif
#if defined(VSTART)
	CERI_VSYMI(VSTART,8);
#else
	CERI_SYM(VSTART); /* 8 */
#endif
#if defined(VSTOP)
	CERI_VSYMI(VSTOP,9);
#else
	CERI_SYM(VSTOP); /* 9 */
#endif
#if defined(VSUSP)
	CERI_VSYMI(VSUSP,10);
#else
	CERI_SYM(VSUSP); /* 10|0xa */
#endif
#if defined(VTIME)
	CERI_VSYMI(VTIME,5);
#else
	CERI_SYM(VTIME); /* 5 */
#endif
#if defined(VWERASE)
	CERI_VSYMI(VWERASE,14);
#else
	CERI_SYM(VWERASE); /* 14|0xe */
#endif
#if defined(TCSANOW)
	CERI_VSYMI(TCSANOW,0);
#else
	CERI_SYM(TCSANOW); /* 0 */
#endif
#if defined(TCSADRAIN)
	CERI_VSYMI(TCSADRAIN,1);
#else
	CERI_SYM(TCSADRAIN); /* 1 */
#endif
#if defined(TCSAFLUSH)
	CERI_VSYMI(TCSAFLUSH,2);
#else
	CERI_SYM(TCSAFLUSH); /* 2 */
#endif
#if defined(TCIFLUSH)
	CERI_VSYMI(TCIFLUSH,0);
#else
	CERI_SYM(TCIFLUSH); /* 0 */
#endif
#if defined(TCOFLUSH)
	CERI_VSYMI(TCOFLUSH,1);
#else
	CERI_SYM(TCOFLUSH); /* 1 */
#endif
#if defined(TCIOFLUSH)
	CERI_VSYMI(TCIOFLUSH,2);
#else
	CERI_SYM(TCIOFLUSH); /* 2 */
#endif
#if defined(TCOOFF)
	CERI_VSYMI(TCOOFF,0);
#else
	CERI_SYM(TCOOFF); /* 0 */
#endif
#if defined(TCOON)
	CERI_VSYMI(TCOON,1);
#else
	CERI_SYM(TCOON); /* 1 */
#endif
#if defined(TCIOFF)
	CERI_VSYMI(TCIOFF,2);
#else
	CERI_SYM(TCIOFF); /* 2 */
#endif
#if defined(TCION)
	CERI_VSYMI(TCION,3);
#else
	CERI_SYM(TCION); /* 3 */
#endif
#if defined(B0)
	CERI_VSYMI(B0,0);
#else
	CERI_SYM(B0); /* 0 */
#endif
#if defined(B50)
	CERI_VSYMI(B50,1);
#else
	CERI_SYM(B50); /* 1 */
#endif
#if defined(B75)
	CERI_VSYMI(B75,2);
#else
	CERI_SYM(B75); /* 2 */
#endif
#if defined(B110)
	CERI_VSYMI(B110,3);
#else
	CERI_SYM(B110); /* 3 */
#endif
#if defined(B134)
	CERI_VSYMI(B134,4);
#else
	CERI_SYM(B134); /* 4 */
#endif
#if defined(B150)
	CERI_VSYMI(B150,5);
#else
	CERI_SYM(B150); /* 5 */
#endif
#if defined(B200)
	CERI_VSYMI(B200,6);
#else
	CERI_SYM(B200); /* 6 */
#endif
#if defined(B300)
	CERI_VSYMI(B300,7);
#else
	CERI_SYM(B300); /* 7 */
#endif
#if defined(B600)
	CERI_VSYMI(B600,8);
#else
	CERI_SYM(B600); /* 8 */
#endif
#if defined(B1200)
	CERI_VSYMI(B1200,9);
#else
	CERI_SYM(B1200); /* 9 */
#endif
#if defined(B1800)
	CERI_VSYMI(B1800,10);
#else
	CERI_SYM(B1800); /* 10|0xa */
#endif
#if defined(B2400)
	CERI_VSYMI(B2400,11);
#else
	CERI_SYM(B2400); /* 11|0xb */
#endif
#if defined(B4800)
	CERI_VSYMI(B4800,12);
#else
	CERI_SYM(B4800); /* 12|0xc */
#endif
#if defined(B9600)
	CERI_VSYMI(B9600,13);
#else
	CERI_SYM(B9600); /* 13|0xd */
#endif
#if defined(B19200)
	CERI_VSYMI(B19200,14);
#else
	CERI_SYM(B19200); /* 14|0xe */
#endif
#if defined(B38400)
	CERI_VSYMI(B38400,15);
#else
	CERI_SYM(B38400); /* 15|0xf */
#endif
#if defined(B57600)
	CERI_VSYMI(B57600,4097);
#else
	CERI_SYM(B57600); /* 4097|0x1001 */
#endif
#if defined(B115200)
	CERI_VSYMI(B115200,4098);
#else
	CERI_SYM(B115200); /* 4098|0x1002 */
#endif
#if defined(B230400)
	CERI_VSYMI(B230400,4099);
#else
	CERI_SYM(B230400); /* 4099|0x1003 */
#endif
#if defined(B460800)
	CERI_VSYMI(B460800,4100);
#else
	CERI_SYM(B460800); /* 4100|0x1004 */
#endif
#if defined(B500000)
	CERI_VSYMI(B500000,4101);
#else
	CERI_SYM(B500000); /* 4101|0x1005 */
#endif
#if defined(B576000)
	CERI_VSYMI(B576000,4102);
#else
	CERI_SYM(B576000); /* 4102|0x1006 */
#endif
#if defined(B921600)
	CERI_VSYMI(B921600,4103);
#else
	CERI_SYM(B921600); /* 4103|0x1007 */
#endif
#if defined(B1000000)
	CERI_VSYMI(B1000000,4104);
#else
	CERI_SYM(B1000000); /* 4104|0x1008 */
#endif
#if defined(B1152000)
	CERI_VSYMI(B1152000,4105);
#else
	CERI_SYM(B1152000); /* 4105|0x1009 */
#endif
#if defined(B1500000)
	CERI_VSYMI(B1500000,4106);
#else
	CERI_SYM(B1500000); /* 4106|0x100a */
#endif
#if defined(B2000000)
	CERI_VSYMI(B2000000,4107);
#else
	CERI_SYM(B2000000); /* 4107|0x100b */
#endif
#if defined(B2500000)
	CERI_VSYMI(B2500000,4108);
#else
	CERI_SYM(B2500000); /* 4108|0x100c */
#endif
#if defined(B3000000)
	CERI_VSYMI(B3000000,4109);
#else
	CERI_SYM(B3000000); /* 4109|0x100d */
#endif
#if defined(B3500000)
	CERI_VSYMI(B3500000,4110);
#else
	CERI_SYM(B3500000); /* 4110|0x100e */
#endif
#if defined(B4000000)
	CERI_VSYMI(B4000000,4111);
#else
	CERI_SYM(B4000000); /* 4111|0x100f */
#endif
	
	printf("\n// CUnistd types\n");
#if defined(STDIN_FILENO)
	CERI_VSYMI(STDIN_FILENO,0);
#else
	CERI_SYM(STDIN_FILENO); /* 0 */
#endif
#if defined(STDOUT_FILENO)
	CERI_VSYMI(STDOUT_FILENO,1);
#else
	CERI_SYM(STDOUT_FILENO); /* 1 */
#endif
#if defined(STDERR_FILENO)
	CERI_VSYMI(STDERR_FILENO,2);
#else
	CERI_SYM(STDERR_FILENO); /* 2 */
#endif
#if defined(SEEK_SET)
	CERI_VSYMI(SEEK_SET,0);
#else
	CERI_SYM(SEEK_SET); /* 0 */
#endif
#if defined(SEEK_CUR)
	CERI_VSYMI(SEEK_CUR,1);
#else
	CERI_SYM(SEEK_CUR); /* 1 */
#endif
#if defined(SEEK_END)
	CERI_VSYMI(SEEK_END,2);
#else
	CERI_SYM(SEEK_END); /* 2 */
#endif

	printf("\n");
	if (ceri_errors > 0) printf("[ERRORS: %d]\n", ceri_errors);
	if (ceri_undefineds > 0) printf("[undefined: %d]\n", ceri_undefineds);
	return 0;
}
