// Generated by CSymbolGen 2024-03-19T21:15:54

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>
#include <termios.h>
#include <signal.h>
#include <errno.h>
#include <sys/ioctl.h>
#ifdef __linux__
#include <linux/serial.h>
#endif
#ifdef __APPLE__
#include <IOKit/serial/ioss.h>
#endif

/*
 * Example code to print symbols and type sizes.
 *
 * Build:
 * gcc symbols.c -o symbols; chmod a+x ./symbols
 * gcc -I<header-include-path> symbols.c -o symbols; chmod a+x ./symbols
 *
 * Run:
 * ./symbols # default arg 013
 * ./symbols 013 # generate with dec, hex and symbol definitions
 * ./symbols 102 # generate java constants with hex values
 */

#define STR(x) #x
#define SYM(x) print_symbol(#x,STR(x))
#define SYMI(x) print_symbol_i(#x,STR(x),x)
#define SIZE(x) print_symbol_i("sizeof("#x")","",sizeof(x))
#define FSIZE(t,f) print_symbol_i("sizeof("#t"."#f")","",(sizeof(((t*)0)->f)))
#define VERIFY(x) verify_int((x),STR(x))

#define FMT_DEC		0x001
#define FMT_HEX		0x002
#define FMT_OCT		0x004
#define FMT_SYM		0x010
#define FMT_JAVA	0x100
#define FMT_DEF		0x013

int format = FMT_DEF;
char uname[200];

void print_symbol(const char *name, const char *symbol) {
	if (format & FMT_JAVA) printf("public static final int ");
	printf("%s = ", name);
	if (strlen(symbol) == 0) printf("<defined>");
	else if (strcmp(name, symbol) == 0) printf("<undefined?>");
	else printf("%s", symbol);
	printf(";\n");
}

void format_sizeof(const char *name, int isymbol) {
    int offset = 7; // sizeof(
    if (strncmp(name + offset, "struct ", 7) == 0) offset += 7;
    int len = strlen(name + offset) - 1;
    strncpy(uname, name + offset, len);
    for (int i = 0; i < len; i++) {
        uname[i] = toupper(uname[i]);
        if (uname[i] == '.') uname[i] = '_';
    }
    uname[len] = 0;
    printf("%s_SIZE = %d; // %s", uname, isymbol, name);
}

void format_symbol_i(const char *name, const char *symbol, int isymbol) {
	printf("%s", name);
	if (format & FMT_DEC) printf(" = %d", isymbol);
	if (format & FMT_HEX) printf(" = 0x%x", isymbol);
	if (format & FMT_OCT) printf(" = 0%o", isymbol);
	if ((format & FMT_SYM) && strlen(symbol) > 0) printf(" = %s", symbol);
}

void print_symbol_i(const char *name, const char *symbol, int isymbol) {
	if (format & FMT_JAVA) printf("public static final int ");
	if ((format & FMT_JAVA) && strncmp(name, "sizeof(", 7) == 0) format_sizeof(name, isymbol);
	else format_symbol_i(name, symbol, isymbol);
	printf(";\n");
}

int verify_int(int r, const char *s) {
    printf("%s => 0x%x 0%o %d", s, r, r, r);
    if (r < 0) printf(" [ERROR]\n");
    else printf("\n");
    return r;
}

void set_format_flags(int argc, char *argv[]) {
	if (argc < 2) return;
	char* p;
	long value = strtol(argv[1], &p, 16);
	if (*p == '\0') format = (int) value; // ok
	else printf("Bad format '%s', using %03x\n", argv[1], format);
}

int main(int argc, char *argv[]) {
	set_format_flags(argc, argv);
	printf("\n");
	SIZE(int);
	SIZE(long);
	SIZE(size_t);
	SIZE(mode_t);
	SIZE(speed_t);
	SIZE(nfds_t);
	SIZE(sigset_t);
	SIZE(time_t);
	SIZE(struct timespec);
	FSIZE(struct timespec,tv_sec);
	FSIZE(struct timespec,tv_nsec);
	
	printf("\n// CErrNo types\n");
#ifdef EPERM
	SYMI(EPERM);
#else
	SYM(EPERM);
#endif
#ifdef ENOENT
	SYMI(ENOENT);
#else
	SYM(ENOENT);
#endif
#ifdef ESRCH
	SYMI(ESRCH);
#else
	SYM(ESRCH);
#endif
#ifdef EINTR
	SYMI(EINTR);
#else
	SYM(EINTR);
#endif
#ifdef EIO
	SYMI(EIO);
#else
	SYM(EIO);
#endif
#ifdef ENXIO
	SYMI(ENXIO);
#else
	SYM(ENXIO);
#endif
#ifdef E2BIG
	SYMI(E2BIG);
#else
	SYM(E2BIG);
#endif
#ifdef ENOEXEC
	SYMI(ENOEXEC);
#else
	SYM(ENOEXEC);
#endif
#ifdef EBADF
	SYMI(EBADF);
#else
	SYM(EBADF);
#endif
#ifdef ECHILD
	SYMI(ECHILD);
#else
	SYM(ECHILD);
#endif
#ifdef EAGAIN
	SYMI(EAGAIN);
#else
	SYM(EAGAIN);
#endif
#ifdef EWOULDBLOCK
	SYMI(EWOULDBLOCK);
#else
	SYM(EWOULDBLOCK);
#endif
#ifdef ENOMEM
	SYMI(ENOMEM);
#else
	SYM(ENOMEM);
#endif
#ifdef EACCES
	SYMI(EACCES);
#else
	SYM(EACCES);
#endif
#ifdef EFAULT
	SYMI(EFAULT);
#else
	SYM(EFAULT);
#endif
#ifdef ENOTBLK
	SYMI(ENOTBLK);
#else
	SYM(ENOTBLK);
#endif
#ifdef EBUSY
	SYMI(EBUSY);
#else
	SYM(EBUSY);
#endif
#ifdef EEXIST
	SYMI(EEXIST);
#else
	SYM(EEXIST);
#endif
#ifdef EXDEV
	SYMI(EXDEV);
#else
	SYM(EXDEV);
#endif
#ifdef ENODEV
	SYMI(ENODEV);
#else
	SYM(ENODEV);
#endif
#ifdef ENOTDIR
	SYMI(ENOTDIR);
#else
	SYM(ENOTDIR);
#endif
#ifdef EISDIR
	SYMI(EISDIR);
#else
	SYM(EISDIR);
#endif
#ifdef EINVAL
	SYMI(EINVAL);
#else
	SYM(EINVAL);
#endif
#ifdef ENFILE
	SYMI(ENFILE);
#else
	SYM(ENFILE);
#endif
#ifdef EMFILE
	SYMI(EMFILE);
#else
	SYM(EMFILE);
#endif
#ifdef ENOTTY
	SYMI(ENOTTY);
#else
	SYM(ENOTTY);
#endif
#ifdef ETXTBSY
	SYMI(ETXTBSY);
#else
	SYM(ETXTBSY);
#endif
#ifdef EFBIG
	SYMI(EFBIG);
#else
	SYM(EFBIG);
#endif
#ifdef ENOSPC
	SYMI(ENOSPC);
#else
	SYM(ENOSPC);
#endif
#ifdef ESPIPE
	SYMI(ESPIPE);
#else
	SYM(ESPIPE);
#endif
#ifdef EROFS
	SYMI(EROFS);
#else
	SYM(EROFS);
#endif
#ifdef EMLINK
	SYMI(EMLINK);
#else
	SYM(EMLINK);
#endif
#ifdef EPIPE
	SYMI(EPIPE);
#else
	SYM(EPIPE);
#endif
#ifdef EDOM
	SYMI(EDOM);
#else
	SYM(EDOM);
#endif
#ifdef ERANGE
	SYMI(ERANGE);
#else
	SYM(ERANGE);
#endif
#ifdef EDEADLK
	SYMI(EDEADLK);
#else
	SYM(EDEADLK);
#endif
#ifdef ENAMETOOLONG
	SYMI(ENAMETOOLONG);
#else
	SYM(ENAMETOOLONG);
#endif
#ifdef ENOLCK
	SYMI(ENOLCK);
#else
	SYM(ENOLCK);
#endif
#ifdef ENOSYS
	SYMI(ENOSYS);
#else
	SYM(ENOSYS);
#endif
#ifdef ENOTEMPTY
	SYMI(ENOTEMPTY);
#else
	SYM(ENOTEMPTY);
#endif
#ifdef ELOOP
	SYMI(ELOOP);
#else
	SYM(ELOOP);
#endif
#ifdef ENOMSG
	SYMI(ENOMSG);
#else
	SYM(ENOMSG);
#endif
#ifdef EIDRM
	SYMI(EIDRM);
#else
	SYM(EIDRM);
#endif
#ifdef ECHRNG
	SYMI(ECHRNG);
#else
	SYM(ECHRNG);
#endif
#ifdef EL2NSYNC
	SYMI(EL2NSYNC);
#else
	SYM(EL2NSYNC);
#endif
#ifdef EL3HLT
	SYMI(EL3HLT);
#else
	SYM(EL3HLT);
#endif
#ifdef EL3RST
	SYMI(EL3RST);
#else
	SYM(EL3RST);
#endif
#ifdef ELNRNG
	SYMI(ELNRNG);
#else
	SYM(ELNRNG);
#endif
#ifdef EUNATCH
	SYMI(EUNATCH);
#else
	SYM(EUNATCH);
#endif
#ifdef ENOCSI
	SYMI(ENOCSI);
#else
	SYM(ENOCSI);
#endif
#ifdef EL2HLT
	SYMI(EL2HLT);
#else
	SYM(EL2HLT);
#endif
#ifdef EBADE
	SYMI(EBADE);
#else
	SYM(EBADE);
#endif
#ifdef EBADR
	SYMI(EBADR);
#else
	SYM(EBADR);
#endif
#ifdef EXFULL
	SYMI(EXFULL);
#else
	SYM(EXFULL);
#endif
#ifdef ENOANO
	SYMI(ENOANO);
#else
	SYM(ENOANO);
#endif
#ifdef EBADRQC
	SYMI(EBADRQC);
#else
	SYM(EBADRQC);
#endif
#ifdef EBADSLT
	SYMI(EBADSLT);
#else
	SYM(EBADSLT);
#endif
#ifdef EBFONT
	SYMI(EBFONT);
#else
	SYM(EBFONT);
#endif
#ifdef ENOSTR
	SYMI(ENOSTR);
#else
	SYM(ENOSTR);
#endif
#ifdef ENODATA
	SYMI(ENODATA);
#else
	SYM(ENODATA);
#endif
#ifdef ETIME
	SYMI(ETIME);
#else
	SYM(ETIME);
#endif
#ifdef ENOSR
	SYMI(ENOSR);
#else
	SYM(ENOSR);
#endif
#ifdef ENONET
	SYMI(ENONET);
#else
	SYM(ENONET);
#endif
#ifdef ENOPKG
	SYMI(ENOPKG);
#else
	SYM(ENOPKG);
#endif
#ifdef EREMOTE
	SYMI(EREMOTE);
#else
	SYM(EREMOTE);
#endif
#ifdef ENOLINK
	SYMI(ENOLINK);
#else
	SYM(ENOLINK);
#endif
#ifdef EADV
	SYMI(EADV);
#else
	SYM(EADV);
#endif
#ifdef ESRMNT
	SYMI(ESRMNT);
#else
	SYM(ESRMNT);
#endif
#ifdef ECOMM
	SYMI(ECOMM);
#else
	SYM(ECOMM);
#endif
#ifdef EPROTO
	SYMI(EPROTO);
#else
	SYM(EPROTO);
#endif
#ifdef EMULTIHOP
	SYMI(EMULTIHOP);
#else
	SYM(EMULTIHOP);
#endif
#ifdef EDOTDOT
	SYMI(EDOTDOT);
#else
	SYM(EDOTDOT);
#endif
#ifdef EBADMSG
	SYMI(EBADMSG);
#else
	SYM(EBADMSG);
#endif
#ifdef EOVERFLOW
	SYMI(EOVERFLOW);
#else
	SYM(EOVERFLOW);
#endif
#ifdef ENOTUNIQ
	SYMI(ENOTUNIQ);
#else
	SYM(ENOTUNIQ);
#endif
#ifdef EBADFD
	SYMI(EBADFD);
#else
	SYM(EBADFD);
#endif
#ifdef EREMCHG
	SYMI(EREMCHG);
#else
	SYM(EREMCHG);
#endif
#ifdef ELIBACC
	SYMI(ELIBACC);
#else
	SYM(ELIBACC);
#endif
#ifdef ELIBBAD
	SYMI(ELIBBAD);
#else
	SYM(ELIBBAD);
#endif
#ifdef ELIBSCN
	SYMI(ELIBSCN);
#else
	SYM(ELIBSCN);
#endif
#ifdef ELIBMAX
	SYMI(ELIBMAX);
#else
	SYM(ELIBMAX);
#endif
#ifdef ELIBEXEC
	SYMI(ELIBEXEC);
#else
	SYM(ELIBEXEC);
#endif
#ifdef EILSEQ
	SYMI(EILSEQ);
#else
	SYM(EILSEQ);
#endif
#ifdef ERESTART
	SYMI(ERESTART);
#else
	SYM(ERESTART);
#endif
#ifdef ESTRPIPE
	SYMI(ESTRPIPE);
#else
	SYM(ESTRPIPE);
#endif
#ifdef EUSERS
	SYMI(EUSERS);
#else
	SYM(EUSERS);
#endif
#ifdef ENOTSOCK
	SYMI(ENOTSOCK);
#else
	SYM(ENOTSOCK);
#endif
#ifdef EDESTADDRREQ
	SYMI(EDESTADDRREQ);
#else
	SYM(EDESTADDRREQ);
#endif
#ifdef EMSGSIZE
	SYMI(EMSGSIZE);
#else
	SYM(EMSGSIZE);
#endif
#ifdef EPROTOTYPE
	SYMI(EPROTOTYPE);
#else
	SYM(EPROTOTYPE);
#endif
#ifdef ENOPROTOOPT
	SYMI(ENOPROTOOPT);
#else
	SYM(ENOPROTOOPT);
#endif
#ifdef EPROTONOSUPPORT
	SYMI(EPROTONOSUPPORT);
#else
	SYM(EPROTONOSUPPORT);
#endif
#ifdef ESOCKTNOSUPPORT
	SYMI(ESOCKTNOSUPPORT);
#else
	SYM(ESOCKTNOSUPPORT);
#endif
#ifdef EOPNOTSUPP
	SYMI(EOPNOTSUPP);
#else
	SYM(EOPNOTSUPP);
#endif
#ifdef ENOTSUP
	SYMI(ENOTSUP);
#else
	SYM(ENOTSUP);
#endif
#ifdef EPFNOSUPPORT
	SYMI(EPFNOSUPPORT);
#else
	SYM(EPFNOSUPPORT);
#endif
#ifdef EAFNOSUPPORT
	SYMI(EAFNOSUPPORT);
#else
	SYM(EAFNOSUPPORT);
#endif
#ifdef EADDRINUSE
	SYMI(EADDRINUSE);
#else
	SYM(EADDRINUSE);
#endif
#ifdef EADDRNOTAVAIL
	SYMI(EADDRNOTAVAIL);
#else
	SYM(EADDRNOTAVAIL);
#endif
#ifdef ENETDOWN
	SYMI(ENETDOWN);
#else
	SYM(ENETDOWN);
#endif
#ifdef ENETUNREACH
	SYMI(ENETUNREACH);
#else
	SYM(ENETUNREACH);
#endif
#ifdef ENETRESET
	SYMI(ENETRESET);
#else
	SYM(ENETRESET);
#endif
#ifdef ECONNABORTED
	SYMI(ECONNABORTED);
#else
	SYM(ECONNABORTED);
#endif
#ifdef ECONNRESET
	SYMI(ECONNRESET);
#else
	SYM(ECONNRESET);
#endif
#ifdef ENOBUFS
	SYMI(ENOBUFS);
#else
	SYM(ENOBUFS);
#endif
#ifdef EISCONN
	SYMI(EISCONN);
#else
	SYM(EISCONN);
#endif
#ifdef ENOTCONN
	SYMI(ENOTCONN);
#else
	SYM(ENOTCONN);
#endif
#ifdef ESHUTDOWN
	SYMI(ESHUTDOWN);
#else
	SYM(ESHUTDOWN);
#endif
#ifdef ETOOMANYREFS
	SYMI(ETOOMANYREFS);
#else
	SYM(ETOOMANYREFS);
#endif
#ifdef ETIMEDOUT
	SYMI(ETIMEDOUT);
#else
	SYM(ETIMEDOUT);
#endif
#ifdef ECONNREFUSED
	SYMI(ECONNREFUSED);
#else
	SYM(ECONNREFUSED);
#endif
#ifdef EHOSTDOWN
	SYMI(EHOSTDOWN);
#else
	SYM(EHOSTDOWN);
#endif
#ifdef EHOSTUNREACH
	SYMI(EHOSTUNREACH);
#else
	SYM(EHOSTUNREACH);
#endif
#ifdef EALREADY
	SYMI(EALREADY);
#else
	SYM(EALREADY);
#endif
#ifdef EINPROGRESS
	SYMI(EINPROGRESS);
#else
	SYM(EINPROGRESS);
#endif
#ifdef ESTALE
	SYMI(ESTALE);
#else
	SYM(ESTALE);
#endif
#ifdef EUCLEAN
	SYMI(EUCLEAN);
#else
	SYM(EUCLEAN);
#endif
#ifdef ENOTNAM
	SYMI(ENOTNAM);
#else
	SYM(ENOTNAM);
#endif
#ifdef ENAVAIL
	SYMI(ENAVAIL);
#else
	SYM(ENAVAIL);
#endif
#ifdef EISNAM
	SYMI(EISNAM);
#else
	SYM(EISNAM);
#endif
#ifdef EREMOTEIO
	SYMI(EREMOTEIO);
#else
	SYM(EREMOTEIO);
#endif
#ifdef EDQUOT
	SYMI(EDQUOT);
#else
	SYM(EDQUOT);
#endif
#ifdef ENOMEDIUM
	SYMI(ENOMEDIUM);
#else
	SYM(ENOMEDIUM);
#endif
#ifdef EMEDIUMTYPE
	SYMI(EMEDIUMTYPE);
#else
	SYM(EMEDIUMTYPE);
#endif
#ifdef ECANCELED
	SYMI(ECANCELED);
#else
	SYM(ECANCELED);
#endif
#ifdef ENOKEY
	SYMI(ENOKEY);
#else
	SYM(ENOKEY);
#endif
#ifdef EKEYEXPIRED
	SYMI(EKEYEXPIRED);
#else
	SYM(EKEYEXPIRED);
#endif
#ifdef EKEYREVOKED
	SYMI(EKEYREVOKED);
#else
	SYM(EKEYREVOKED);
#endif
#ifdef EKEYREJECTED
	SYMI(EKEYREJECTED);
#else
	SYM(EKEYREJECTED);
#endif
#ifdef EOWNERDEAD
	SYMI(EOWNERDEAD);
#else
	SYM(EOWNERDEAD);
#endif
#ifdef ENOTRECOVERABLE
	SYMI(ENOTRECOVERABLE);
#else
	SYM(ENOTRECOVERABLE);
#endif
#ifdef ERFKILL
	SYMI(ERFKILL);
#else
	SYM(ERFKILL);
#endif
#ifdef EHWPOISON
	SYMI(EHWPOISON);
#else
	SYM(EHWPOISON);
#endif
#ifdef EAUTH
	SYMI(EAUTH);
#else
	SYM(EAUTH);
#endif
#ifdef EBADRPC
	SYMI(EBADRPC);
#else
	SYM(EBADRPC);
#endif
#ifdef EFTYPE
	SYMI(EFTYPE);
#else
	SYM(EFTYPE);
#endif
#ifdef ENEEDAUTH
	SYMI(ENEEDAUTH);
#else
	SYM(ENEEDAUTH);
#endif
#ifdef ENOATTR
	SYMI(ENOATTR);
#else
	SYM(ENOATTR);
#endif
#ifdef EPROCLIM
	SYMI(EPROCLIM);
#else
	SYM(EPROCLIM);
#endif
#ifdef EPROCUNAVAIL
	SYMI(EPROCUNAVAIL);
#else
	SYM(EPROCUNAVAIL);
#endif
#ifdef EPROGMISMATCH
	SYMI(EPROGMISMATCH);
#else
	SYM(EPROGMISMATCH);
#endif
#ifdef EPROGUNAVAIL
	SYMI(EPROGUNAVAIL);
#else
	SYM(EPROGUNAVAIL);
#endif
#ifdef ERPCMISMATCH
	SYMI(ERPCMISMATCH);
#else
	SYM(ERPCMISMATCH);
#endif
	
	printf("\n// CFcntl types\n");
#ifdef O_RDONLY
	SYMI(O_RDONLY);
#else
	SYM(O_RDONLY);
#endif
#ifdef O_WRONLY
	SYMI(O_WRONLY);
#else
	SYM(O_WRONLY);
#endif
#ifdef O_RDWR
	SYMI(O_RDWR);
#else
	SYM(O_RDWR);
#endif
#ifdef O_ACCMODE
	SYMI(O_ACCMODE);
#else
	SYM(O_ACCMODE);
#endif
#ifdef O_CREAT
	SYMI(O_CREAT);
#else
	SYM(O_CREAT);
#endif
#ifdef O_EXCL
	SYMI(O_EXCL);
#else
	SYM(O_EXCL);
#endif
#ifdef O_NOCTTY
	SYMI(O_NOCTTY);
#else
	SYM(O_NOCTTY);
#endif
#ifdef O_TRUNC
	SYMI(O_TRUNC);
#else
	SYM(O_TRUNC);
#endif
#ifdef O_APPEND
	SYMI(O_APPEND);
#else
	SYM(O_APPEND);
#endif
#ifdef O_NONBLOCK
	SYMI(O_NONBLOCK);
#else
	SYM(O_NONBLOCK);
#endif
#ifdef O_DSYNC
	SYMI(O_DSYNC);
#else
	SYM(O_DSYNC);
#endif
#ifdef O_ASYNC
	SYMI(O_ASYNC);
#else
	SYM(O_ASYNC);
#endif
#ifdef O_DIRECTORY
	SYMI(O_DIRECTORY);
#else
	SYM(O_DIRECTORY);
#endif
#ifdef O_NOFOLLOW
	SYMI(O_NOFOLLOW);
#else
	SYM(O_NOFOLLOW);
#endif
#ifdef O_CLOEXEC
	SYMI(O_CLOEXEC);
#else
	SYM(O_CLOEXEC);
#endif
#ifdef O_SYNC
	SYMI(O_SYNC);
#else
	SYM(O_SYNC);
#endif
#ifdef F_DUPFD
	SYMI(F_DUPFD);
#else
	SYM(F_DUPFD);
#endif
#ifdef F_GETFD
	SYMI(F_GETFD);
#else
	SYM(F_GETFD);
#endif
#ifdef F_SETFD
	SYMI(F_SETFD);
#else
	SYM(F_SETFD);
#endif
#ifdef F_GETFL
	SYMI(F_GETFL);
#else
	SYM(F_GETFL);
#endif
#ifdef F_SETFL
	SYMI(F_SETFL);
#else
	SYM(F_SETFL);
#endif
	
	printf("\n// CIoctl types\n");
#ifdef _IOC_SIZEBITS
	SYMI(_IOC_SIZEBITS);
#else
	SYM(_IOC_SIZEBITS);
#endif
#ifdef _IOC_SIZEMASK
	SYMI(_IOC_SIZEMASK);
#else
	SYM(_IOC_SIZEMASK);
#endif
#ifdef IOC_VOID
	SYMI(IOC_VOID);
#else
	SYM(IOC_VOID);
#endif
#ifdef IOC_OUT
	SYMI(IOC_OUT);
#else
	SYM(IOC_OUT);
#endif
#ifdef IOC_IN
	SYMI(IOC_IN);
#else
	SYM(IOC_IN);
#endif
#ifdef TIOCSBRK
	SYMI(TIOCSBRK);
#else
	SYM(TIOCSBRK);
#endif
#ifdef TIOCCBRK
	SYMI(TIOCCBRK);
#else
	SYM(TIOCCBRK);
#endif
#ifdef FIONREAD
	SYMI(FIONREAD);
#else
	SYM(FIONREAD);
#endif
#ifdef TIOCEXCL
	SYMI(TIOCEXCL);
#else
	SYM(TIOCEXCL);
#endif
#ifdef TIOCOUTQ
	SYMI(TIOCOUTQ);
#else
	SYM(TIOCOUTQ);
#endif
#ifdef TIOCMGET
	SYMI(TIOCMGET);
#else
	SYM(TIOCMGET);
#endif
#ifdef TIOCMBIC
	SYMI(TIOCMBIC);
#else
	SYM(TIOCMBIC);
#endif
#ifdef TIOCMBIS
	SYMI(TIOCMBIS);
#else
	SYM(TIOCMBIS);
#endif
#ifdef TIOCMSET
	SYMI(TIOCMSET);
#else
	SYM(TIOCMSET);
#endif
#ifdef TIOCM_LE
	SYMI(TIOCM_LE);
#else
	SYM(TIOCM_LE);
#endif
#ifdef TIOCM_DTR
	SYMI(TIOCM_DTR);
#else
	SYM(TIOCM_DTR);
#endif
#ifdef TIOCM_RTS
	SYMI(TIOCM_RTS);
#else
	SYM(TIOCM_RTS);
#endif
#ifdef TIOCM_CTS
	SYMI(TIOCM_CTS);
#else
	SYM(TIOCM_CTS);
#endif
#ifdef TIOCM_CD
	SYMI(TIOCM_CD);
#else
	SYM(TIOCM_CD);
#endif
#ifdef TIOCM_RI
	SYMI(TIOCM_RI);
#else
	SYM(TIOCM_RI);
#endif
#ifdef TIOCM_DSR
	SYMI(TIOCM_DSR);
#else
	SYM(TIOCM_DSR);
#endif
	
	printf("\n// CIoctl.Linux types\n");
#ifdef ASYNC_SPD_HI
	SYMI(ASYNC_SPD_HI);
#else
	SYM(ASYNC_SPD_HI);
#endif
#ifdef ASYNC_SPD_VHI
	SYMI(ASYNC_SPD_VHI);
#else
	SYM(ASYNC_SPD_VHI);
#endif
#ifdef ASYNC_SPD_SHI
	SYMI(ASYNC_SPD_SHI);
#else
	SYM(ASYNC_SPD_SHI);
#endif
#ifdef ASYNC_SPD_CUST
	SYMI(ASYNC_SPD_CUST);
#else
	SYM(ASYNC_SPD_CUST);
#endif
#ifdef ASYNC_SPD_MASK
	SYMI(ASYNC_SPD_MASK);
#else
	SYM(ASYNC_SPD_MASK);
#endif
#ifdef TIOCGSERIAL
	SYMI(TIOCGSERIAL);
#else
	SYM(TIOCGSERIAL);
#endif
#ifdef TIOCSSERIAL
	SYMI(TIOCSSERIAL);
#else
	SYM(TIOCSSERIAL);
#endif
	
	printf("\n// CIoctl.Mac types\n");
#ifdef IOSSIOSPEED
	SYMI(IOSSIOSPEED);
#else
	SYM(IOSSIOSPEED);
#endif
	
	printf("\n// CPoll types\n");
#ifdef POLLIN
	SYMI(POLLIN);
#else
	SYM(POLLIN);
#endif
#ifdef POLLPRI
	SYMI(POLLPRI);
#else
	SYM(POLLPRI);
#endif
#ifdef POLLOUT
	SYMI(POLLOUT);
#else
	SYM(POLLOUT);
#endif
#ifdef POLLERR
	SYMI(POLLERR);
#else
	SYM(POLLERR);
#endif
#ifdef POLLHUP
	SYMI(POLLHUP);
#else
	SYM(POLLHUP);
#endif
#ifdef POLLNVAL
	SYMI(POLLNVAL);
#else
	SYM(POLLNVAL);
#endif
	
	printf("\n// CSignal types\n");
#ifdef SIGHUP
	SYMI(SIGHUP);
#else
	SYM(SIGHUP);
#endif
#ifdef SIGINT
	SYMI(SIGINT);
#else
	SYM(SIGINT);
#endif
#ifdef SIGQUIT
	SYMI(SIGQUIT);
#else
	SYM(SIGQUIT);
#endif
#ifdef SIGILL
	SYMI(SIGILL);
#else
	SYM(SIGILL);
#endif
#ifdef SIGTRAP
	SYMI(SIGTRAP);
#else
	SYM(SIGTRAP);
#endif
#ifdef SIGABRT
	SYMI(SIGABRT);
#else
	SYM(SIGABRT);
#endif
#ifdef SIGIOT
	SYMI(SIGIOT);
#else
	SYM(SIGIOT);
#endif
#ifdef SIGBUS
	SYMI(SIGBUS);
#else
	SYM(SIGBUS);
#endif
#ifdef SIGFPE
	SYMI(SIGFPE);
#else
	SYM(SIGFPE);
#endif
#ifdef SIGKILL
	SYMI(SIGKILL);
#else
	SYM(SIGKILL);
#endif
#ifdef SIGUSR1
	SYMI(SIGUSR1);
#else
	SYM(SIGUSR1);
#endif
#ifdef SIGSEGV
	SYMI(SIGSEGV);
#else
	SYM(SIGSEGV);
#endif
#ifdef SIGUSR2
	SYMI(SIGUSR2);
#else
	SYM(SIGUSR2);
#endif
#ifdef SIGPIPE
	SYMI(SIGPIPE);
#else
	SYM(SIGPIPE);
#endif
#ifdef SIGALRM
	SYMI(SIGALRM);
#else
	SYM(SIGALRM);
#endif
#ifdef SIGTERM
	SYMI(SIGTERM);
#else
	SYM(SIGTERM);
#endif
#ifdef SIGCHLD
	SYMI(SIGCHLD);
#else
	SYM(SIGCHLD);
#endif
#ifdef SIGCONT
	SYMI(SIGCONT);
#else
	SYM(SIGCONT);
#endif
#ifdef SIGSTOP
	SYMI(SIGSTOP);
#else
	SYM(SIGSTOP);
#endif
#ifdef SIGTSTP
	SYMI(SIGTSTP);
#else
	SYM(SIGTSTP);
#endif
#ifdef SIGTTIN
	SYMI(SIGTTIN);
#else
	SYM(SIGTTIN);
#endif
#ifdef SIGTTOU
	SYMI(SIGTTOU);
#else
	SYM(SIGTTOU);
#endif
#ifdef SIGURG
	SYMI(SIGURG);
#else
	SYM(SIGURG);
#endif
#ifdef SIGXCPU
	SYMI(SIGXCPU);
#else
	SYM(SIGXCPU);
#endif
#ifdef SIGXFSZ
	SYMI(SIGXFSZ);
#else
	SYM(SIGXFSZ);
#endif
#ifdef SIGVTALRM
	SYMI(SIGVTALRM);
#else
	SYM(SIGVTALRM);
#endif
#ifdef SIGPROF
	SYMI(SIGPROF);
#else
	SYM(SIGPROF);
#endif
#ifdef SIGWINCH
	SYMI(SIGWINCH);
#else
	SYM(SIGWINCH);
#endif
#ifdef SIGIO
	SYMI(SIGIO);
#else
	SYM(SIGIO);
#endif
#ifdef SIGPOLL
	SYMI(SIGPOLL);
#else
	SYM(SIGPOLL);
#endif
#ifdef SIGSYS
	SYMI(SIGSYS);
#else
	SYM(SIGSYS);
#endif
	SYM(SIG_DFL);
	SYM(SIG_IGN);
	SYM(SIG_ERR);
	
	printf("\n// CTermios types\n");
#ifdef NCCS
	SYMI(NCCS);
#else
	SYM(NCCS);
#endif
#ifdef IXON
	SYMI(IXON);
#else
	SYM(IXON);
#endif
#ifdef IXOFF
	SYMI(IXOFF);
#else
	SYM(IXOFF);
#endif
#ifdef IXANY
	SYMI(IXANY);
#else
	SYM(IXANY);
#endif
#ifdef OPOST
	SYMI(OPOST);
#else
	SYM(OPOST);
#endif
#ifdef CSIZE
	SYMI(CSIZE);
#else
	SYM(CSIZE);
#endif
#ifdef CS5
	SYMI(CS5);
#else
	SYM(CS5);
#endif
#ifdef CS6
	SYMI(CS6);
#else
	SYM(CS6);
#endif
#ifdef CS7
	SYMI(CS7);
#else
	SYM(CS7);
#endif
#ifdef CS8
	SYMI(CS8);
#else
	SYM(CS8);
#endif
#ifdef CSTOPB
	SYMI(CSTOPB);
#else
	SYM(CSTOPB);
#endif
#ifdef CREAD
	SYMI(CREAD);
#else
	SYM(CREAD);
#endif
#ifdef PARENB
	SYMI(PARENB);
#else
	SYM(PARENB);
#endif
#ifdef CMSPAR
	SYMI(CMSPAR);
#else
	SYM(CMSPAR);
#endif
#ifdef PARODD
	SYMI(PARODD);
#else
	SYM(PARODD);
#endif
#ifdef CLOCAL
	SYMI(CLOCAL);
#else
	SYM(CLOCAL);
#endif
#ifdef CRTSCTS
	SYMI(CRTSCTS);
#else
	SYM(CRTSCTS);
#endif
#ifdef ISIG
	SYMI(ISIG);
#else
	SYM(ISIG);
#endif
#ifdef ICANON
	SYMI(ICANON);
#else
	SYM(ICANON);
#endif
#ifdef ECHO
	SYMI(ECHO);
#else
	SYM(ECHO);
#endif
#ifdef ECHOE
	SYMI(ECHOE);
#else
	SYM(ECHOE);
#endif
#ifdef VEOF
	SYMI(VEOF);
#else
	SYM(VEOF);
#endif
#ifdef VSTART
	SYMI(VSTART);
#else
	SYM(VSTART);
#endif
#ifdef VSTOP
	SYMI(VSTOP);
#else
	SYM(VSTOP);
#endif
#ifdef VMIN
	SYMI(VMIN);
#else
	SYM(VMIN);
#endif
#ifdef VTIME
	SYMI(VTIME);
#else
	SYM(VTIME);
#endif
#ifdef TCSANOW
	SYMI(TCSANOW);
#else
	SYM(TCSANOW);
#endif
#ifdef TCSADRAIN
	SYMI(TCSADRAIN);
#else
	SYM(TCSADRAIN);
#endif
#ifdef TCSAFLUSH
	SYMI(TCSAFLUSH);
#else
	SYM(TCSAFLUSH);
#endif
#ifdef TCIFLUSH
	SYMI(TCIFLUSH);
#else
	SYM(TCIFLUSH);
#endif
#ifdef TCOFLUSH
	SYMI(TCOFLUSH);
#else
	SYM(TCOFLUSH);
#endif
#ifdef TCIOFLUSH
	SYMI(TCIOFLUSH);
#else
	SYM(TCIOFLUSH);
#endif
#ifdef TCOOFF
	SYMI(TCOOFF);
#else
	SYM(TCOOFF);
#endif
#ifdef TCOON
	SYMI(TCOON);
#else
	SYM(TCOON);
#endif
#ifdef TCIOFF
	SYMI(TCIOFF);
#else
	SYM(TCIOFF);
#endif
#ifdef TCION
	SYMI(TCION);
#else
	SYM(TCION);
#endif
#ifdef B0
	SYMI(B0);
#else
	SYM(B0);
#endif
#ifdef B50
	SYMI(B50);
#else
	SYM(B50);
#endif
#ifdef B75
	SYMI(B75);
#else
	SYM(B75);
#endif
#ifdef B110
	SYMI(B110);
#else
	SYM(B110);
#endif
#ifdef B134
	SYMI(B134);
#else
	SYM(B134);
#endif
#ifdef B150
	SYMI(B150);
#else
	SYM(B150);
#endif
#ifdef B200
	SYMI(B200);
#else
	SYM(B200);
#endif
#ifdef B300
	SYMI(B300);
#else
	SYM(B300);
#endif
#ifdef B600
	SYMI(B600);
#else
	SYM(B600);
#endif
#ifdef B1200
	SYMI(B1200);
#else
	SYM(B1200);
#endif
#ifdef B1800
	SYMI(B1800);
#else
	SYM(B1800);
#endif
#ifdef B2400
	SYMI(B2400);
#else
	SYM(B2400);
#endif
#ifdef B4800
	SYMI(B4800);
#else
	SYM(B4800);
#endif
#ifdef B9600
	SYMI(B9600);
#else
	SYM(B9600);
#endif
#ifdef B19200
	SYMI(B19200);
#else
	SYM(B19200);
#endif
#ifdef B38400
	SYMI(B38400);
#else
	SYM(B38400);
#endif
#ifdef B57600
	SYMI(B57600);
#else
	SYM(B57600);
#endif
#ifdef B115200
	SYMI(B115200);
#else
	SYM(B115200);
#endif
#ifdef B230400
	SYMI(B230400);
#else
	SYM(B230400);
#endif
#ifdef B460800
	SYMI(B460800);
#else
	SYM(B460800);
#endif
#ifdef B500000
	SYMI(B500000);
#else
	SYM(B500000);
#endif
#ifdef B576000
	SYMI(B576000);
#else
	SYM(B576000);
#endif
#ifdef B921600
	SYMI(B921600);
#else
	SYM(B921600);
#endif
#ifdef B1000000
	SYMI(B1000000);
#else
	SYM(B1000000);
#endif
#ifdef B1152000
	SYMI(B1152000);
#else
	SYM(B1152000);
#endif
#ifdef B1500000
	SYMI(B1500000);
#else
	SYM(B1500000);
#endif
#ifdef B2000000
	SYMI(B2000000);
#else
	SYM(B2000000);
#endif
#ifdef B2500000
	SYMI(B2500000);
#else
	SYM(B2500000);
#endif
#ifdef B3000000
	SYMI(B3000000);
#else
	SYM(B3000000);
#endif
#ifdef B3500000
	SYMI(B3500000);
#else
	SYM(B3500000);
#endif
#ifdef B4000000
	SYMI(B4000000);
#else
	SYM(B4000000);
#endif
	
	printf("\n// CUnistd types\n");
#ifdef STDIN_FILENO
	SYMI(STDIN_FILENO);
#else
	SYM(STDIN_FILENO);
#endif
#ifdef STDOUT_FILENO
	SYMI(STDOUT_FILENO);
#else
	SYM(STDOUT_FILENO);
#endif
#ifdef STDERR_FILENO
	SYMI(STDERR_FILENO);
#else
	SYM(STDERR_FILENO);
#endif
#ifdef SEEK_SET
	SYMI(SEEK_SET);
#else
	SYM(SEEK_SET);
#endif
#ifdef SEEK_CUR
	SYMI(SEEK_CUR);
#else
	SYM(SEEK_CUR);
#endif
#ifdef SEEK_END
	SYMI(SEEK_END);
#else
	SYM(SEEK_END);
#endif
	printf("\n");

	return 0;
}

