/*
 * Generated for linux by CSymbolGen (Mac OS X; aarch64; 15.5) 2025-07-02T17:59:07
 *
 * Build:  gcc clib-symbols-linux.c -o clib-symbols-linux; chmod a+x ./clib-symbols-linux
 *  Run:  ./clib-symbols-linux
 */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <linux/serial.h>
#include <poll.h>
#include <signal.h>
#include <termios.h>
#include <unistd.h>

#define CERI_STR(x) #x
#define CERI_SYM(x) ceri_print_symbol(#x,CERI_STR(x))
#define CERI_SYMI(x) ceri_print_symbol_i(#x,CERI_STR(x),x)
#define CERI_VSYMI(x,y) ceri_verify_symbol_i(#x,CERI_STR(x),x,y)
#define CERI_SIZE(t) ceri_print_symbol_i("sizeof("#t")","",sizeof(t))
#define CERI_FSIZE(t,f) ceri_print_symbol_i("sizeof("#t"."#f")","",(sizeof(((t*)0)->f)))
#define CERI_VSIZE(t,s) ceri_verify_symbol_i("sizeof("#t")","",sizeof(t),s)

int ceri_errors = 0;
int ceri_undefineds = 0;

void ceri_print_symbol(const char *name, const char *sym) {
	printf("%s = ", name);
	if (strlen(sym) == 0) printf("<defined>");
	else if (strcmp(name, sym) == 0) {
		printf("<undefined?>");
		ceri_undefineds++;
	} else printf("\"%s\"", sym);
	printf("\n");
}

void ceri_print_symbol_i(const char *name, const char *sym, long int isym) {
	printf("%s = ", name);
	if (isym > -10 && isym <  10) printf("%ld", isym);
	else printf("%1$ld|0x%1$lx", isym);
	if (strlen(sym) > 0) printf(" \"%s\"", sym);
	printf("\n");
}

void ceri_verify_symbol_i(const char *name, const char *sym, long int isym, long int iexpect) {
	if (isym < -0xffffffff) isym &= 0xffffffff;
	if (isym != iexpect) {
		printf("[ERROR] %1$ld|0x%1$lx != ", iexpect);
		ceri_errors++;
	}
	ceri_print_symbol_i(name, sym, isym);
}

int main(int argc, char *argv[]) {
	
	printf("\n");
	printf("// CErrNo\n");
	// Ignore: UNDEFINED = -1
	CERI_VSYMI(EPERM,1);
	CERI_VSYMI(ENOENT,2);
	CERI_VSYMI(ESRCH,3);
	CERI_VSYMI(EINTR,4);
	CERI_VSYMI(EIO,5);
	CERI_VSYMI(ENXIO,6);
	CERI_VSYMI(E2BIG,7);
	CERI_VSYMI(ENOEXEC,8);
	CERI_VSYMI(EBADF,9);
	CERI_VSYMI(ECHILD,10);
	CERI_VSYMI(EAGAIN,11);
	CERI_VSYMI(EWOULDBLOCK,11);
	CERI_VSYMI(ENOMEM,12);
	CERI_VSYMI(EACCES,13);
	CERI_VSYMI(EFAULT,14);
	CERI_VSYMI(ENOTBLK,15);
	CERI_VSYMI(EBUSY,16);
	CERI_VSYMI(EEXIST,17);
	CERI_VSYMI(EXDEV,18);
	CERI_VSYMI(ENODEV,19);
	CERI_VSYMI(ENOTDIR,20);
	CERI_VSYMI(EISDIR,21);
	CERI_VSYMI(EINVAL,22);
	CERI_VSYMI(ENFILE,23);
	CERI_VSYMI(EMFILE,24);
	CERI_VSYMI(ENOTTY,25);
	CERI_VSYMI(ETXTBSY,26);
	CERI_VSYMI(EFBIG,27);
	CERI_VSYMI(ENOSPC,28);
	CERI_VSYMI(ESPIPE,29);
	CERI_VSYMI(EROFS,30);
	CERI_VSYMI(EMLINK,31);
	CERI_VSYMI(EPIPE,32);
	CERI_VSYMI(EDOM,33);
	CERI_VSYMI(ERANGE,34);
	CERI_VSYMI(EDEADLK,35);
	CERI_VSYMI(ENAMETOOLONG,36);
	CERI_VSYMI(ENOLCK,37);
	CERI_VSYMI(ENOSYS,38);
	CERI_VSYMI(ENOTEMPTY,39);
	CERI_VSYMI(ELOOP,40);
	CERI_VSYMI(ENOMSG,42);
	CERI_VSYMI(EIDRM,43);
	CERI_VSYMI(ECHRNG,44);
	CERI_VSYMI(EL2NSYNC,45);
	CERI_VSYMI(EL3HLT,46);
	CERI_VSYMI(EL3RST,47);
	CERI_VSYMI(ELNRNG,48);
	CERI_VSYMI(EUNATCH,49);
	CERI_VSYMI(ENOCSI,50);
	CERI_VSYMI(EL2HLT,51);
	CERI_VSYMI(EBADE,52);
	CERI_VSYMI(EBADR,53);
	CERI_VSYMI(EXFULL,54);
	CERI_VSYMI(ENOANO,55);
	CERI_VSYMI(EBADRQC,56);
	CERI_VSYMI(EBADSLT,57);
	CERI_VSYMI(EBFONT,59);
	CERI_VSYMI(ENOSTR,60);
	CERI_VSYMI(ENODATA,61);
	CERI_VSYMI(ETIME,62);
	CERI_VSYMI(ENOSR,63);
	CERI_VSYMI(ENONET,64);
	CERI_VSYMI(ENOPKG,65);
	CERI_VSYMI(EREMOTE,66);
	CERI_VSYMI(ENOLINK,67);
	CERI_VSYMI(EADV,68);
	CERI_VSYMI(ESRMNT,69);
	CERI_VSYMI(ECOMM,70);
	CERI_VSYMI(EPROTO,71);
	CERI_VSYMI(EMULTIHOP,72);
	CERI_VSYMI(EDOTDOT,73);
	CERI_VSYMI(EBADMSG,74);
	CERI_VSYMI(EOVERFLOW,75);
	CERI_VSYMI(ENOTUNIQ,76);
	CERI_VSYMI(EBADFD,77);
	CERI_VSYMI(EREMCHG,78);
	CERI_VSYMI(ELIBACC,79);
	CERI_VSYMI(ELIBBAD,80);
	CERI_VSYMI(ELIBSCN,81);
	CERI_VSYMI(ELIBMAX,82);
	CERI_VSYMI(ELIBEXEC,83);
	CERI_VSYMI(EILSEQ,84);
	CERI_VSYMI(ERESTART,85);
	CERI_VSYMI(ESTRPIPE,86);
	CERI_VSYMI(EUSERS,87);
	CERI_VSYMI(ENOTSOCK,88);
	CERI_VSYMI(EDESTADDRREQ,89);
	CERI_VSYMI(EMSGSIZE,90);
	CERI_VSYMI(EPROTOTYPE,91);
	CERI_VSYMI(ENOPROTOOPT,92);
	CERI_VSYMI(EPROTONOSUPPORT,93);
	CERI_VSYMI(ESOCKTNOSUPPORT,94);
	CERI_VSYMI(EOPNOTSUPP,95);
	CERI_VSYMI(ENOTSUP,95);
	CERI_VSYMI(EPFNOSUPPORT,96);
	CERI_VSYMI(EAFNOSUPPORT,97);
	CERI_VSYMI(EADDRINUSE,98);
	CERI_VSYMI(EADDRNOTAVAIL,99);
	CERI_VSYMI(ENETDOWN,100);
	CERI_VSYMI(ENETUNREACH,101);
	CERI_VSYMI(ENETRESET,102);
	CERI_VSYMI(ECONNABORTED,103);
	CERI_VSYMI(ECONNRESET,104);
	CERI_VSYMI(ENOBUFS,105);
	CERI_VSYMI(EISCONN,106);
	CERI_VSYMI(ENOTCONN,107);
	CERI_VSYMI(ESHUTDOWN,108);
	CERI_VSYMI(ETOOMANYREFS,109);
	CERI_VSYMI(ETIMEDOUT,110);
	CERI_VSYMI(ECONNREFUSED,111);
	CERI_VSYMI(EHOSTDOWN,112);
	CERI_VSYMI(EHOSTUNREACH,113);
	CERI_VSYMI(EALREADY,114);
	CERI_VSYMI(EINPROGRESS,115);
	CERI_VSYMI(ESTALE,116);
	CERI_VSYMI(EUCLEAN,117);
	CERI_VSYMI(ENOTNAM,118);
	CERI_VSYMI(ENAVAIL,119);
	CERI_VSYMI(EISNAM,120);
	CERI_VSYMI(EREMOTEIO,121);
	CERI_VSYMI(EDQUOT,122);
	CERI_VSYMI(ENOMEDIUM,123);
	CERI_VSYMI(EMEDIUMTYPE,124);
	CERI_VSYMI(ECANCELED,125);
	CERI_VSYMI(ENOKEY,126);
	CERI_VSYMI(EKEYEXPIRED,127);
	CERI_VSYMI(EKEYREVOKED,128);
	CERI_VSYMI(EKEYREJECTED,129);
	CERI_VSYMI(EOWNERDEAD,130);
	CERI_VSYMI(ENOTRECOVERABLE,131);
	CERI_VSYMI(ERFKILL,132);
	CERI_VSYMI(EHWPOISON,133);
	// Ignore: EAUTH = -1
	// Ignore: EBADRPC = -1
	// Ignore: EFTYPE = -1
	// Ignore: ENEEDAUTH = -1
	// Ignore: ENOATTR = -1
	// Ignore: EPROCLIM = -1
	// Ignore: EPROCUNAVAIL = -1
	// Ignore: EPROGMISMATCH = -1
	// Ignore: EPROGUNAVAIL = -1
	// Ignore: ERPCMISMATCH = -1
	
	printf("\n");
	printf("// CFcntl\n");
	// Ignore: INVALID_FD = -1
	CERI_VSYMI(O_RDONLY,0);
	CERI_VSYMI(O_WRONLY,1);
	CERI_VSYMI(O_RDWR,2);
	CERI_VSYMI(O_ACCMODE,3);
	CERI_VSYMI(O_CREAT,64);
	CERI_VSYMI(O_EXCL,128);
	CERI_VSYMI(O_NOCTTY,256);
	CERI_VSYMI(O_TRUNC,512);
	CERI_VSYMI(O_APPEND,1024);
	CERI_VSYMI(O_NONBLOCK,2048);
	CERI_VSYMI(O_DSYNC,4096);
	CERI_VSYMI(O_ASYNC,8192);
	CERI_VSYMI(O_DIRECTORY,16384);
	CERI_VSYMI(O_NOFOLLOW,32768);
	CERI_VSYMI(O_CLOEXEC,524288);
	CERI_VSYMI(O_SYNC,1052672);
	CERI_VSYMI(F_DUPFD,0);
	CERI_VSYMI(F_GETFD,1);
	CERI_VSYMI(F_SETFD,2);
	CERI_VSYMI(F_GETFL,3);
	CERI_VSYMI(F_SETFL,4);
	
	printf("\n");
	printf("// CIoctl\n");
	CERI_VSYMI(_IOC_SIZEBITS,14);
	CERI_VSYMI(_IOC_SIZEMASK,16383);
	CERI_VSYMI(_IOC_NONE,0);
	CERI_VSYMI(IOC_OUT,2147483648);
	CERI_VSYMI(IOC_IN,1073741824);
	CERI_VSYMI(TIOCSBRK,21543);
	CERI_VSYMI(TIOCCBRK,21544);
	CERI_VSYMI(FIONREAD,21531);
	CERI_VSYMI(TIOCEXCL,21516);
	CERI_VSYMI(TIOCOUTQ,21521);
	CERI_VSYMI(TIOCMGET,21525);
	CERI_VSYMI(TIOCMBIC,21527);
	CERI_VSYMI(TIOCMBIS,21526);
	CERI_VSYMI(TIOCMSET,21528);
	CERI_VSYMI(TIOCM_LE,1);
	CERI_VSYMI(TIOCM_DTR,2);
	CERI_VSYMI(TIOCM_RTS,4);
	CERI_VSYMI(TIOCM_CTS,32);
	CERI_VSYMI(TIOCM_CD,64);
	CERI_VSYMI(TIOCM_RI,128);
	CERI_VSYMI(TIOCM_DSR,256);
	printf("// CIoctl.Linux\n");
	CERI_VSYMI(ASYNC_SPD_HI,16);
	CERI_VSYMI(ASYNC_SPD_VHI,32);
	CERI_VSYMI(ASYNC_SPD_SHI,4096);
	CERI_VSYMI(ASYNC_SPD_CUST,48);
	CERI_VSYMI(ASYNC_SPD_MASK,4144);
	CERI_VSYMI(TIOCGSERIAL,21534);
	CERI_VSYMI(TIOCSSERIAL,21535);
	printf("// CIoctl.Linux.serial_struct\n");
	CERI_VSIZE(struct serial_struct,72);
	
	printf("\n");
	printf("// CPoll\n");
	CERI_VSYMI(POLLIN,1);
	CERI_VSYMI(POLLPRI,2);
	CERI_VSYMI(POLLOUT,4);
	CERI_VSYMI(POLLERR,8);
	CERI_VSYMI(POLLHUP,16);
	CERI_VSYMI(POLLNVAL,32);
	printf("// CPoll.pollfd\n");
	CERI_VSIZE(struct pollfd,8);
	
	printf("\n");
	printf("// CSignal\n");
	CERI_VSYMI(SIGHUP,1);
	CERI_VSYMI(SIGINT,2);
	CERI_VSYMI(SIGQUIT,3);
	CERI_VSYMI(SIGILL,4);
	CERI_VSYMI(SIGTRAP,5);
	CERI_VSYMI(SIGABRT,6);
	CERI_VSYMI(SIGIOT,6);
	CERI_VSYMI(SIGBUS,7);
	CERI_VSYMI(SIGFPE,8);
	CERI_VSYMI(SIGKILL,9);
	CERI_VSYMI(SIGUSR1,10);
	CERI_VSYMI(SIGSEGV,11);
	CERI_VSYMI(SIGUSR2,12);
	CERI_VSYMI(SIGPIPE,13);
	CERI_VSYMI(SIGALRM,14);
	CERI_VSYMI(SIGTERM,15);
	CERI_VSYMI(SIGCHLD,17);
	CERI_VSYMI(SIGCONT,18);
	CERI_VSYMI(SIGSTOP,19);
	CERI_VSYMI(SIGTSTP,20);
	CERI_VSYMI(SIGTTIN,21);
	CERI_VSYMI(SIGTTOU,22);
	CERI_VSYMI(SIGURG,23);
	CERI_VSYMI(SIGXCPU,24);
	CERI_VSYMI(SIGXFSZ,25);
	CERI_VSYMI(SIGVTALRM,26);
	CERI_VSYMI(SIGPROF,27);
	CERI_VSYMI(SIGWINCH,28);
	CERI_VSYMI(SIGIO,29);
	CERI_VSYMI(SIGSYS,31);
	// Ignore: SIG_DFL = 0
	// Ignore: SIG_IGN = 1
	// Ignore: SIG_ERR = -1
	printf("// CSignal.sigset_t\n");
	CERI_VSIZE(sigset_t,128);
	
	printf("\n");
	printf("// CTermios\n");
	CERI_VSYMI(IGNBRK,1);
	CERI_VSYMI(BRKINT,2);
	CERI_VSYMI(IGNPAR,4);
	CERI_VSYMI(PARMRK,8);
	CERI_VSYMI(INPCK,16);
	CERI_VSYMI(ISTRIP,32);
	CERI_VSYMI(INLCR,64);
	CERI_VSYMI(IGNCR,128);
	CERI_VSYMI(ICRNL,256);
	CERI_VSYMI(IXON,1024);
	CERI_VSYMI(IXANY,2048);
	CERI_VSYMI(IXOFF,4096);
	CERI_VSYMI(IMAXBEL,8192);
	CERI_VSYMI(IUTF8,16384);
	CERI_VSYMI(OPOST,1);
	CERI_VSYMI(ONLCR,4);
	CERI_VSYMI(OCRNL,8);
	CERI_VSYMI(ONOCR,16);
	CERI_VSYMI(ONLRET,32);
	CERI_VSYMI(OFILL,64);
	CERI_VSYMI(OFDEL,128);
	CERI_VSYMI(CSIZE,48);
	CERI_VSYMI(CSTOPB,64);
	CERI_VSYMI(CREAD,128);
	CERI_VSYMI(PARENB,256);
	CERI_VSYMI(PARODD,512);
	CERI_VSYMI(HUPCL,1024);
	CERI_VSYMI(CLOCAL,2048);
	CERI_VSYMI(CMSPAR,1073741824);
	CERI_VSYMI(CRTSCTS,2147483648);
	CERI_VSYMI(CS5,0);
	CERI_VSYMI(CS6,16);
	CERI_VSYMI(CS7,32);
	CERI_VSYMI(CS8,48);
	CERI_VSYMI(ISIG,1);
	CERI_VSYMI(ICANON,2);
	CERI_VSYMI(ECHO,8);
	CERI_VSYMI(ECHOE,16);
	CERI_VSYMI(ECHOK,32);
	CERI_VSYMI(ECHONL,64);
	CERI_VSYMI(ECHOCTL,512);
	CERI_VSYMI(ECHOPRT,1024);
	CERI_VSYMI(ECHOKE,2048);
	CERI_VSYMI(NOFLSH,128);
	CERI_VSYMI(TOSTOP,256);
	CERI_VSYMI(IEXTEN,32768);
	CERI_VSYMI(VEOF,4);
	CERI_VSYMI(VEOL,11);
	CERI_VSYMI(VEOL2,16);
	CERI_VSYMI(VERASE,2);
	CERI_VSYMI(VINTR,0);
	CERI_VSYMI(VKILL,3);
	CERI_VSYMI(VLNEXT,15);
	CERI_VSYMI(VMIN,6);
	CERI_VSYMI(VQUIT,1);
	CERI_VSYMI(VREPRINT,12);
	CERI_VSYMI(VSTART,8);
	CERI_VSYMI(VSTOP,9);
	CERI_VSYMI(VSUSP,10);
	CERI_VSYMI(VTIME,5);
	CERI_VSYMI(VWERASE,14);
	CERI_VSYMI(TCSANOW,0);
	CERI_VSYMI(TCSADRAIN,1);
	CERI_VSYMI(TCSAFLUSH,2);
	CERI_VSYMI(TCIFLUSH,0);
	CERI_VSYMI(TCOFLUSH,1);
	CERI_VSYMI(TCIOFLUSH,2);
	CERI_VSYMI(TCOOFF,0);
	CERI_VSYMI(TCOON,1);
	CERI_VSYMI(TCIOFF,2);
	CERI_VSYMI(TCION,3);
	CERI_VSYMI(B0,0);
	CERI_VSYMI(B50,1);
	CERI_VSYMI(B75,2);
	CERI_VSYMI(B110,3);
	CERI_VSYMI(B134,4);
	CERI_VSYMI(B150,5);
	CERI_VSYMI(B200,6);
	CERI_VSYMI(B300,7);
	CERI_VSYMI(B600,8);
	CERI_VSYMI(B1200,9);
	CERI_VSYMI(B1800,10);
	CERI_VSYMI(B2400,11);
	CERI_VSYMI(B4800,12);
	CERI_VSYMI(B9600,13);
	CERI_VSYMI(B19200,14);
	CERI_VSYMI(B38400,15);
	CERI_VSYMI(B57600,4097);
	CERI_VSYMI(B115200,4098);
	CERI_VSYMI(B230400,4099);
	CERI_VSYMI(B460800,4100);
	CERI_VSYMI(B500000,4101);
	CERI_VSYMI(B576000,4102);
	CERI_VSYMI(B921600,4103);
	CERI_VSYMI(B1000000,4104);
	CERI_VSYMI(B1152000,4105);
	CERI_VSYMI(B1500000,4106);
	CERI_VSYMI(B2000000,4107);
	CERI_VSYMI(B2500000,4108);
	CERI_VSYMI(B3000000,4109);
	CERI_VSYMI(B3500000,4110);
	CERI_VSYMI(B4000000,4111);
	printf("// CTermios.Linux.termios\n");
	CERI_VSIZE(struct termios,60);
	printf("// CTermios.speed_t\n");
	CERI_VSIZE(speed_t,4);
	printf("// CTermios.tcflag_t\n");
	CERI_VSIZE(tcflag_t,4);
	
	printf("\n");
	printf("// CUnistd\n");
	CERI_VSYMI(STDIN_FILENO,0);
	CERI_VSYMI(STDOUT_FILENO,1);
	CERI_VSYMI(STDERR_FILENO,2);
	CERI_VSYMI(SEEK_SET,0);
	CERI_VSYMI(SEEK_CUR,1);
	CERI_VSYMI(SEEK_END,2);
	printf("// CUnistd.size_t\n");
	CERI_VSIZE(size_t,8);
	printf("// CUnistd.ssize_t\n");
	CERI_VSIZE(ssize_t,8);

	printf("\n");
	if (ceri_errors > 0) printf("[ERRORS: %d]\n", ceri_errors);
	if (ceri_undefineds > 0) printf("[undefined: %d]\n", ceri_undefineds);
	return 0;
}
