/*
 * Generated for mac by CSymbolGen (Mac OS X; aarch64; 15.5) 2025-07-02T17:59:07
 *
 * Build:  gcc clib-symbols-mac.c -o clib-symbols-mac; chmod a+x ./clib-symbols-mac
 *  Run:  ./clib-symbols-mac
 */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <IOKit/serial/ioss.h>
#include <poll.h>
#include <signal.h>
#include <termios.h>
#include <unistd.h>

#define CERI_STR(x) #x
#define CERI_SYM(x) ceri_print_symbol(#x,CERI_STR(x))
#define CERI_SYMI(x) ceri_print_symbol_i(#x,CERI_STR(x),x)
#define CERI_VSYMI(x,y) ceri_verify_symbol_i(#x,CERI_STR(x),x,y)
#define CERI_SIZE(t) ceri_print_symbol_i("sizeof("#t")","",sizeof(t))
#define CERI_FSIZE(t,f) ceri_print_symbol_i("sizeof("#t"."#f")","",(sizeof(((t*)0)->f)))
#define CERI_VSIZE(t,s) ceri_verify_symbol_i("sizeof("#t")","",sizeof(t),s)

int ceri_errors = 0;
int ceri_undefineds = 0;

void ceri_print_symbol(const char *name, const char *sym) {
	printf("%s = ", name);
	if (strlen(sym) == 0) printf("<defined>");
	else if (strcmp(name, sym) == 0) {
		printf("<undefined?>");
		ceri_undefineds++;
	} else printf("\"%s\"", sym);
	printf("\n");
}

void ceri_print_symbol_i(const char *name, const char *sym, long int isym) {
	printf("%s = ", name);
	if (isym > -10 && isym <  10) printf("%ld", isym);
	else printf("%1$ld|0x%1$lx", isym);
	if (strlen(sym) > 0) printf(" \"%s\"", sym);
	printf("\n");
}

void ceri_verify_symbol_i(const char *name, const char *sym, long int isym, long int iexpect) {
	if (isym < -0xffffffff) isym &= 0xffffffff;
	if (isym != iexpect) {
		printf("[ERROR] %1$ld|0x%1$lx != ", iexpect);
		ceri_errors++;
	}
	ceri_print_symbol_i(name, sym, isym);
}

int main(int argc, char *argv[]) {
	
	printf("\n");
	printf("// CErrNo\n");
	// Ignore: UNDEFINED = -1
	CERI_VSYMI(EPERM,1);
	CERI_VSYMI(ENOENT,2);
	CERI_VSYMI(ESRCH,3);
	CERI_VSYMI(EINTR,4);
	CERI_VSYMI(EIO,5);
	CERI_VSYMI(ENXIO,6);
	CERI_VSYMI(E2BIG,7);
	CERI_VSYMI(ENOEXEC,8);
	CERI_VSYMI(EBADF,9);
	CERI_VSYMI(ECHILD,10);
	CERI_VSYMI(EAGAIN,35);
	CERI_VSYMI(EWOULDBLOCK,35);
	CERI_VSYMI(ENOMEM,12);
	CERI_VSYMI(EACCES,13);
	CERI_VSYMI(EFAULT,14);
	CERI_VSYMI(ENOTBLK,15);
	CERI_VSYMI(EBUSY,16);
	CERI_VSYMI(EEXIST,17);
	CERI_VSYMI(EXDEV,18);
	CERI_VSYMI(ENODEV,19);
	CERI_VSYMI(ENOTDIR,20);
	CERI_VSYMI(EISDIR,21);
	CERI_VSYMI(EINVAL,22);
	CERI_VSYMI(ENFILE,23);
	CERI_VSYMI(EMFILE,24);
	CERI_VSYMI(ENOTTY,25);
	CERI_VSYMI(ETXTBSY,26);
	CERI_VSYMI(EFBIG,27);
	CERI_VSYMI(ENOSPC,28);
	CERI_VSYMI(ESPIPE,29);
	CERI_VSYMI(EROFS,30);
	CERI_VSYMI(EMLINK,31);
	CERI_VSYMI(EPIPE,32);
	CERI_VSYMI(EDOM,33);
	CERI_VSYMI(ERANGE,34);
	CERI_VSYMI(EDEADLK,11);
	CERI_VSYMI(ENAMETOOLONG,63);
	CERI_VSYMI(ENOLCK,77);
	CERI_VSYMI(ENOSYS,78);
	CERI_VSYMI(ENOTEMPTY,66);
	CERI_VSYMI(ELOOP,62);
	CERI_VSYMI(ENOMSG,91);
	CERI_VSYMI(EIDRM,90);
	// Ignore: ECHRNG = -1
	// Ignore: EL2NSYNC = -1
	// Ignore: EL3HLT = -1
	// Ignore: EL3RST = -1
	// Ignore: ELNRNG = -1
	// Ignore: EUNATCH = -1
	// Ignore: ENOCSI = -1
	// Ignore: EL2HLT = -1
	// Ignore: EBADE = -1
	// Ignore: EBADR = -1
	// Ignore: EXFULL = -1
	// Ignore: ENOANO = -1
	// Ignore: EBADRQC = -1
	// Ignore: EBADSLT = -1
	// Ignore: EBFONT = -1
	CERI_VSYMI(ENOSTR,99);
	CERI_VSYMI(ENODATA,96);
	CERI_VSYMI(ETIME,101);
	CERI_VSYMI(ENOSR,98);
	// Ignore: ENONET = -1
	// Ignore: ENOPKG = -1
	CERI_VSYMI(EREMOTE,71);
	CERI_VSYMI(ENOLINK,97);
	// Ignore: EADV = -1
	// Ignore: ESRMNT = -1
	// Ignore: ECOMM = -1
	CERI_VSYMI(EPROTO,100);
	CERI_VSYMI(EMULTIHOP,95);
	// Ignore: EDOTDOT = -1
	CERI_VSYMI(EBADMSG,94);
	CERI_VSYMI(EOVERFLOW,84);
	// Ignore: ENOTUNIQ = -1
	// Ignore: EBADFD = -1
	// Ignore: EREMCHG = -1
	// Ignore: ELIBACC = -1
	// Ignore: ELIBBAD = -1
	// Ignore: ELIBSCN = -1
	// Ignore: ELIBMAX = -1
	// Ignore: ELIBEXEC = -1
	CERI_VSYMI(EILSEQ,92);
	// Ignore: ERESTART = -1
	// Ignore: ESTRPIPE = -1
	CERI_VSYMI(EUSERS,68);
	CERI_VSYMI(ENOTSOCK,38);
	CERI_VSYMI(EDESTADDRREQ,39);
	CERI_VSYMI(EMSGSIZE,40);
	CERI_VSYMI(EPROTOTYPE,41);
	CERI_VSYMI(ENOPROTOOPT,42);
	CERI_VSYMI(EPROTONOSUPPORT,43);
	CERI_VSYMI(ESOCKTNOSUPPORT,44);
	CERI_VSYMI(EOPNOTSUPP,102);
	CERI_VSYMI(ENOTSUP,45);
	CERI_VSYMI(EPFNOSUPPORT,46);
	CERI_VSYMI(EAFNOSUPPORT,47);
	CERI_VSYMI(EADDRINUSE,48);
	CERI_VSYMI(EADDRNOTAVAIL,49);
	CERI_VSYMI(ENETDOWN,50);
	CERI_VSYMI(ENETUNREACH,51);
	CERI_VSYMI(ENETRESET,52);
	CERI_VSYMI(ECONNABORTED,53);
	CERI_VSYMI(ECONNRESET,54);
	CERI_VSYMI(ENOBUFS,55);
	CERI_VSYMI(EISCONN,56);
	CERI_VSYMI(ENOTCONN,57);
	CERI_VSYMI(ESHUTDOWN,58);
	CERI_VSYMI(ETOOMANYREFS,59);
	CERI_VSYMI(ETIMEDOUT,60);
	CERI_VSYMI(ECONNREFUSED,61);
	CERI_VSYMI(EHOSTDOWN,64);
	CERI_VSYMI(EHOSTUNREACH,65);
	CERI_VSYMI(EALREADY,37);
	CERI_VSYMI(EINPROGRESS,36);
	CERI_VSYMI(ESTALE,70);
	// Ignore: EUCLEAN = -1
	// Ignore: ENOTNAM = -1
	// Ignore: ENAVAIL = -1
	// Ignore: EISNAM = -1
	// Ignore: EREMOTEIO = -1
	CERI_VSYMI(EDQUOT,69);
	// Ignore: ENOMEDIUM = -1
	// Ignore: EMEDIUMTYPE = -1
	CERI_VSYMI(ECANCELED,89);
	// Ignore: ENOKEY = -1
	// Ignore: EKEYEXPIRED = -1
	// Ignore: EKEYREVOKED = -1
	// Ignore: EKEYREJECTED = -1
	CERI_VSYMI(EOWNERDEAD,105);
	CERI_VSYMI(ENOTRECOVERABLE,104);
	// Ignore: ERFKILL = -1
	// Ignore: EHWPOISON = -1
	CERI_VSYMI(EAUTH,80);
	CERI_VSYMI(EBADRPC,72);
	CERI_VSYMI(EFTYPE,79);
	CERI_VSYMI(ENEEDAUTH,81);
	CERI_VSYMI(ENOATTR,93);
	CERI_VSYMI(EPROCLIM,67);
	CERI_VSYMI(EPROCUNAVAIL,76);
	CERI_VSYMI(EPROGMISMATCH,75);
	CERI_VSYMI(EPROGUNAVAIL,74);
	CERI_VSYMI(ERPCMISMATCH,73);
	
	printf("\n");
	printf("// CFcntl\n");
	// Ignore: INVALID_FD = -1
	CERI_VSYMI(O_RDONLY,0);
	CERI_VSYMI(O_WRONLY,1);
	CERI_VSYMI(O_RDWR,2);
	CERI_VSYMI(O_ACCMODE,3);
	CERI_VSYMI(O_CREAT,512);
	CERI_VSYMI(O_EXCL,2048);
	CERI_VSYMI(O_NOCTTY,131072);
	CERI_VSYMI(O_TRUNC,1024);
	CERI_VSYMI(O_APPEND,8);
	CERI_VSYMI(O_NONBLOCK,4);
	CERI_VSYMI(O_DSYNC,4194304);
	CERI_VSYMI(O_ASYNC,64);
	CERI_VSYMI(O_DIRECTORY,1048576);
	CERI_VSYMI(O_NOFOLLOW,256);
	CERI_VSYMI(O_CLOEXEC,16777216);
	CERI_VSYMI(O_SYNC,128);
	CERI_VSYMI(F_DUPFD,0);
	CERI_VSYMI(F_GETFD,1);
	CERI_VSYMI(F_SETFD,2);
	CERI_VSYMI(F_GETFL,3);
	CERI_VSYMI(F_SETFL,4);
	
	printf("\n");
	printf("// CIoctl\n");
	// Ignore: _IOC_SIZEBITS = 13
	// Ignore: _IOC_SIZEMASK = 8191
	CERI_VSYMI(IOC_VOID,536870912); /* _IOC_NONE */
	CERI_VSYMI(IOC_OUT,1073741824);
	CERI_VSYMI(IOC_IN,2147483648);
	CERI_VSYMI(TIOCSBRK,536900731);
	CERI_VSYMI(TIOCCBRK,536900730);
	CERI_VSYMI(FIONREAD,1074030207);
	CERI_VSYMI(TIOCEXCL,536900621);
	CERI_VSYMI(TIOCOUTQ,1074033779);
	CERI_VSYMI(TIOCMGET,1074033770);
	CERI_VSYMI(TIOCMBIC,2147775595);
	CERI_VSYMI(TIOCMBIS,2147775596);
	CERI_VSYMI(TIOCMSET,2147775597);
	CERI_VSYMI(TIOCM_LE,1);
	CERI_VSYMI(TIOCM_DTR,2);
	CERI_VSYMI(TIOCM_RTS,4);
	CERI_VSYMI(TIOCM_CTS,32);
	CERI_VSYMI(TIOCM_CD,64);
	CERI_VSYMI(TIOCM_RI,128);
	CERI_VSYMI(TIOCM_DSR,256);
	printf("// CIoctl.Mac\n");
	CERI_VSYMI(IOSSIOSPEED,2148029442);
	
	printf("\n");
	printf("// CPoll\n");
	CERI_VSYMI(POLLIN,1);
	CERI_VSYMI(POLLPRI,2);
	CERI_VSYMI(POLLOUT,4);
	CERI_VSYMI(POLLERR,8);
	CERI_VSYMI(POLLHUP,16);
	CERI_VSYMI(POLLNVAL,32);
	printf("// CPoll.pollfd\n");
	CERI_VSIZE(struct pollfd,8);
	
	printf("\n");
	printf("// CSignal\n");
	CERI_VSYMI(SIGHUP,1);
	CERI_VSYMI(SIGINT,2);
	CERI_VSYMI(SIGQUIT,3);
	CERI_VSYMI(SIGILL,4);
	CERI_VSYMI(SIGTRAP,5);
	CERI_VSYMI(SIGABRT,6);
	CERI_VSYMI(SIGIOT,6);
	CERI_VSYMI(SIGBUS,10);
	CERI_VSYMI(SIGFPE,8);
	CERI_VSYMI(SIGKILL,9);
	CERI_VSYMI(SIGUSR1,30);
	CERI_VSYMI(SIGSEGV,11);
	CERI_VSYMI(SIGUSR2,31);
	CERI_VSYMI(SIGPIPE,13);
	CERI_VSYMI(SIGALRM,14);
	CERI_VSYMI(SIGTERM,15);
	CERI_VSYMI(SIGCHLD,20);
	CERI_VSYMI(SIGCONT,19);
	CERI_VSYMI(SIGSTOP,17);
	CERI_VSYMI(SIGTSTP,18);
	CERI_VSYMI(SIGTTIN,21);
	CERI_VSYMI(SIGTTOU,22);
	CERI_VSYMI(SIGURG,16);
	CERI_VSYMI(SIGXCPU,24);
	CERI_VSYMI(SIGXFSZ,25);
	CERI_VSYMI(SIGVTALRM,26);
	CERI_VSYMI(SIGPROF,27);
	CERI_VSYMI(SIGWINCH,28);
	CERI_VSYMI(SIGIO,23);
	CERI_VSYMI(SIGSYS,12);
	// Ignore: SIG_DFL = 0
	// Ignore: SIG_IGN = 1
	// Ignore: SIG_ERR = -1
	printf("// CSignal.sigset_t\n");
	CERI_VSIZE(sigset_t,4);
	
	printf("\n");
	printf("// CTermios\n");
	CERI_VSYMI(IGNBRK,1);
	CERI_VSYMI(BRKINT,2);
	CERI_VSYMI(IGNPAR,4);
	CERI_VSYMI(PARMRK,8);
	CERI_VSYMI(INPCK,16);
	CERI_VSYMI(ISTRIP,32);
	CERI_VSYMI(INLCR,64);
	CERI_VSYMI(IGNCR,128);
	CERI_VSYMI(ICRNL,256);
	CERI_VSYMI(IXON,512);
	CERI_VSYMI(IXANY,2048);
	CERI_VSYMI(IXOFF,1024);
	CERI_VSYMI(IMAXBEL,8192);
	CERI_VSYMI(IUTF8,16384);
	CERI_VSYMI(OPOST,1);
	CERI_VSYMI(ONLCR,2);
	CERI_VSYMI(OCRNL,16);
	CERI_VSYMI(ONOCR,32);
	CERI_VSYMI(ONLRET,64);
	CERI_VSYMI(OFILL,128);
	CERI_VSYMI(OFDEL,131072);
	CERI_VSYMI(CSIZE,768);
	CERI_VSYMI(CSTOPB,1024);
	CERI_VSYMI(CREAD,2048);
	CERI_VSYMI(PARENB,4096);
	CERI_VSYMI(PARODD,8192);
	CERI_VSYMI(HUPCL,16384);
	CERI_VSYMI(CLOCAL,32768);
	// Ignore: CMSPAR = 0
	CERI_VSYMI(CRTSCTS,196608);
	CERI_VSYMI(CS5,0);
	CERI_VSYMI(CS6,256);
	CERI_VSYMI(CS7,512);
	CERI_VSYMI(CS8,768);
	CERI_VSYMI(ISIG,128);
	CERI_VSYMI(ICANON,256);
	CERI_VSYMI(ECHO,8);
	CERI_VSYMI(ECHOE,2);
	CERI_VSYMI(ECHOK,4);
	CERI_VSYMI(ECHONL,16);
	CERI_VSYMI(ECHOCTL,64);
	CERI_VSYMI(ECHOPRT,32);
	CERI_VSYMI(ECHOKE,1);
	CERI_VSYMI(NOFLSH,2147483648);
	CERI_VSYMI(TOSTOP,4194304);
	CERI_VSYMI(IEXTEN,1024);
	CERI_VSYMI(VEOF,0);
	CERI_VSYMI(VEOL,1);
	CERI_VSYMI(VEOL2,2);
	CERI_VSYMI(VERASE,3);
	CERI_VSYMI(VINTR,8);
	CERI_VSYMI(VKILL,5);
	CERI_VSYMI(VLNEXT,14);
	CERI_VSYMI(VMIN,16);
	CERI_VSYMI(VQUIT,9);
	CERI_VSYMI(VREPRINT,6);
	CERI_VSYMI(VSTART,12);
	CERI_VSYMI(VSTOP,13);
	CERI_VSYMI(VSUSP,10);
	CERI_VSYMI(VTIME,17);
	CERI_VSYMI(VWERASE,4);
	CERI_VSYMI(TCSANOW,0);
	CERI_VSYMI(TCSADRAIN,1);
	CERI_VSYMI(TCSAFLUSH,2);
	CERI_VSYMI(TCIFLUSH,1);
	CERI_VSYMI(TCOFLUSH,2);
	CERI_VSYMI(TCIOFLUSH,3);
	CERI_VSYMI(TCOOFF,1);
	CERI_VSYMI(TCOON,2);
	CERI_VSYMI(TCIOFF,3);
	CERI_VSYMI(TCION,4);
	CERI_VSYMI(B0,0);
	CERI_VSYMI(B50,50);
	CERI_VSYMI(B75,75);
	CERI_VSYMI(B110,110);
	CERI_VSYMI(B134,134);
	CERI_VSYMI(B150,150);
	CERI_VSYMI(B200,200);
	CERI_VSYMI(B300,300);
	CERI_VSYMI(B600,600);
	CERI_VSYMI(B1200,1200);
	CERI_VSYMI(B1800,1800);
	CERI_VSYMI(B2400,2400);
	CERI_VSYMI(B4800,4800);
	CERI_VSYMI(B9600,9600);
	CERI_VSYMI(B19200,19200);
	CERI_VSYMI(B38400,38400);
	CERI_VSYMI(B57600,57600);
	CERI_VSYMI(B115200,115200);
	CERI_VSYMI(B230400,230400);
	// Ignore: B460800 = 460800
	// Ignore: B500000 = 500000
	// Ignore: B576000 = 576000
	// Ignore: B921600 = 921600
	// Ignore: B1000000 = 1000000
	// Ignore: B1152000 = 1152000
	// Ignore: B1500000 = 1500000
	// Ignore: B2000000 = 2000000
	// Ignore: B2500000 = 2500000
	// Ignore: B3000000 = 3000000
	// Ignore: B3500000 = 3500000
	// Ignore: B4000000 = 4000000
	printf("// CTermios.Mac.termios\n");
	CERI_VSIZE(struct termios,72);
	printf("// CTermios.speed_t\n");
	CERI_VSIZE(speed_t,8);
	printf("// CTermios.tcflag_t\n");
	CERI_VSIZE(tcflag_t,8);
	
	printf("\n");
	printf("// CUnistd\n");
	CERI_VSYMI(STDIN_FILENO,0);
	CERI_VSYMI(STDOUT_FILENO,1);
	CERI_VSYMI(STDERR_FILENO,2);
	CERI_VSYMI(SEEK_SET,0);
	CERI_VSYMI(SEEK_CUR,1);
	CERI_VSYMI(SEEK_END,2);
	printf("// CUnistd.size_t\n");
	CERI_VSIZE(size_t,8);
	printf("// CUnistd.ssize_t\n");
	CERI_VSIZE(ssize_t,8);

	printf("\n");
	if (ceri_errors > 0) printf("[ERRORS: %d]\n", ceri_errors);
	if (ceri_undefineds > 0) printf("[undefined: %d]\n", ceri_undefineds);
	return 0;
}
