#!/usr/bin/env bash
#------------------------------------------------------------------------------
# Find all header files; h-files* are ignored by git
#------------------------------------------------------------------------------
set -e

sudo find / -type f 2>/dev/null | grep '\.'h$
