package ceri.common;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import ceri.common.collection.ArrayIteratorBehavior;
import ceri.common.collection.ArrayUtilTest;
import ceri.common.collection.ByteProviderBehavior;
import ceri.common.collection.ByteReceiverBehavior;
import ceri.common.collection.CollectionUtilTest;
import ceri.common.collection.DelegatingMapBehavior;
import ceri.common.collection.FixedSizeCacheBehavior;
import ceri.common.collection.ImmutableByteArrayBehavior;
import ceri.common.collection.ImmutableIntArrayBehavior;
import ceri.common.collection.ImmutableUtilTest;
import ceri.common.collection.IndexedBehavior;
import ceri.common.collection.MapPopulatorBehavior;
import ceri.common.collection.StreamUtilTest;
import ceri.common.collection.WrappedIntStreamBehavior;
import ceri.common.collection.WrappedStreamBehavior;
import ceri.common.color.BiasesTest;
import ceri.common.color.ColorComparatorsTest;
import ceri.common.color.ColorUtilTest;
import ceri.common.color.ColorableTest;
import ceri.common.color.ColorxBehavior;
import ceri.common.color.ColorxComparatorsTest;
import ceri.common.color.ColorxUtilTest;
import ceri.common.color.ColorxableTest;
import ceri.common.color.CtColorBehavior;
import ceri.common.color.HsbColorBehavior;
import ceri.common.color.RgbColorBehavior;
import ceri.common.color.RgbxColorBehavior;
import ceri.common.color.X11ColorTest;
import ceri.common.color.XybColorBehavior;
import ceri.common.color.XyzColorBehavior;
import ceri.common.comparator.ComparatorSequenceBehavior;
import ceri.common.comparator.ComparatorsTest;
import ceri.common.comparator.EnumComparatorsTest;
import ceri.common.concurrent.AsyncRunnerBehavior;
import ceri.common.concurrent.AtomicByteArrayBehavior;
import ceri.common.concurrent.BooleanConditionBehavior;
import ceri.common.concurrent.ConcurrentUtilTest;
import ceri.common.concurrent.RuntimeInterruptedExceptionBehavior;
import ceri.common.concurrent.SafeReadWriteBehavior;
import ceri.common.concurrent.ValueConditionBehavior;
import ceri.common.data.BinaryStateBehavior;
import ceri.common.data.BooleanAccessorBehavior;
import ceri.common.data.ByteArrayDataInputBehavior;
import ceri.common.data.ByteArrayDataOutputBehavior;
import ceri.common.data.ByteTypeValueBehavior;
import ceri.common.data.ByteUtilTest;
import ceri.common.data.DataDecoderBehavior;
import ceri.common.data.DataEncoderBehavior;
import ceri.common.data.DataUtilTest;
import ceri.common.data.DecodingExceptionBehavior;
import ceri.common.data.FieldTranscoderBehavior;
import ceri.common.data.IntAccessorBehavior;
import ceri.common.data.IntBitSetBehavior;
import ceri.common.data.IntTypeValueBehavior;
import ceri.common.data.MaskTranscoderBehavior;
import ceri.common.data.ShortTypeValueBehavior;
import ceri.common.data.TypeTranscoderBehavior;
import ceri.common.data.UnexpectedValueExceptionBehavior;
import ceri.common.data.UnsignedOctetTypeBehavior;
import ceri.common.data.XorBehavior;
import ceri.common.date.CalendarFieldBehavior;
import ceri.common.date.DateUtilTest;
import ceri.common.date.HolidayBehavior;
import ceri.common.date.ImmutableDateBehavior;
import ceri.common.date.ImmutableTimeZoneBehavior;
import ceri.common.date.MultiDateParserBehavior;
import ceri.common.email.EmailUtilTest;
import ceri.common.event.CloseableIntListenerBehavior;
import ceri.common.event.CloseableListenerBehavior;
import ceri.common.event.EventTrackerBehavior;
import ceri.common.event.IntListenersBehavior;
import ceri.common.event.ListenersBehavior;
import ceri.common.event.NullIntListenableBehavior;
import ceri.common.event.NullListenableBehavior;
import ceri.common.factory.DateFactoriesTest;
import ceri.common.factory.FactoriesTest;
import ceri.common.factory.FactoryExceptionBehavior;
import ceri.common.factory.NumberFactoriesTest;
import ceri.common.factory.StringFactoriesTest;
import ceri.common.filter.CollectionFiltersTest;
import ceri.common.filter.EnumFiltersTest;
import ceri.common.filter.FilterBehavior;
import ceri.common.filter.FiltersTest;
import ceri.common.function.BooleanConsumerBehavior;
import ceri.common.function.ExceptionBiConsumerBehavior;
import ceri.common.function.ExceptionBiFunctionBehavior;
import ceri.common.function.ExceptionConsumerBehavior;
import ceri.common.function.ExceptionFunctionBehavior;
import ceri.common.function.ExceptionIntConsumerBehavior;
import ceri.common.function.ExceptionIntFunctionBehavior;
import ceri.common.function.ExceptionIntPredicateBehavior;
import ceri.common.function.ExceptionIntSupplierBehavior;
import ceri.common.function.ExceptionIntUnaryOperatorBehavior;
import ceri.common.function.ExceptionPredicateBehavior;
import ceri.common.function.ExceptionRunnableBehavior;
import ceri.common.function.ExceptionSupplierBehavior;
import ceri.common.function.ExceptionToIntFunctionBehavior;
import ceri.common.function.FunctionUtilTest;
import ceri.common.function.FunctionWrapperBehavior;
import ceri.common.function.NamedPredicateBuilderBehavior;
import ceri.common.function.ObjBooleanConsumerBehavior;
import ceri.common.function.ObjByteConsumerBehavior;
import ceri.common.function.ObjShortConsumerBehavior;
import ceri.common.function.ToByteFunctionBehavior;
import ceri.common.function.ToShortFunctionBehavior;
import ceri.common.geo.LatLngBehavior;
import ceri.common.geo.LatLngUtilTest;
import ceri.common.geom.Circle2dBehavior;
import ceri.common.geom.ConcaveSpheroidBehavior;
import ceri.common.geom.Cone3dBehavior;
import ceri.common.geom.Cylinder3dBehavior;
import ceri.common.geom.Dimension2dBehavior;
import ceri.common.geom.Ellipse2dBehavior;
import ceri.common.geom.Ellipsoid3dBehavior;
import ceri.common.geom.GeometryUtilTest;
import ceri.common.geom.InvertedRadial3dBehavior;
import ceri.common.geom.Line2dBehavior;
import ceri.common.geom.Line2dEquationBehavior;
import ceri.common.geom.LineUtilTest;
import ceri.common.geom.Point2dBehavior;
import ceri.common.geom.Polar2dBehavior;
import ceri.common.geom.Radial3dBehavior;
import ceri.common.geom.Ratio2dBehavior;
import ceri.common.geom.Rectangle2dBehavior;
import ceri.common.geom.Shape3dUtilTest;
import ceri.common.geom.Spheroid3dBehavior;
import ceri.common.geom.TruncatedRadial3dBehavior;
import ceri.common.io.BitIteratorBehavior;
import ceri.common.io.BlockingBufferStreamBehavior;
import ceri.common.io.ByteBufferStreamBehavior;
import ceri.common.io.CloseableWrapperBehavior;
import ceri.common.io.FileFiltersTest;
import ceri.common.io.FileIteratorBehavior;
import ceri.common.io.FileTrackerBehavior;
import ceri.common.io.FilenameIteratorBehavior;
import ceri.common.io.InputStreamIteratorBehavior;
import ceri.common.io.IoStreamUtilTest;
import ceri.common.io.IoTimeoutExceptionBehavior;
import ceri.common.io.IoUtilTest;
import ceri.common.io.KeyCheckerBehavior;
import ceri.common.io.PollingInputStreamBehavior;
import ceri.common.io.RegexFilenameFilterBehavior;
import ceri.common.io.ReplaceableInputStreamBehavior;
import ceri.common.io.ReplaceableOutputStreamBehavior;
import ceri.common.io.ResourceListerBehavior;
import ceri.common.io.RuntimeIoExceptionBehavior;
import ceri.common.io.StateChangeBehavior;
import ceri.common.io.StringPrintStreamBehavior;
import ceri.common.math.AlgebraUtilTest;
import ceri.common.math.BoundBehavior;
import ceri.common.math.FractionBehavior;
import ceri.common.math.IntervalBehavior;
import ceri.common.math.IntervalUtilTest;
import ceri.common.math.MathUtilTest;
import ceri.common.math.MatrixBehavior;
import ceri.common.math.MatrixUtilTest;
import ceri.common.math.MixedFractionBehavior;
import ceri.common.math.NumberPatternsBehavior;
import ceri.common.math.ReverseFunctionBehavior;
import ceri.common.math.TrigUtilTest;
import ceri.common.math.VectorBehavior;
import ceri.common.math.VectorUtilTest;
import ceri.common.net.HostPortBehavior;
import ceri.common.net.NetUtilTest;
import ceri.common.net.UdpUtilTest;
import ceri.common.property.BasePropertiesBehavior;
import ceri.common.property.LocatorBehavior;
import ceri.common.property.PathBehavior;
import ceri.common.property.PathFactoryBehavior;
import ceri.common.property.PropertyAccessorBehavior;
import ceri.common.property.PropertyUtilTest;
import ceri.common.reflect.CallerBehavior;
import ceri.common.reflect.CreateExceptionBehavior;
import ceri.common.reflect.ReflectUtilTest;
import ceri.common.score.CollectionScorersTest;
import ceri.common.score.ScoreLookupBehavior;
import ceri.common.score.ScoreResultBehavior;
import ceri.common.score.ScorersTest;
import ceri.common.sql.SqlFormatterBehavior;
import ceri.common.svg.EllipseBehavior;
import ceri.common.svg.EllipticalArcBehavior;
import ceri.common.svg.GroundedPathBehavior;
import ceri.common.svg.LargeArcFlagBehavior;
import ceri.common.svg.LineToBehavior;
import ceri.common.svg.MoveToBehavior;
import ceri.common.svg.PathGroupBehavior;
import ceri.common.svg.PositionBehavior;
import ceri.common.svg.SvgUtilTest;
import ceri.common.svg.SweepFlagBehavior;
import ceri.common.test.BinaryLogInputStreamBehavior;
import ceri.common.test.BinaryLogOutputStreamBehavior;
import ceri.common.test.BinaryPrinterBehavior;
import ceri.common.test.DebuggerBehavior;
import ceri.common.test.FileTestHelperBehavior;
import ceri.common.test.PulsePrinterBehavior;
import ceri.common.test.RegexMatcherBehavior;
import ceri.common.test.ResponseStreamBehavior;
import ceri.common.test.TestPrinterBehavior;
import ceri.common.test.TestRunAdapterBehavior;
import ceri.common.test.TestRunPrinterBehavior;
import ceri.common.test.TestStateBehavior;
import ceri.common.test.TestStyleBehavior;
import ceri.common.test.TestThreadBehavior;
import ceri.common.test.TestTimerBehavior;
import ceri.common.test.TestUtil;
import ceri.common.test.TestUtilTest;
import ceri.common.text.DsvCodecBehavior;
import ceri.common.text.DsvParserBehavior;
import ceri.common.text.FractionFormatsTest;
import ceri.common.text.MarshallerBehavior;
import ceri.common.text.RegexSequencerBehavior;
import ceri.common.text.RegexUtilTest;
import ceri.common.text.StringTypeBehavior;
import ceri.common.text.StringUtilTest;
import ceri.common.text.TextUtilTest;
import ceri.common.text.ToStringHelperBehavior;
import ceri.common.text.Utf8UtilTest;
import ceri.common.tree.NodeTreeBehavior;
import ceri.common.tree.TreeIteratorBehavior;
import ceri.common.tree.TreeNodeBehavior;
import ceri.common.tree.TreeNodeComparatorsTest;
import ceri.common.tree.TreeUtilTest;
import ceri.common.util.BasicUtilTest;
import ceri.common.util.EqualsUtilTest;
import ceri.common.util.ExceptionAdapterBehavior;
import ceri.common.util.ExceptionTrackerBehavior;
import ceri.common.util.HashCoderBehavior;
import ceri.common.util.HolderBehavior;
import ceri.common.util.KeyValueBehavior;
import ceri.common.util.LocaleUtilTest;
import ceri.common.util.MultiPatternBehavior;
import ceri.common.util.NameValueBehavior;
import ceri.common.util.OsUtilTest;
import ceri.common.util.PrimitiveUtilTest;
import ceri.common.util.StartupValuesBehavior;
import ceri.common.util.TimerBehavior;
import ceri.common.validation.ValidationUtilTest;
import ceri.common.xml.RuntimeXPathExceptionBehavior;
import ceri.common.xml.XPathUtilTest;
import ceri.common.xml.XmlUtilTest;

/**
 * Generated test suite for ceri-common
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
	// collection
	ArrayIteratorBehavior.class, //
	ArrayUtilTest.class, //
	ByteProviderBehavior.class, //
	ByteReceiverBehavior.class, //
	CollectionUtilTest.class, //
	DelegatingMapBehavior.class, //
	FixedSizeCacheBehavior.class, //
	ImmutableByteArrayBehavior.class, //
	ImmutableIntArrayBehavior.class, //
	ImmutableUtilTest.class, //
	IndexedBehavior.class, //
	MapPopulatorBehavior.class, //
	StreamUtilTest.class, //
	WrappedIntStreamBehavior.class, //
	WrappedStreamBehavior.class, //
	// color
	BiasesTest.class, //
	ColorComparatorsTest.class, //
	ColorUtilTest.class, //
	ColorableTest.class, //
	ColorxBehavior.class, //
	ColorxComparatorsTest.class, //
	ColorxUtilTest.class, //
	ColorxableTest.class, //
	CtColorBehavior.class, //
	HsbColorBehavior.class, //
	RgbColorBehavior.class, //
	RgbxColorBehavior.class, //
	X11ColorTest.class, //
	XybColorBehavior.class, //
	XyzColorBehavior.class, //
	// comparator
	ComparatorSequenceBehavior.class, //
	ComparatorsTest.class, //
	EnumComparatorsTest.class, //
	// concurrent
	AsyncRunnerBehavior.class, //
	AtomicByteArrayBehavior.class, //
	BooleanConditionBehavior.class, //
	ConcurrentUtilTest.class, //
	RuntimeInterruptedExceptionBehavior.class, //
	SafeReadWriteBehavior.class, //
	ValueConditionBehavior.class, //
	// data
	BinaryStateBehavior.class, //
	BooleanAccessorBehavior.class, //
	ByteArrayDataInputBehavior.class, //
	ByteArrayDataOutputBehavior.class, //
	ByteTypeValueBehavior.class, //
	ByteUtilTest.class, //
	DataDecoderBehavior.class, //
	DataEncoderBehavior.class, //
	DataUtilTest.class, //
	DecodingExceptionBehavior.class, //
	FieldTranscoderBehavior.class, //
	IntAccessorBehavior.class, //
	IntBitSetBehavior.class, //
	IntTypeValueBehavior.class, //
	MaskTranscoderBehavior.class, //
	ShortTypeValueBehavior.class, //
	TypeTranscoderBehavior.class, //
	UnexpectedValueExceptionBehavior.class, //
	UnsignedOctetTypeBehavior.class, //
	XorBehavior.class, //
	// date
	CalendarFieldBehavior.class, //
	DateUtilTest.class, //
	HolidayBehavior.class, //
	ImmutableDateBehavior.class, //
	ImmutableTimeZoneBehavior.class, //
	MultiDateParserBehavior.class, //
	// email
	EmailUtilTest.class, //
	// event
	CloseableIntListenerBehavior.class, //
	CloseableListenerBehavior.class, //
	EventTrackerBehavior.class, //
	IntListenersBehavior.class, //
	ListenersBehavior.class, //
	NullIntListenableBehavior.class, //
	NullListenableBehavior.class, //
	// factory
	DateFactoriesTest.class, //
	FactoriesTest.class, //
	FactoryExceptionBehavior.class, //
	NumberFactoriesTest.class, //
	StringFactoriesTest.class, //
	// filter
	CollectionFiltersTest.class, //
	EnumFiltersTest.class, //
	FilterBehavior.class, //
	FiltersTest.class, //
	// function
	BooleanConsumerBehavior.class, //
	ExceptionBiConsumerBehavior.class, //
	ExceptionBiFunctionBehavior.class, //
	ExceptionConsumerBehavior.class, //
	ExceptionFunctionBehavior.class, //
	ExceptionIntConsumerBehavior.class, //
	ExceptionIntFunctionBehavior.class, //
	ExceptionIntPredicateBehavior.class, //
	ExceptionIntSupplierBehavior.class, //
	ExceptionIntUnaryOperatorBehavior.class, //
	ExceptionPredicateBehavior.class, //
	ExceptionRunnableBehavior.class, //
	ExceptionSupplierBehavior.class, //
	ExceptionToIntFunctionBehavior.class, //
	FunctionUtilTest.class, //
	FunctionWrapperBehavior.class, //
	NamedPredicateBuilderBehavior.class, //
	ObjBooleanConsumerBehavior.class, //
	ObjByteConsumerBehavior.class, //
	ObjShortConsumerBehavior.class, //
	ToByteFunctionBehavior.class, //
	ToShortFunctionBehavior.class, //
	// geo
	LatLngBehavior.class, //
	LatLngUtilTest.class, //
	// geom
	Circle2dBehavior.class, //
	ConcaveSpheroidBehavior.class, //
	Cone3dBehavior.class, //
	Cylinder3dBehavior.class, //
	Dimension2dBehavior.class, //
	Ellipse2dBehavior.class, //
	Ellipsoid3dBehavior.class, //
	GeometryUtilTest.class, //
	InvertedRadial3dBehavior.class, //
	Line2dBehavior.class, //
	Line2dEquationBehavior.class, //
	LineUtilTest.class, //
	Point2dBehavior.class, //
	Polar2dBehavior.class, //
	Radial3dBehavior.class, //
	Ratio2dBehavior.class, //
	Rectangle2dBehavior.class, //
	Shape3dUtilTest.class, //
	Spheroid3dBehavior.class, //
	TruncatedRadial3dBehavior.class, //
	// io
	BitIteratorBehavior.class, //
	BlockingBufferStreamBehavior.class, //
	ByteBufferStreamBehavior.class, //
	CloseableWrapperBehavior.class, //
	FileFiltersTest.class, //
	FileIteratorBehavior.class, //
	FileTrackerBehavior.class, //
	FilenameIteratorBehavior.class, //
	InputStreamIteratorBehavior.class, //
	IoStreamUtilTest.class, //
	IoTimeoutExceptionBehavior.class, //
	IoUtilTest.class, //
	KeyCheckerBehavior.class, //
	PollingInputStreamBehavior.class, //
	RegexFilenameFilterBehavior.class, //
	ReplaceableInputStreamBehavior.class, //
	ReplaceableOutputStreamBehavior.class, //
	ResourceListerBehavior.class, //
	RuntimeIoExceptionBehavior.class, //
	StateChangeBehavior.class, //
	StringPrintStreamBehavior.class, //
	// math
	AlgebraUtilTest.class, //
	BoundBehavior.class, //
	FractionBehavior.class, //
	IntervalBehavior.class, //
	IntervalUtilTest.class, //
	MathUtilTest.class, //
	MatrixBehavior.class, //
	MatrixUtilTest.class, //
	MixedFractionBehavior.class, //
	NumberPatternsBehavior.class, //
	ReverseFunctionBehavior.class, //
	TrigUtilTest.class, //
	VectorBehavior.class, //
	VectorUtilTest.class, //
	// net
	HostPortBehavior.class, //
	NetUtilTest.class, //
	UdpUtilTest.class, //
	// property
	BasePropertiesBehavior.class, //
	LocatorBehavior.class, //
	PathBehavior.class, //
	PathFactoryBehavior.class, //
	PropertyAccessorBehavior.class, //
	PropertyUtilTest.class, //
	// reflect
	CallerBehavior.class, //
	CreateExceptionBehavior.class, //
	ReflectUtilTest.class, //
	// score
	CollectionScorersTest.class, //
	ScoreLookupBehavior.class, //
	ScoreResultBehavior.class, //
	ScorersTest.class, //
	// sql
	SqlFormatterBehavior.class, //
	// svg
	EllipseBehavior.class, //
	EllipticalArcBehavior.class, //
	GroundedPathBehavior.class, //
	LargeArcFlagBehavior.class, //
	LineToBehavior.class, //
	MoveToBehavior.class, //
	PathGroupBehavior.class, //
	PositionBehavior.class, //
	SvgUtilTest.class, //
	SweepFlagBehavior.class, //
	// test
	BinaryLogInputStreamBehavior.class, //
	BinaryLogOutputStreamBehavior.class, //
	BinaryPrinterBehavior.class, //
	DebuggerBehavior.class, //
	FileTestHelperBehavior.class, //
	PulsePrinterBehavior.class, //
	RegexMatcherBehavior.class, //
	ResponseStreamBehavior.class, //
	TestPrinterBehavior.class, //
	TestRunAdapterBehavior.class, //
	TestRunPrinterBehavior.class, //
	TestStateBehavior.class, //
	TestStyleBehavior.class, //
	TestThreadBehavior.class, //
	TestTimerBehavior.class, //
	TestUtilTest.class, //
	// text
	DsvCodecBehavior.class, //
	DsvParserBehavior.class, //
	FractionFormatsTest.class, //
	MarshallerBehavior.class, //
	RegexSequencerBehavior.class, //
	RegexUtilTest.class, //
	StringTypeBehavior.class, //
	StringUtilTest.class, //
	TextUtilTest.class, //
	ToStringHelperBehavior.class, //
	Utf8UtilTest.class, //
	// tree
	NodeTreeBehavior.class, //
	TreeIteratorBehavior.class, //
	TreeNodeBehavior.class, //
	TreeNodeComparatorsTest.class, //
	TreeUtilTest.class, //
	// util
	BasicUtilTest.class, //
	EqualsUtilTest.class, //
	ExceptionAdapterBehavior.class, //
	ExceptionTrackerBehavior.class, //
	HashCoderBehavior.class, //
	HolderBehavior.class, //
	KeyValueBehavior.class, //
	LocaleUtilTest.class, //
	MultiPatternBehavior.class, //
	NameValueBehavior.class, //
	OsUtilTest.class, //
	PrimitiveUtilTest.class, //
	StartupValuesBehavior.class, //
	TimerBehavior.class, //
	// validation
	ValidationUtilTest.class, //
	// xml
	RuntimeXPathExceptionBehavior.class, //
	XPathUtilTest.class, //
	XmlUtilTest.class, //
})
public class _Tests {
	public static void main(String... args) {
		TestUtil.exec(_Tests.class);
	}
}
