package ceri.common;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import ceri.common.collection.*;
import ceri.common.color.*;
import ceri.common.comparator.ComparatorSequenceBehavior;
import ceri.common.comparator.ComparatorsTest;
import ceri.common.comparator.EnumComparatorsTest;
import ceri.common.concurrent.*;
import ceri.common.data.*;
import ceri.common.date.*;
import ceri.common.email.EmailUtilTest;
import ceri.common.event.*;
import ceri.common.factory.*;
import ceri.common.filter.CollectionFiltersTest;
import ceri.common.filter.EnumFiltersTest;
import ceri.common.filter.FilterBehavior;
import ceri.common.filter.FiltersTest;
import ceri.common.function.*;
import ceri.common.geo.LatLngBehavior;
import ceri.common.geo.LatLngUtilTest;
import ceri.common.geom.*;
import ceri.common.io.*;
import ceri.common.math.*;
import ceri.common.net.HostPortBehavior;
import ceri.common.net.NetUtilTest;
import ceri.common.net.UdpUtilTest;
import ceri.common.property.*;
import ceri.common.reflect.CallerBehavior;
import ceri.common.reflect.CreateExceptionBehavior;
import ceri.common.reflect.ReflectUtilTest;
import ceri.common.score.CollectionScorersTest;
import ceri.common.score.ScoreLookupBehavior;
import ceri.common.score.ScoreResultBehavior;
import ceri.common.score.ScorersTest;
import ceri.common.svg.*;
import ceri.common.test.*;
import ceri.common.text.*;
import ceri.common.tree.*;
import ceri.common.util.*;
import ceri.common.validation.ValidationUtilTest;
import ceri.common.xml.RuntimeXPathExceptionBehavior;
import ceri.common.xml.XPathUtilTest;
import ceri.common.xml.XmlUtilTest;

/**
 * Generated test suite for ceri-common
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
	// collection
	ArrayIteratorBehavior.class, //
	ArrayUtilTest.class, //
	ByteProviderBehavior.class, //
	ByteReceiverBehavior.class, //
	CollectionUtilTest.class, //
	DelegatingMapBehavior.class, //
	FixedSizeCacheBehavior.class, //
	ImmutableByteArrayBehavior.class, //
	ImmutableIntArrayBehavior.class, //
	ImmutableUtilTest.class, //
	MapPopulatorBehavior.class, //
	StreamUtilTest.class, //
	// color
	BiasesTest.class, //
	ColorComparatorsTest.class, //
	ColorUtilTest.class, //
	ColorableTest.class, //
	ColorxBehavior.class, //
	ColorxComparatorsTest.class, //
	ColorxUtilTest.class, //
	ColorxableTest.class, //
	CtColorBehavior.class, //
	HsbColorBehavior.class, //
	RgbColorBehavior.class, //
	RgbxColorBehavior.class, //
	X11ColorTest.class, //
	XybColorBehavior.class, //
	XyzColorBehavior.class, //
	// comparator
	ComparatorSequenceBehavior.class, //
	ComparatorsTest.class, //
	EnumComparatorsTest.class, //
	// concurrent
	AsyncRunnerBehavior.class, //
	AtomicByteArrayBehavior.class, //
	BooleanConditionBehavior.class, //
	ConcurrentUtilTest.class, //
	RuntimeInterruptedExceptionBehavior.class, //
	SafeReadWriteBehavior.class, //
	ValueConditionBehavior.class, //
	// data
	BinaryStateBehavior.class, //
	BooleanAccessorBehavior.class, //
	ByteArrayDataInputBehavior.class, //
	ByteArrayDataOutputBehavior.class, //
	ByteTypeValueBehavior.class, //
	ByteUtilTest.class, //
	DataDecoderBehavior.class, //
	DataEncoderBehavior.class, //
	DataUtilTest.class, //
	DecodingExceptionBehavior.class, //
	FieldTranscoderBehavior.class, //
	IntAccessorBehavior.class, //
	IntBitSetBehavior.class, //
	IntTypeValueBehavior.class, //
	MaskTranscoderBehavior.class, //
	ShortTypeValueBehavior.class, //
	TypeTranscoderBehavior.class, //
	UnexpectedValueExceptionBehavior.class, //
	UnsignedOctetTypeBehavior.class, //
	XorBehavior.class, //
	// date
	CalendarFieldBehavior.class, //
	DateUtilTest.class, //
	HolidayBehavior.class, //
	ImmutableDateBehavior.class, //
	ImmutableTimeZoneBehavior.class, //
	MultiDateParserBehavior.class, //
	// email
	EmailUtilTest.class, //
	// event
	CloseableIntListenerBehavior.class, //
	CloseableListenerBehavior.class, //
	EventTrackerBehavior.class, //
	IntListenersBehavior.class, //
	ListenersBehavior.class, //
	NullIntListenableBehavior.class, //
	NullListenableBehavior.class, //
	// factory
	DateFactoriesTest.class, //
	FactoriesTest.class, //
	FactoryExceptionBehavior.class, //
	NumberFactoriesTest.class, //
	StringFactoriesTest.class, //
	// filter
	CollectionFiltersTest.class, //
	EnumFiltersTest.class, //
	FilterBehavior.class, //
	FiltersTest.class, //
	// function
	BooleanConsumerBehavior.class, //
	ExceptionBiConsumerBehavior.class, //
	ExceptionBiFunctionBehavior.class, //
	ExceptionConsumerBehavior.class, //
	ExceptionFunctionBehavior.class, //
	ExceptionPredicateBehavior.class, //
	ExceptionRunnableBehavior.class, //
	ExceptionSupplierBehavior.class, //
	FunctionUtilTest.class, //
	FunctionWrapperBehavior.class, //
	ObjBooleanConsumerBehavior.class, //
	ObjByteConsumerBehavior.class, //
	ObjShortConsumerBehavior.class, //
	PredicateBuilderBehavior.class, //
	ToByteFunctionBehavior.class, //
	ToShortFunctionBehavior.class, //
	WrapperExceptionBehavior.class, //
	// geo
	LatLngBehavior.class, //
	LatLngUtilTest.class, //
	// geom
	Circle2dBehavior.class, //
	ConcaveSpheroidBehavior.class, //
	Cone3dBehavior.class, //
	Cylinder3dBehavior.class, //
	Dimension2dBehavior.class, //
	Ellipse2dBehavior.class, //
	Ellipsoid3dBehavior.class, //
	GeometryUtilTest.class, //
	InvertedRadial3dBehavior.class, //
	Line2dBehavior.class, //
	Line2dEquationBehavior.class, //
	LineUtilTest.class, //
	Point2dBehavior.class, //
	Polar2dBehavior.class, //
	Radial3dBehavior.class, //
	Ratio2dBehavior.class, //
	Rectangle2dBehavior.class, //
	Shape3dUtilTest.class, //
	Spheroid3dBehavior.class, //
	TruncatedRadial3dBehavior.class, //
	// io
	BitIteratorBehavior.class, //
	BlockingBufferStreamBehavior.class, //
	ByteBufferStreamBehavior.class, //
	CloseableWrapperBehavior.class, //
	FileFiltersTest.class, //
	FileIteratorBehavior.class, //
	FileTrackerBehavior.class, //
	FilenameIteratorBehavior.class, //
	InputStreamIteratorBehavior.class, //
	IoStreamUtilTest.class, //
	IoTimeoutExceptionBehavior.class, //
	IoUtilTest.class, //
	KeyCheckerBehavior.class, //
	PollingInputStreamBehavior.class, //
	RegexFilenameFilterBehavior.class, //
	ReplaceableInputStreamBehavior.class, //
	ReplaceableOutputStreamBehavior.class, //
	ResourceListerBehavior.class, //
	RuntimeIoExceptionBehavior.class, //
	StateChangeBehavior.class, //
	StringPrintStreamBehavior.class, //
	// math
	AlgebraUtilTest.class, //
	BoundBehavior.class, //
	FractionBehavior.class, //
	IntervalBehavior.class, //
	IntervalUtilTest.class, //
	MathUtilTest.class, //
	MatrixBehavior.class, //
	MatrixUtilTest.class, //
	MixedFractionBehavior.class, //
	NumberPatternsBehavior.class, //
	ReverseFunctionBehavior.class, //
	TrigUtilTest.class, //
	VectorBehavior.class, //
	VectorUtilTest.class, //
	// net
	HostPortBehavior.class, //
	NetUtilTest.class, //
	UdpUtilTest.class, //
	// property
	BasePropertiesBehavior.class, //
	LocatorBehavior.class, //
	PathBehavior.class, //
	PathFactoryBehavior.class, //
	PropertyAccessorBehavior.class, //
	PropertyUtilTest.class, //
	// reflect
	CallerBehavior.class, //
	CreateExceptionBehavior.class, //
	ReflectUtilTest.class, //
	// score
	CollectionScorersTest.class, //
	ScoreLookupBehavior.class, //
	ScoreResultBehavior.class, //
	ScorersTest.class, //
	// svg
	EllipseBehavior.class, //
	EllipticalArcBehavior.class, //
	GroundedPathBehavior.class, //
	LargeArcFlagBehavior.class, //
	LineToBehavior.class, //
	MoveToBehavior.class, //
	PathGroupBehavior.class, //
	PositionBehavior.class, //
	SvgUtilTest.class, //
	SweepFlagBehavior.class, //
	// test
	BinaryLogInputStreamBehavior.class, //
	BinaryLogOutputStreamBehavior.class, //
	BinaryPrinterBehavior.class, //
	DebuggerBehavior.class, //
	PulsePrinterBehavior.class, //
	RegexMatcherBehavior.class, //
	ResponseStreamBehavior.class, //
	TestPrinterBehavior.class, //
	TestRunAdapterBehavior.class, //
	TestRunPrinterBehavior.class, //
	TestStateBehavior.class, //
	TestThreadBehavior.class, //
	TestTimerBehavior.class, //
	TestUtilTest.class, //
	// text
	DsvCodecBehavior.class, //
	DsvParserBehavior.class, //
	FractionFormatsTest.class, //
	MarshallerBehavior.class, //
	RegexSequencerBehavior.class, //
	RegexUtilTest.class, //
	StringUtilTest.class, //
	TextUtilTest.class, //
	ToStringHelperBehavior.class, //
	Utf8UtilTest.class, //
	// tree
	NodeTreeBehavior.class, //
	TreeIteratorBehavior.class, //
	TreeNodeBehavior.class, //
	TreeNodeComparatorsTest.class, //
	TreeUtilTest.class, //
	// util
	BasicUtilTest.class, //
	EqualsUtilTest.class, //
	ExceptionTrackerBehavior.class, //
	HashCoderBehavior.class, //
	HolderBehavior.class, //
	KeyValueBehavior.class, //
	LocaleUtilTest.class, //
	MultiPatternBehavior.class, //
	NameValueBehavior.class, //
	OsUtilTest.class, //
	PrimitiveUtilTest.class, //
	StartupValuesBehavior.class, //
	TimerBehavior.class, //
	// validation
	ValidationUtilTest.class, //
	// xml
	RuntimeXPathExceptionBehavior.class, //
	XPathUtilTest.class, //
	XmlUtilTest.class, //
})
public class _Tests {
	public static void main(String... args) {
		TestUtil.exec(_Tests.class);
	}
}
