package ceri.common;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import ceri.common.test.TestUtil;

/**
 * Generated test suite for ceri-common
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
	// collection
	ceri.common.collection.ArrayUtilTest.class, //
	ceri.common.collection.BiMapBehavior.class, //
	ceri.common.collection.CollectionUtilTest.class, //
	ceri.common.collection.FixedSizeCacheBehavior.class, //
	ceri.common.collection.ImmutableUtilTest.class, //
	ceri.common.collection.IndexedBehavior.class, //
	ceri.common.collection.IteratorsTest.class, //
	ceri.common.collection.MapPopulatorBehavior.class, //
	ceri.common.collection.NodeBehavior.class, //
	ceri.common.collection.StreamUtilTest.class, //
	ceri.common.collection.SubArrayBehavior.class, //
	ceri.common.collection.TypedPipeBehavior.class, //
	ceri.common.collection.WrappedIntStreamBehavior.class, //
	ceri.common.collection.WrappedStreamBehavior.class, //
	// color
	ceri.common.color.BiasTest.class, //
	ceri.common.color.ColorComparatorsTest.class, //
	ceri.common.color.ColorSpacesTest.class, //
	ceri.common.color.ColorUtilTest.class, //
	ceri.common.color.ColorableTest.class, //
	ceri.common.color.ColorsTest.class, //
	ceri.common.color.ColorxBehavior.class, //
	ceri.common.color.ColorxComparatorsTest.class, //
	ceri.common.color.ColorxUtilTest.class, //
	ceri.common.color.ColorxableTest.class, //
	ceri.common.color.ComponentBehavior.class, //
	ceri.common.color.GrayCharBehavior.class, //
	ceri.common.color.HsbColorBehavior.class, //
	ceri.common.color.LuvColorBehavior.class, //
	ceri.common.color.RgbColorBehavior.class, //
	ceri.common.color.XybColorBehavior.class, //
	ceri.common.color.XyzColorBehavior.class, //
	// comparator
	ceri.common.comparator.ComparatorSequenceBehavior.class, //
	ceri.common.comparator.ComparatorsTest.class, //
	ceri.common.comparator.EnumComparatorsTest.class, //
	// concurrent
	ceri.common.concurrent.BooleanConditionBehavior.class, //
	ceri.common.concurrent.ConcurrentUtilTest.class, //
	ceri.common.concurrent.RuntimeInterruptedExceptionBehavior.class, //
	ceri.common.concurrent.SafeReadWriteBehavior.class, //
	ceri.common.concurrent.SimpleExecutorBehavior.class, //
	ceri.common.concurrent.TaskQueueBehavior.class, //
	ceri.common.concurrent.ValueConditionBehavior.class, //
	ceri.common.concurrent.VolatileByteArrayBehavior.class, //
	// data
	ceri.common.data.BinaryStateBehavior.class, //
	ceri.common.data.BooleanAccessorBehavior.class, //
	ceri.common.data.ByteAccessorBehavior.class, //
	ceri.common.data.ByteArrayBehavior.class, //
	ceri.common.data.ByteProviderBehavior.class, //
	ceri.common.data.ByteReaderBehavior.class, //
	ceri.common.data.ByteReceiverBehavior.class, //
	ceri.common.data.ByteStreamBehavior.class, //
	ceri.common.data.ByteUtilTest.class, //
	ceri.common.data.ByteWriterBehavior.class, //
	ceri.common.data.CrcAlgorithmBehavior.class, //
	ceri.common.data.CrcBehavior.class, //
	ceri.common.data.DataUtilTest.class, //
	ceri.common.data.FieldTranscoderBehavior.class, //
	ceri.common.data.IntAccessorBehavior.class, //
	ceri.common.data.IntArrayBehavior.class, //
	ceri.common.data.IntBitSetBehavior.class, //
	ceri.common.data.IntFieldBehavior.class, //
	ceri.common.data.IntProviderBehavior.class, //
	ceri.common.data.IntReaderBehavior.class, //
	ceri.common.data.IntReceiverBehavior.class, //
	ceri.common.data.IntTypeValueBehavior.class, //
	ceri.common.data.IntWriterBehavior.class, //
	ceri.common.data.MaskTranscoderBehavior.class, //
	ceri.common.data.NavigatorBehavior.class, //
	ceri.common.data.TypeTranscoderBehavior.class, //
	ceri.common.data.XorBehavior.class, //
	// event
	ceri.common.event.EventTrackerBehavior.class, //
	ceri.common.event.IntListenableBehavior.class, //
	ceri.common.event.IntListenersBehavior.class, //
	ceri.common.event.ListenableBehavior.class, //
	ceri.common.event.ListenersBehavior.class, //
	// exception
	ceri.common.exception.ExceptionAdapterBehavior.class, //
	ceri.common.exception.ExceptionTrackerBehavior.class, //
	ceri.common.exception.ExceptionUtilTest.class, //
	// function
	ceri.common.function.AccessorBehavior.class, //
	ceri.common.function.BooleanConsumerBehavior.class, //
	ceri.common.function.ByteConsumerBehavior.class, //
	ceri.common.function.ExceptionBiConsumerBehavior.class, //
	ceri.common.function.ExceptionBiFunctionBehavior.class, //
	ceri.common.function.ExceptionBiPredicateBehavior.class, //
	ceri.common.function.ExceptionBooleanSupplierBehavior.class, //
	ceri.common.function.ExceptionConsumerBehavior.class, //
	ceri.common.function.ExceptionFunctionBehavior.class, //
	ceri.common.function.ExceptionIntBinaryOperatorBehavior.class, //
	ceri.common.function.ExceptionIntConsumerBehavior.class, //
	ceri.common.function.ExceptionIntFunctionBehavior.class, //
	ceri.common.function.ExceptionIntPredicateBehavior.class, //
	ceri.common.function.ExceptionIntSupplierBehavior.class, //
	ceri.common.function.ExceptionIntUnaryOperatorBehavior.class, //
	ceri.common.function.ExceptionLongConsumerBehavior.class, //
	ceri.common.function.ExceptionLongFunctionBehavior.class, //
	ceri.common.function.ExceptionLongPredicateBehavior.class, //
	ceri.common.function.ExceptionLongSupplierBehavior.class, //
	ceri.common.function.ExceptionLongUnaryOperatorBehavior.class, //
	ceri.common.function.ExceptionObjIntConsumerBehavior.class, //
	ceri.common.function.ExceptionObjIntFunctionBehavior.class, //
	ceri.common.function.ExceptionObjIntPredicateBehavior.class, //
	ceri.common.function.ExceptionPredicateBehavior.class, //
	ceri.common.function.ExceptionRunnableBehavior.class, //
	ceri.common.function.ExceptionSupplierBehavior.class, //
	ceri.common.function.ExceptionToIntFunctionBehavior.class, //
	ceri.common.function.FluentBehavior.class, //
	ceri.common.function.FunctionUtilTest.class, //
	ceri.common.function.FunctionWrapperBehavior.class, //
	ceri.common.function.NamedPredicateBuilderBehavior.class, //
	ceri.common.function.ObjBooleanConsumerBehavior.class, //
	ceri.common.function.ObjByteConsumerBehavior.class, //
	ceri.common.function.ObjIntPredicateBehavior.class, //
	ceri.common.function.ObjShortConsumerBehavior.class, //
	ceri.common.function.PredicatesTest.class, //
	ceri.common.function.ToBooleanFunctionBehavior.class, //
	ceri.common.function.ToByteFunctionBehavior.class, //
	ceri.common.function.ToShortFunctionBehavior.class, //
	// geom
	ceri.common.geom.Circle2dBehavior.class, //
	ceri.common.geom.ConcaveSpheroidBehavior.class, //
	ceri.common.geom.Cone3dBehavior.class, //
	ceri.common.geom.Cylinder3dBehavior.class, //
	ceri.common.geom.Dimension2dBehavior.class, //
	ceri.common.geom.Ellipse2dBehavior.class, //
	ceri.common.geom.Ellipsoid3dBehavior.class, //
	ceri.common.geom.GeometryUtilTest.class, //
	ceri.common.geom.InvertedRadial3dBehavior.class, //
	ceri.common.geom.Line2dBehavior.class, //
	ceri.common.geom.Line2dEquationBehavior.class, //
	ceri.common.geom.LineUtilTest.class, //
	ceri.common.geom.Point2dBehavior.class, //
	ceri.common.geom.Polar2dBehavior.class, //
	ceri.common.geom.Radial3dBehavior.class, //
	ceri.common.geom.Ratio2dBehavior.class, //
	ceri.common.geom.Rectangle2dBehavior.class, //
	ceri.common.geom.Shape3dUtilTest.class, //
	ceri.common.geom.Spheroid3dBehavior.class, //
	ceri.common.geom.TruncatedRadial3dBehavior.class, //
	// io
	ceri.common.io.BufferedOutputStreamBehavior.class, //
	ceri.common.io.DeviceModeBehavior.class, //
	ceri.common.io.FileTrackerBehavior.class, //
	ceri.common.io.FileVisitUtilTest.class, //
	ceri.common.io.IoStreamUtilTest.class, //
	ceri.common.io.IoTimeoutExceptionBehavior.class, //
	ceri.common.io.IoUtilTest.class, //
	ceri.common.io.KeyCheckerBehavior.class, //
	ceri.common.io.PathFiltersTest.class, //
	ceri.common.io.PathPatternBehavior.class, //
	ceri.common.io.PipedStreamBehavior.class, //
	ceri.common.io.PollingInputStreamBehavior.class, //
	ceri.common.io.ReplaceableInputStreamBehavior.class, //
	ceri.common.io.ReplaceableOutputStreamBehavior.class, //
	ceri.common.io.ResourcePathBehavior.class, //
	ceri.common.io.RuntimeEofExceptionBehavior.class, //
	ceri.common.io.RuntimeIoExceptionBehavior.class, //
	ceri.common.io.StateChangeBehavior.class, //
	ceri.common.io.StringPrintStreamBehavior.class, //
	// log
	ceri.common.log.LevelBehavior.class, //
	ceri.common.log.LoggerBehavior.class, //
	// math
	ceri.common.math.AlgebraUtilTest.class, //
	ceri.common.math.BoundBehavior.class, //
	ceri.common.math.FractionBehavior.class, //
	ceri.common.math.IntervalBehavior.class, //
	ceri.common.math.IntervalUtilTest.class, //
	ceri.common.math.MathUtilTest.class, //
	ceri.common.math.MatrixBehavior.class, //
	ceri.common.math.MixedFractionBehavior.class, //
	ceri.common.math.NumberPatternsBehavior.class, //
	ceri.common.math.ReverseFunctionBehavior.class, //
	ceri.common.math.TrigUtilTest.class, //
	// net
	ceri.common.net.AddressTypeBehavior.class, //
	ceri.common.net.EmailUtilTest.class, //
	ceri.common.net.HostPortBehavior.class, //
	ceri.common.net.NetUtilTest.class, //
	ceri.common.net.UdpUtilTest.class, //
	// process
	ceri.common.process.ColumnsBehavior.class, //
	ceri.common.process.NullProcessBehavior.class, //
	ceri.common.process.OutputBehavior.class, //
	ceri.common.process.ParametersBehavior.class, //
	ceri.common.process.ProcessUtilTest.class, //
	ceri.common.process.ProcessorBehavior.class, //
	// property
	ceri.common.property.BasePropertiesBehavior.class, //
	ceri.common.property.LocatorBehavior.class, //
	ceri.common.property.PathBehavior.class, //
	ceri.common.property.PathFactoryBehavior.class, //
	ceri.common.property.PropertyAccessorBehavior.class, //
	ceri.common.property.PropertyUtilTest.class, //
	// reflect
	ceri.common.reflect.CallerBehavior.class, //
	ceri.common.reflect.CreateExceptionBehavior.class, //
	ceri.common.reflect.ReflectUtilTest.class, //
	// score
	ceri.common.score.CollectionScorersTest.class, //
	ceri.common.score.ScoreLookupBehavior.class, //
	ceri.common.score.ScoreResultBehavior.class, //
	ceri.common.score.ScorersTest.class, //
	// sql
	ceri.common.sql.SqlFormatterBehavior.class, //
	ceri.common.sql.SqlStatementBehavior.class, //
	ceri.common.sql.SqlUtilTest.class, //
	// svg
	ceri.common.svg.EllipseBehavior.class, //
	ceri.common.svg.EllipticalArcBehavior.class, //
	ceri.common.svg.GroundedPathBehavior.class, //
	ceri.common.svg.LargeArcFlagBehavior.class, //
	ceri.common.svg.LineToBehavior.class, //
	ceri.common.svg.MoveToBehavior.class, //
	ceri.common.svg.PathGroupBehavior.class, //
	ceri.common.svg.PositionBehavior.class, //
	ceri.common.svg.SvgUtilTest.class, //
	ceri.common.svg.SweepFlagBehavior.class, //
	// test
	ceri.common.test.AssertUtilTest.class, //
	ceri.common.test.BinaryPrinterBehavior.class, //
	ceri.common.test.BranchCaptorBehavior.class, //
	ceri.common.test.CallSyncBehavior.class, //
	ceri.common.test.CaptorBehavior.class, //
	ceri.common.test.DebuggerBehavior.class, //
	ceri.common.test.ErrorGenBehavior.class, //
	ceri.common.test.FileTestHelperBehavior.class, //
	ceri.common.test.PulsePrinterBehavior.class, //
	ceri.common.test.TestConnectorBehavior.class, //
	ceri.common.test.TestExecutorServiceBehavior.class, //
	ceri.common.test.TestFutureBehavior.class, //
	ceri.common.test.TestInputStreamBehavior.class, //
	ceri.common.test.TestListenerBehavior.class, //
	ceri.common.test.TestListenersBehavior.class, //
	ceri.common.test.TestOutputStreamBehavior.class, //
	ceri.common.test.TestPrinterBehavior.class, //
	ceri.common.test.TestProcessBehavior.class, //
	ceri.common.test.TestRunAdapterBehavior.class, //
	ceri.common.test.TestSocketBehavior.class, //
	ceri.common.test.TestStyleBehavior.class, //
	ceri.common.test.TestTimerBehavior.class, //
	ceri.common.test.TestUtilTest.class, //
	// text
	ceri.common.text.AnsiEscapeBehavior.class, //
	ceri.common.text.DsvCodecBehavior.class, //
	ceri.common.text.DsvParserBehavior.class, //
	ceri.common.text.FractionFormatsTest.class, //
	ceri.common.text.MarshallerBehavior.class, //
	ceri.common.text.MultiPatternBehavior.class, //
	ceri.common.text.NonMatchResultBehavior.class, //
	ceri.common.text.NonMatcherBehavior.class, //
	ceri.common.text.RegexSequencerBehavior.class, //
	ceri.common.text.RegexUtilTest.class, //
	ceri.common.text.SplitterBehavior.class, //
	ceri.common.text.StringTypeBehavior.class, //
	ceri.common.text.StringUtilTest.class, //
	ceri.common.text.TextUtilTest.class, //
	ceri.common.text.ToStringBehavior.class, //
	ceri.common.text.Utf8UtilTest.class, //
	// time
	ceri.common.time.CalendarFieldBehavior.class, //
	ceri.common.time.DateUtilTest.class, //
	ceri.common.time.HolidayBehavior.class, //
	ceri.common.time.TimeoutBehavior.class, //
	ceri.common.time.TimerBehavior.class, //
	// tree
	ceri.common.tree.NodeTreeBehavior.class, //
	ceri.common.tree.TreeIteratorBehavior.class, //
	ceri.common.tree.TreeNodeBehavior.class, //
	ceri.common.tree.TreeNodeComparatorsTest.class, //
	ceri.common.tree.TreeUtilTest.class, //
	// util
	ceri.common.util.AlignBehavior.class, //
	ceri.common.util.BasicUtilTest.class, //
	ceri.common.util.CounterBehavior.class, //
	ceri.common.util.EnclosedBehavior.class, //
	ceri.common.util.HasherBehavior.class, //
	ceri.common.util.HolderBehavior.class, //
	ceri.common.util.KeyValueBehavior.class, //
	ceri.common.util.LatLngBehavior.class, //
	ceri.common.util.LocaleUtilTest.class, //
	ceri.common.util.OsUtilTest.class, //
	ceri.common.util.PrimitiveUtilTest.class, //
	ceri.common.util.StartupValuesBehavior.class, //
	ceri.common.util.SystemVarsTest.class, //
	ceri.common.util.ValueCacheBehavior.class, //
	// validation
	ceri.common.validation.DisplayDoubleBehavior.class, //
	ceri.common.validation.DisplayLongBehavior.class, //
	ceri.common.validation.ValidationUtilTest.class, //
	// xml
	ceri.common.xml.RuntimeXPathExceptionBehavior.class, //
	ceri.common.xml.XPathUtilTest.class, //
	ceri.common.xml.XmlUtilTest.class, //
})
public class _Tests {
	public static void main(String... args) {
		TestUtil.exec(_Tests.class);
	}
}
